codeready-toolchain/host-operator

OWNERS

chore: add OWNERS

---

.yamllint
Makefile
make/dev.mk
make/find-tools.mk
make/format.mk
make/git.mk
make/go.mk
make/help.mk
make/lint.mk
make/out.mk
make/test.mk
make/verbose.mk
openshift-ci/Dockerfile.deploy
openshift-ci/Dockerfile.tools

*Changes Proposed in this PR*
- add required make targets for openshift-ci
- add required dockerfiles for openshift-ci
- other configuration files like `.yamllint`
- add `build/bin` directory to build operator container using `operator-sdk`

chore: enable openshift ci

---

deploy/crds/toolchain_v1alpha1_masteruserrecord.yaml
examples/toolchain_v1alpha1_masteruserrecord_cr.yaml

We need **UserID** to create **Identity** and **UserIdentityMapping** resources.

Add UserID to MasterUserRecord

---

deploy/crds/toolchain_v1alpha1_masteruserrecord.yaml
examples/toolchain_v1alpha1_masteruserrecord_cr.yaml

See https://github.com/codeready-toolchain/api/pull/12

Rename ResourceVersion to SyncIndex in MasterUserRecord

---

deploy/crds/toolchain_v1alpha1_masteruserrecord.yaml

See https://github.com/codeready-toolchain/api/pull/14

Rename Status.ResourceVersion to SyncIndex in MasterUserRecord

---

deploy/crds/toolchain_v1alpha1_masteruserrecord.yaml
examples/toolchain_v1alpha1_masteruserrecord_cr.yaml
go.mod
go.sum
make/clean.mk

See https://github.com/codeready-toolchain/api/pull/15

Add conditions to MUR status

---

deploy/crds/toolchain_v1alpha1_masteruserrecord.yaml
deploy/crds/toolchain_v1alpha1_userprovisionrequest.yaml
deploy/role.yaml
examples/toolchain_v1alpha1_userprovisionrequest_cr.yaml
go.mod
go.sum

See https://github.com/codeready-toolchain/api/pull/16

UserProvisionRequest CRD

---

deploy/crds/toolchain_v1alpha1_masteruserrecord.yaml
deploy/crds/toolchain_v1alpha1_usersignup.yaml

left over from - https://github.com/codeready-toolchain/api/pull/18/files

change due to api make genreate

---

build/bin/entrypoint
build/bin/user_setup

restore missing scripts to build Docker image

---

.codecov.yaml

fix missing reports on codecov.io

---

go.mod
go.sum

Failing to find `UserSignupList` schema as using old api version. Now updated to latest

update api version 

---

make/test.mk

*Changes Proposed in this PR*
* Add make target to deploy member-operator
* Add make target to create kubefedcluster cr

deploy member-operator for e2e tests

---

make/test.mk

same as https://github.com/codeready-toolchain/member-operator/pull/47

feat: add/modify make targets to clean e2e namespaces

---

deploy/crds/toolchain_v1alpha1_masteruserrecord.yaml
deploy/crds/toolchain_v1alpha1_usersignup.yaml

Result of `make generate` after https://github.com/codeready-toolchain/api/pull/28 

preserve custom fields in CRDs

---

deploy/crds/toolchain_v1alpha1_usersignup.yaml

see https://github.com/codeready-toolchain/api/pull/30

fix JSONPath syntax for additionalPrinterColumns

---

.golangci.yml
pkg/controller/masteruserrecord/masteruserrecord_controller.go
pkg/controller/masteruserrecord/masteruserrecord_controller_test.go
pkg/controller/masteruserrecord/sync_test.go
pkg/controller/usersignup/usersignup_controller.go

also, few extra changes reported by go-lint

configure 'unparam' linter and clean code accordingly

---

cmd/manager/main.go
cmd/manager/main_test.go
go.sum

add commit and buildtime vars

---

deploy/crds/toolchain_v1alpha1_usersignup_crd.yaml
deploy/olm-catalog/host-operator/0.0.1/toolchain_v1alpha1_usersignup_crd.yaml
examples/toolchain_v1alpha1_usersignup_cr.yaml
hack/deploy_csv.yaml

Related to https://github.com/codeready-toolchain/api/pull/48

Remove UserID from UserSignup.Spec

---

deploy/crds/toolchain_v1alpha1_masteruserrecord_crd.yaml
deploy/crds/toolchain_v1alpha1_nstemplatetier_crd.yaml
deploy/crds/toolchain_v1alpha1_usersignup_crd.yaml
deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain-host-operator.v0.0.1.clusterserviceversion.yaml
deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain_v1alpha1_masteruserrecord_crd.yaml
deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain_v1alpha1_nstemplatetier_crd.yaml
deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain_v1alpha1_usersignup_crd.yaml
hack/deploy_csv.yaml

See https://github.com/codeready-toolchain/api/pull/51

Regenerate manifests by controller-runtime 0.2

---

openshift-ci/Dockerfile.tools

to unblock e2e tests executed in host-operator repo

fix(e2e): install gcc in Dockerfile.tools

---

deploy/crds/toolchain_v1alpha1_masteruserrecord_crd.yaml
deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain-host-operator.v0.0.1.clusterserviceversion.yaml
deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain_v1alpha1_masteruserrecord_crd.yaml
hack/deploy_csv.yaml

Generated by https://github.com/codeready-toolchain/api/pull/59

Add details about cluster for UserAccounts in MUR

---

README.adoc

...so we know that it's passing or failing :-)

chore: add CD status images

---

deploy/cluster_role.yaml
deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain-host-operator.v0.0.1.clusterserviceversion.yaml
deploy/role.yaml
hack/deploy_csv.yaml

add missing permissions to serviceaccount

---

deploy/templates/nstemplatetiers/advanced-code.yaml
deploy/templates/nstemplatetiers/advanced-dev.yaml
deploy/templates/nstemplatetiers/advanced-stage.yaml
deploy/templates/nstemplatetiers/basic-code.yaml
deploy/templates/nstemplatetiers/basic-dev.yaml
deploy/templates/nstemplatetiers/basic-stage.yaml
pkg/templates/nstemplatetiers/nstemplatetier_generator_whitebox_test.go

So, the user has edit role in -code, -dev, and -stage namespaces.
E2E tests: https://github.com/codeready-toolchain/toolchain-e2e/pull/49
TODO:

Add edit role to ns templates

---

deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain-host-operator.v0.0.1.clusterserviceversion.yaml
hack/deploy_csv.yaml
hack/install_operator.yaml

see https://github.com/codeready-toolchain/api/pull/67

chore: reflect changes in hack resource names

---

deploy/crds/toolchain_v1alpha1_usersignup_crd.yaml
deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain-host-operator.v0.0.1.clusterserviceversion.yaml
deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain_v1alpha1_usersignup_crd.yaml
go.mod
go.sum
hack/deploy_csv.yaml

As an admin, I want to see the user email when approving an account. This makes my work easier as I can see where the user is coming from (e.g. redhat.com).
This PR requires the api PR to be merged for tests to pass.. 
Relates to:
jira - https://jira.coreos.com/browse/CRT-374
api - codeready-toolchain/api#69
e2e- https://github.com/codeready-toolchain/toolchain-e2e/pull/55
reg - https://github.com/codeready-toolchain/registration-service/pull/78

adding email to usersignup

---

deploy/olm-catalog/host-operator/host-operator.package.yaml

https://github.com/codeready-toolchain/host-operator/pull/118#discussion_r356470203

fix: remove the outdated host-operator package file

---

deploy/crds/toolchain_v1alpha1_usersignup_crd.yaml
deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain-host-operator.v0.0.1.clusterserviceversion.yaml
deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain_v1alpha1_usersignup_crd.yaml
hack/deploy_csv.yaml

This PR adds the files generated from adding a new `Deactivated` property to `UserSignup`.

Add Deactivated property to UserSignup

---

deploy/crds/toolchain_v1alpha1_masteruserrecord_crd.yaml
deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain-host-operator.v0.0.1.clusterserviceversion.yaml
deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain_v1alpha1_masteruserrecord_crd.yaml
hack/deploy_csv.yaml

See https://github.com/codeready-toolchain/api/pull/75

Add Che URL to MUR status

---

deploy/cluster_role.yaml
deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain-host-operator.v0.0.1.clusterserviceversion.yaml
hack/deploy_csv.yaml

See https://github.com/codeready-toolchain/member-operator/pull/110

Permission error in host

---

go.mod
go.sum

see https://github.com/codeready-toolchain/api/pull/82

chore: update api repo to use openshift/api@release-4.2

---

deploy/crds/toolchain_v1alpha1_banneduser_crd.yaml
deploy/olm-catalog/host-operator/host-operator.package.yaml
deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain-host-operator.v0.0.1.clusterserviceversion.yaml
deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain_v1alpha1_banneduser_crd.yaml
examples/toolchain_v1alpha1_banneduser_cr.yaml
hack/deploy_csv.yaml

Regenerated from api - added BannedUser type

---

deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain-host-operator.v0.0.1.clusterserviceversion.yaml
hack/deploy_csv.yaml

see https://github.com/codeready-toolchain/host-operator/pull/134#issuecomment-572432463

fix: propagate BannedUser into deploy hack file & regenerate base CSV

---

deploy/crds/toolchain_v1alpha1_masteruserrecord_crd.yaml
deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain-host-operator.v0.0.1.clusterserviceversion.yaml
deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain_v1alpha1_masteruserrecord_crd.yaml
go.mod
go.sum
hack/deploy_csv.yaml
pkg/controller/masteruserrecord/masteruserrecord_controller.go
pkg/controller/masteruserrecord/sync.go
pkg/controller/usersignup/usersignup_controller.go
pkg/controller/usersignup/usersignup_controller_test.go

Deprecating Embedded UserAccount ID and UserAccount Disabled fields.
Related PR in API: https://github.com/codeready-toolchain/api/pull/105
Relates to Jira task: https://issues.redhat.com/browse/CRT-457
Relates to Jira story: https://issues.redhat.com/browse/CRT-444
This will be done in three stages:
1. Deprecate Embedded UA ID/Disabled
1.1 PRs:
https://github.com/codeready-toolchain/api/pull/100
https://github.com/codeready-toolchain/host-operator/pull/143
2. Change the implementation and start using the new API. Roll out to prod.
2.1 PRs: 
https://github.com/codeready-toolchain/host-operator/pull/146
https://github.com/codeready-toolchain/toolchain-e2e/pull/73
3. Delete deprecated API.
3.1 PRs:
https://github.com/codeready-toolchain/api/pull/105 …

Delete deprecated API

---

go.mod
go.sum
pkg/controller/registrationservice/registrationservice_controller.go

Moving registration_service_controller reasons to api and using them from api. 
relates to api PR: https://github.com/codeready-toolchain/api/pull/112

moving reaosns to api

---

go.mod
go.sum
pkg/controller/usersignup/usersignup_controller.go

Moving usersignup reasons to api and using them.
Relates to the following PR: https://github.com/codeready-toolchain/api/pull/113

using reasons from api

---

go.mod
go.sum
pkg/controller/changetierrequest/changetierrequest_controller.go
pkg/controller/controller.go

just a result of 
```
operator-sdk add controller --api-version=toolchain.dev.openshift.com/v1alpha1 --kind=ChangeTierRequest 
```
plus some cleanup 
plus update of api repo

chore: generate basic scaffolding of changetierrequest controller

---

deploy/crds/toolchain_v1alpha1_masteruserrecord_crd.yaml
deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain_v1alpha1_masteruserrecord_crd.yaml
hack/deploy_csv.yaml

result of https://github.com/codeready-toolchain/api/pull/117

add 'clusterResources' field in NSTemplateSet

---

make/test.mk

openshift CI migrated to a new cluster

chore: use registry URL in new CI cluster

---

make/test.mk

instead of using hardcoded URL (that was changing recently) we can use a variable to load the image location

chore: use host-operator image location from variable

---

deploy/templates/nstemplatetiers/advanced/ns_dev.yaml
deploy/templates/nstemplatetiers/advanced/ns_stage.yaml
pkg/templates/nstemplatetiers/nstemplatetier_generator_whitebox_test.go

e2e tests: https://github.com/codeready-toolchain/toolchain-e2e/pull/101

Add permissions to edit rbac for advanced tier

---

deploy/templates/nstemplatetiers/advanced/cluster.yaml
deploy/templates/nstemplatetiers/advanced/ns_code.yaml
deploy/templates/nstemplatetiers/advanced/ns_dev.yaml
deploy/templates/nstemplatetiers/advanced/ns_stage.yaml
deploy/templates/nstemplatetiers/basic/cluster.yaml
deploy/templates/nstemplatetiers/basic/ns_code.yaml
deploy/templates/nstemplatetiers/basic/ns_dev.yaml
deploy/templates/nstemplatetiers/basic/ns_stage.yaml
deploy/templates/nstemplatetiers/team/cluster.yaml
deploy/templates/nstemplatetiers/team/ns_dev.yaml
deploy/templates/nstemplatetiers/team/ns_stage.yaml
go.mod
go.sum
pkg/templates/nstemplatetiers/nstemplatetier_generator_whitebox_test.go

Removing provider label from namespace template tiers.
Jira story: https://issues.redhat.com/browse/CRT-495

removing provider label from tiers

---

deploy/crds/toolchain_v1alpha1_usersignup_crd.yaml
deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain_v1alpha1_usersignup_crd.yaml
hack/deploy_csv.yaml

result of: https://github.com/codeready-toolchain/api/pull/127
Jira Task: https://issues.redhat.com/browse/CRT-518

adding fields for notification service

---

deploy/crds/toolchain_v1alpha1_notification_crd.yaml
deploy/crds/toolchain_v1alpha1_notificationtemplate_crd.yaml
deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain-host-operator.v0.0.1.clusterserviceversion.yaml
deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain_v1alpha1_notification_crd.yaml
deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain_v1alpha1_notificationtemplate_crd.yaml
hack/deploy_csv.yaml

Issue: https://issues.redhat.com/browse/CRT-507
Modifications made as a result of `make generate` from API package.

CRT-507 generated from api - notification types

---

deploy/crds/toolchain_v1alpha1_masteruserrecord_crd.yaml
deploy/crds/toolchain_v1alpha1_notification_crd.yaml
deploy/crds/toolchain_v1alpha1_nstemplatetier_crd.yaml
deploy/crds/toolchain_v1alpha1_tiertemplate_crd.yaml
deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain-host-operator.v0.0.1.clusterserviceversion.yaml
deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain_v1alpha1_masteruserrecord_crd.yaml
deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain_v1alpha1_notification_crd.yaml
deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain_v1alpha1_nstemplatetier_crd.yaml
deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain_v1alpha1_tiertemplate_crd.yaml
hack/deploy_csv.yaml

Regenerated files from the api repository
Updates https://issues.redhat.com/browse/CRT-499

feat: add TemplateTier CRD

---

deploy/crds/toolchain_v1alpha1_tiertemplate_crd.yaml
deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain_v1alpha1_tiertemplate_crd.yaml
hack/deploy_csv.yaml

See https://github.com/codeready-toolchain/api/pull/131

feat: add TierTemplateSpec.TierName field

---

go.mod
go.sum
pkg/controller/registrationservice/registrationservice_controller.go
pkg/controller/registrationservice/registrationservice_controller_test.go
pkg/controller/registrationservice/template_test.go

see codeready-toolchain/toolchain-common#100

chore: update common and reflect changes

---

deploy/crds/toolchain_v1alpha1_masteruserrecord_crd.yaml
deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain_v1alpha1_masteruserrecord_crd.yaml
hack/deploy_csv.yaml

result of https://github.com/codeready-toolchain/api/pull/133

chore: add tier name to MUR printcolumns

---

go.mod
go.sum
pkg/controller/changetierrequest/changetierrequest_controller.go
pkg/controller/changetierrequest/changetierrequest_controller_test.go
pkg/controller/usersignup/usersignup_controller.go
pkg/controller/usersignup/usersignup_controller_test.go
pkg/templates/nstemplatetiers/nstemplatetier_generator.go
pkg/templates/nstemplatetiers/nstemplatetier_generator_whitebox_test.go

Set the `TemplateRef` field in the namespaces
and cluster resources of the MUR during provisioning.
Updates https://issues.redhat.com/browse/CRT-500

feat: set TemplateRef in MUR spec

---

deploy/crds/toolchain_v1alpha1_masteruserrecord_crd.yaml
deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain_v1alpha1_masteruserrecord_crd.yaml
go.mod
go.sum
hack/deploy_csv.yaml

source: https://github.com/codeready-toolchain/api/pull/136

chore(CRT-501): make legacy fields optional and templateRef mandatory

---

go.mod
go.sum
pkg/configuration/configuration.go
pkg/controller/notification/notification_context_test.go
pkg/controller/notification/notification_controller.go
pkg/controller/notification/notification_controller_test.go

This PR creates a base notification controller which implements the logic to delete a notification once the duration_before_notification_deletion time has elapsed. 
Jira: https://issues.redhat.com/browse/CRT-508
Related PR: https://github.com/codeready-toolchain/api/pull/156

notification controller with notification cleanup

---

deploy/env/e2e-tests.yaml
go.mod
go.sum
pkg/configuration/configuration.go
pkg/controller/changetierrequest/changetierrequest_controller.go
pkg/controller/changetierrequest/changetierrequest_controller_test.go
pkg/controller/controller.go
pkg/controller/notification/mailgun_notification_delivery_service.go
pkg/controller/notification/mock_notification_delivery_service.go
pkg/controller/notification/notification_context_test.go
pkg/controller/notification/notification_controller.go
pkg/controller/notification/notification_controller_test.go
pkg/controller/notification/notification_delivery_service.go

This PR is addressing comments from: https://github.com/codeready-toolchain/host-operator/pull/226
Related PRs: 
https://github.com/codeready-toolchain/api/pull/157
e2e-tests to come...

fixing code for changetierrequest and notification

---

pkg/controller/notification/notification_delivery_service.go
pkg/controller/notification/notification_delivery_service_test.go

Adds a base implementation class for delivery services that provides commonly used functions.
fixes https://issues.redhat.com/browse/CRT-693

Base implementation class for delivery services

---

cmd/manager/main.go
deploy/env/prod.yaml
go.sum
pkg/configuration/configuration.go
pkg/configuration/configuration_test.go
pkg/controller/changetierrequest/changetierrequest_controller_test.go
pkg/controller/notification/notification_controller_test.go
pkg/controller/registrationservice/creation_test.go

adding secret for mailgun.
Related Jira: https://issues.redhat.com/browse/CRT-697
toolchain-infra PR: https://github.com/codeready-toolchain/toolchain-infra/pull/21

create mailgun secret

---

deploy/env/prod.yaml
pkg/configuration/configuration.go
pkg/configuration/configuration_test.go

adding configMap for host operator as discussed here: codeready-toolchain/host-operator#238 (comment)
this adds the registration service url
related to: https://github.com/codeready-toolchain/toolchain-infra/pull/26

Add hostoperator configmap

---

pkg/controller/notification/mailgun_notification_delivery_service.go
pkg/controller/notification/mailgun_notification_delivery_service_test.go
pkg/controller/notification/notification_controller.go
pkg/controller/notification/notification_controller_test.go
pkg/controller/notification/notification_delivery_service.go
pkg/controller/notification/notification_delivery_service_test.go

Addressing comment: https://github.com/codeready-toolchain/host-operator/pull/238#discussion_r456266976

Avoid passing config twice

---

cmd/manager/main.go
pkg/configuration/configuration.go
pkg/configuration/configuration_test.go
pkg/controller/changetierrequest/changetierrequest_controller.go
pkg/controller/nstemplatetier/nstemplatetier_controller.go
pkg/controller/nstemplatetier/nstemplatetier_controller_test.go

replace the constant defined in the NSTemplateTier
controller with a variable defined in the configuration,
with a default value equal to the aforementioned const.
Also, rename a config var and default for other deletions
Fixes https://issues.redhat.com/browse/CRT-707

define MaxPoolSize in configuration

---

go.mod
go.sum
pkg/controller/notification/mailgun_notification_delivery_service_test.go
pkg/controller/toolchainstatus/toolchainstatus_controller.go

Related PR: https://github.com/codeready-toolchain/toolchain-common/pull/118
This PR updates the condition/error handling to use `ValidateComponentConditionReady` to get errors directly from the component conditions.

Update component condition/error handling

---

deploy/crds/toolchain_v1alpha1_toolchaincluster_crd.yaml
deploy/olm-catalog/toolchain-host-operator/manifests/toolchain-host-operator.clusterserviceversion.yaml
deploy/olm-catalog/toolchain-host-operator/manifests/toolchain_v1alpha1_toolchaincluster_crd.yaml
hack/deploy_csv.yaml

Adds ToolchainCluster CRD
result of https://github.com/codeready-toolchain/api/pull/172

chore: add ToolchainCluster CRD

---

deploy/crds/toolchain_v1alpha1_usersignup_crd.yaml
deploy/olm-catalog/toolchain-host-operator/manifests/toolchain_v1alpha1_usersignup_crd.yaml
hack/deploy_csv.yaml

Added optional VerificationRequired boolean attribute to UserSignupSpec for phone verification in API repo. This code is generated via api changes.
Jira: https://issues.redhat.com/browse/CRT-759
Related PR:

generated usersignup phone verification api changes

---

deploy/crds/toolchain_v1alpha1_toolchainstatus_crd.yaml
deploy/olm-catalog/toolchain-host-operator/manifests/toolchain_v1alpha1_toolchainstatus_crd.yaml
hack/deploy_csv.yaml

result of https://github.com/codeready-toolchain/api/pull/182

chore: add counts to ToolchainStatus

---

go.mod
go.sum

includes changes from https://github.com/codeready-toolchain/toolchain-common/pull/126

toolchain-common module update

---

deploy/crds/toolchain_v1alpha1_toolchainstatus_crd.yaml
deploy/olm-catalog/toolchain-host-operator/manifests/toolchain_v1alpha1_toolchainstatus_crd.yaml
hack/deploy_csv.yaml

reflect changes in https://github.com/codeready-toolchain/api/pull/188

chore: add resource usage to MemberStatus & refactor ToolchainStatus

---

deploy/crds/toolchain_v1alpha1_hostoperatorconfig_crd.yaml
deploy/olm-catalog/toolchain-host-operator/manifests/toolchain-host-operator.clusterserviceversion.yaml
deploy/olm-catalog/toolchain-host-operator/manifests/toolchain_v1alpha1_hostoperatorconfig_crd.yaml
go.mod
go.sum
hack/deploy_csv.yaml

Generated CRD from https://github.com/codeready-toolchain/api/pull/190 & updates API dependency

chore: introduce HostOperatorConfig CRD

---

go.mod
go.sum
pkg/controller/toolchainstatus/toolchainstatus_controller.go
pkg/controller/toolchainstatus/toolchainstatus_controller_test.go

Collects resource usages from member statuses and put them into ToolchainStatus.
Depends on: https://github.com/codeready-toolchain/toolchain-common/pull/130
paired with: https://github.com/codeready-toolchain/toolchain-e2e/pull/163

feat: collect resource usages from MemberStatuses into ToolchainStatus

---

pkg/controller/deactivation/deactivation_controller_test.go

Addresses comments from https://github.com/codeready-toolchain/host-operator/pull/281#pullrequestreview-489873528

chore: Minor fixes for deactivation controller test

---

deploy/registration-service/registration-service.yaml

adding list permissions for reg-service on usersignups. related to: https://github.com/codeready-toolchain/registration-service/pull/126

adding list permissions

---

deploy/env/prod.yaml

added twilio conf for staging

---

deploy/crds/toolchain_v1alpha1_usersignup_crd.yaml
deploy/olm-catalog/toolchain-host-operator/manifests/toolchain_v1alpha1_usersignup_crd.yaml
hack/deploy_csv.yaml

generated result of https://github.com/codeready-toolchain/api/pull/193

chore: add state label as another column to UserSignup

---

go.mod
go.sum
pkg/controller/usersignup/status.go
pkg/controller/usersignup/usersignup_controller.go
pkg/controller/usersignup/usersignup_controller_test.go

sets the values of the `state` label at `UserSignup` resources
depends on: https://github.com/codeready-toolchain/api/pull/193
paired with: https://github.com/codeready-toolchain/toolchain-e2e/pull/175

feat: set state label values at UserSignup

---

deploy/crds/toolchain_v1alpha1_toolchainstatus_crd.yaml
deploy/olm-catalog/toolchain-host-operator/manifests/toolchain_v1alpha1_toolchainstatus_crd.yaml
hack/deploy_csv.yaml

CRDs generated by https://github.com/codeready-toolchain/api/pull/194

Add Console and Che URLs to member and toolchain status resources

---

deploy/crds/toolchain_v1alpha1_toolchaincluster_crd.yaml
deploy/crds/toolchain_v1alpha1_toolchainstatus_crd.yaml
deploy/olm-catalog/toolchain-host-operator/manifests/toolchain_v1alpha1_toolchaincluster_crd.yaml
deploy/olm-catalog/toolchain-host-operator/manifests/toolchain_v1alpha1_toolchainstatus_crd.yaml
hack/deploy_csv.yaml

generated from https://github.com/codeready-toolchain/api/pull/196

chore: drop zones & region from ToolchainCluster

---

go.mod
go.sum

Apply changes from common (to verify that we don't break anything): https://github.com/codeready-toolchain/toolchain-common/pull/136

chore: apply changes from common (drop zones & region)

---

deploy/templates/nstemplatetiers/advanced/cluster.yaml
pkg/templates/nstemplatetiers/nstemplatetier_generator_whitebox_test.go

Paired with https://github.com/codeready-toolchain/toolchain-e2e/pull/183

No idlers in advanced tier

---

deploy/crds/toolchain_v1alpha1_usersignup_crd.yaml
deploy/olm-catalog/toolchain-host-operator/manifests/toolchain_v1alpha1_usersignup_crd.yaml
hack/deploy_csv.yaml

See https://github.com/codeready-toolchain/api/pull/197

Fix print column for usersignups

---

deploy/crds/toolchain_v1alpha1_notification_crd.yaml
deploy/olm-catalog/toolchain-host-operator/manifests/toolchain_v1alpha1_notification_crd.yaml
hack/deploy_csv.yaml

Fixes https://issues.redhat.com/browse/CRT-829

Added recipient to Notification CRD spec

---

deploy/crds/toolchain_v1alpha1_toolchainstatus_crd.yaml
deploy/olm-catalog/toolchain-host-operator/manifests/toolchain_v1alpha1_toolchainstatus_crd.yaml
hack/deploy_csv.yaml

Generated for https://github.com/codeready-toolchain/api/pull/201

Add MUR count print column to ToolchainStatus

---

deploy/crds/toolchain_v1alpha1_notification_crd.yaml
deploy/olm-catalog/toolchain-host-operator/manifests/toolchain_v1alpha1_notification_crd.yaml
hack/deploy_csv.yaml

Support for https://issues.redhat.com/browse/CRT-829
This PR supports API changes to the Notification CRD

Add subject and content properties to Notification CRD

---

deploy/templates/nstemplatetiers/advanced/cluster.yaml
deploy/templates/nstemplatetiers/advanced/ns_code.yaml
deploy/templates/nstemplatetiers/basic/cluster.yaml
deploy/templates/nstemplatetiers/basic/ns_code.yaml
deploy/templates/nstemplatetiers/basic/ns_dev.yaml
deploy/templates/nstemplatetiers/basic/ns_stage.yaml
deploy/templates/nstemplatetiers/team/cluster.yaml
pkg/templates/nstemplatetiers/nstemplatetier_generator_whitebox_test.go

e2e tests: https://github.com/codeready-toolchain/toolchain-e2e/pull/191

Tiers: 15Gi for storage & rbac-edit role for -dev and -stage

---

deploy/registration-service/registration-service.yaml

Required for https://github.com/codeready-toolchain/registration-service/pull/141

Add permissions to get toolchainstatus to reg-service

---

deploy/olm-catalog/toolchain-host-operator/manifests/toolchain-host-operator.clusterserviceversion.yaml
deploy/operator.yaml
hack/deploy_csv.yaml

Fixes https://issues.redhat.com/browse/CRT-786

operator resource requests and limits

---

deploy/templates/nstemplatetiers/advanced/ns_code.yaml
deploy/templates/nstemplatetiers/basic/ns_code.yaml
pkg/templates/nstemplatetiers/nstemplatetier_generator_whitebox_test.go

E2e tests: https://github.com/codeready-toolchain/toolchain-e2e/pull/198

Add Network Policy to allow ingress traffic from CRW namespace

---

pkg/configuration/configuration.go

Removed missed unused var from CRT-783 feature.

Remove unused var

---

pkg/controller/toolchainstatus/toolchainstatus_controller.go
pkg/controller/toolchainstatus/toolchainstatus_controller_test.go

Fixes https://issues.redhat.com/browse/CRT-881

Validation for admin.email config when sending ToolchainStatus notification

---

deploy/templates/nstemplatetiers/basic/tier.yaml
pkg/templates/nstemplatetiers/nstemplatetier_generator_whitebox_test.go

Change basic tier to 30 days deactivation.
Related to: https://github.com/codeready-toolchain/toolchain-e2e/pull/215

Change basic tier to 30 days deactivation

---

cmd/manager/main.go

exit(1) if metrics server fails to start

---

go.mod
go.sum
pkg/controller/toolchainstatus/toolchainstatus_controller.go
pkg/controller/toolchainstatus/toolchainstatus_controller_test.go
test/toolchainstatus_assertions.go

Fixes https://issues.redhat.com/browse/CRT-885
E2e tests: https://github.com/codeready-toolchain/toolchain-e2e/pull/214
Requires https://github.com/codeready-toolchain/toolchain-common/pull/143 to be merged first.

Update ToolchainStatus conditions instead of replacing them

---

deploy/crds/toolchain_v1alpha1_toolchainstatus_crd.yaml
deploy/olm-catalog/toolchain-host-operator/manifests/toolchain_v1alpha1_toolchainstatus_crd.yaml
deploy/registration-service/registration-service.yaml
hack/deploy_csv.yaml

Related PRs:
https://github.com/codeready-toolchain/member-operator/pull/231
https://github.com/codeready-toolchain/api/pull/210

Generated files for che memberstatus condition

---

README.adoc

chore: add info about releases

---

deploy/crds/toolchain_v1alpha1_usersignup_crd.yaml
deploy/olm-catalog/toolchain-host-operator/manifests/toolchain_v1alpha1_usersignup_crd.yaml
hack/deploy_csv.yaml

Fixes related to: https://issues.redhat.com/browse/CRT-915

Changes due to API regeneration

---

deploy/templates/nstemplatetiers/basic/cluster.yaml
deploy/templates/nstemplatetiers/basicdeactivationdisabled/cluster.yaml
pkg/templates/nstemplatetiers/nstemplatetier_generator_whitebox_test.go

paired with https://github.com/codeready-toolchain/toolchain-e2e/pull/228

chore: drop count limits for basic tier

---

deploy/templates/nstemplatetiers/team/cluster.yaml
pkg/templates/nstemplatetiers/nstemplatetier_generator_whitebox_test.go

E2e tests: https://github.com/codeready-toolchain/toolchain-e2e/pull/229

Disable idler in team tier

---

deploy/crds/toolchain_v1alpha1_usersignup_crd.yaml
deploy/olm-catalog/toolchain-host-operator/manifests/toolchain_v1alpha1_usersignup_crd.yaml
hack/deploy_csv.yaml

Generated for https://github.com/codeready-toolchain/api/pull/215

Make UserSignup.Spec.UserID required

---

pkg/controller/toolchainstatus/toolchainstatus_controller.go
pkg/controller/toolchainstatus/toolchainstatus_controller_test.go
pkg/counter/cache.go
pkg/counter/cache_test.go
pkg/metrics/metrics.go
pkg/metrics/metrics_test.go
test/counter.go
test/toolchainstatus.go

also, introduce a new 'indexOfMember' func
e2e: https://github.com/codeready-toolchain/toolchain-e2e/pull/245
Fixes https://issues.redhat.com/browse/CRT-970

feat: expose metrics for user accounts per member cluster

---

deploy/crds/toolchain_v1alpha1_notification_crd.yaml
deploy/olm-catalog/toolchain-host-operator/manifests/toolchain_v1alpha1_notification_crd.yaml
hack/deploy_csv.yaml

Related PR: https://github.com/codeready-toolchain/api/pull/216
Fixes https://issues.redhat.com/browse/CRT-983

Changes due to API make generate

---

deploy/templates/notificationtemplates/userprovisioned/notification.html
pkg/templates/notificationtemplates/notification_generator_test.go

Email notification updated to indicate 30 days trial period instead of 14days.

Email notification updated to indicate 30 days trial period

---

deploy/crds/toolchain_v1alpha1_toolchainstatus_crd.yaml
deploy/olm-catalog/toolchain-host-operator/manifests/toolchain_v1alpha1_toolchainstatus_crd.yaml
hack/deploy_csv.yaml

moving apiEndpoint from MemberStatusStatus to Member
fixes wrt: https://issues.redhat.com/browse/CRT-971 
related PR: https://github.com/codeready-toolchain/api/pull/221

CRDs updated for moving apiEndpoint to Member

---

deploy/crds/toolchain_v1alpha1_usersignup_crd.yaml
deploy/olm-catalog/toolchain-host-operator/manifests/toolchain_v1alpha1_usersignup_crd.yaml
hack/deploy_csv.yaml

Related API changes PR: https://github.com/codeready-toolchain/api/pull/222

API generated files

---

deploy/templates/nstemplatetiers/advanced/cluster.yaml
deploy/templates/nstemplatetiers/basic/cluster.yaml
deploy/templates/nstemplatetiers/basicdeactivationdisabled/cluster.yaml
deploy/templates/nstemplatetiers/team/cluster.yaml
pkg/templates/nstemplatetiers/nstemplatetier_generator_whitebox_test.go

https://issues.redhat.com/browse/CRT-1008
paired with https://github.com/codeready-toolchain/toolchain-e2e/pull/264

chore: increase cpu limit to 20 cores

---

make/go.mk

Fixes - https://issues.redhat.com/browse/CRT-1041
This PR allows to identify underlying and build
corresponding binaries as required
Signed-off-by: Krishna Harsha Voora <krishvoor@in.ibm.com>

Add support for mutil-architecture

---

deploy/templates/nstemplatetiers/base/cluster.yaml
deploy/templates/nstemplatetiers/basedeactivationdisabled/cluster.yaml
pkg/templates/nstemplatetiers/nstemplatetier_generator_whitebox_test.go

add limits for SBO and RHOAS operator 
paired with: https://github.com/codeready-toolchain/toolchain-e2e/pull/285

chore: add limits for RHOAS CRDs

---

deploy/crds/toolchain_v1alpha1_usersignup_crd.yaml
deploy/olm-catalog/toolchain-host-operator/manifests/toolchain_v1alpha1_usersignup_crd.yaml
go.mod
go.sum
hack/deploy_csv.yaml
pkg/controller/usersignup/usersignup_controller.go
pkg/controller/usersignup/usersignup_controller_test.go

Fixes https://issues.redhat.com/browse/CRT-1103
e2e tests PR: https://github.com/codeready-toolchain/toolchain-e2e/pull/296

API Regenerated - VerificationRequired property removed

---

make/manifests.mk

related PR https://github.com/codeready-toolchain/api/pull/232

chore: remove obsolete manifest target

---

pkg/controller/changetierrequest/changetierrequest_controller.go
pkg/controller/changetierrequest/changetierrequest_controller_test.go
pkg/controller/deactivation/deactivation_controller.go
pkg/controller/deactivation/deactivation_controller_test.go
pkg/controller/hostoperatorconfig/hostoperatorconfig_controller.go
pkg/controller/hostoperatorconfig/hostoperatorconfig_controller_test.go
pkg/controller/masteruserrecord/masteruserrecord_controller.go
pkg/controller/masteruserrecord/masteruserrecord_controller_test.go
pkg/controller/notification/notification_controller.go
pkg/controller/notification/notification_controller_test.go
pkg/controller/nstemplatetier/nstemplatetier_controller.go
pkg/controller/registrationservice/registrationservice_controller.go
pkg/controller/registrationservice/registrationservice_controller_test.go
pkg/controller/templateupdaterequest/templateupdaterequest_controller.go
pkg/controller/toolchainstatus/toolchainstatus_controller.go
pkg/controller/toolchainstatus/toolchainstatus_controller_test.go
pkg/controller/usersignup/usersignup_controller.go
pkg/controller/usersignup/usersignup_controller_test.go
pkg/controller/usersignupcleanup/usersignup_cleanup_controller.go
pkg/controller/usersignupcleanup/usersignup_cleanup_controller_test.go

https://coreos.slack.com/archives/CHK0J6HT6/p1620732956300200

chore: rename controller types to Reconciler

---

go.mod
go.sum

update common to make sure that everything works fine - related PR: https://github.com/codeready-toolchain/member-operator/pull/249

chore: update common

---

make/manifests.mk

because I'm stupid :man_facepalming:

fix: bring back PATH_TO_OLM_GENERATE_FILE variable

---

deploy/crds/toolchain.dev.openshift.com_toolchainstatuses.yaml
deploy/crds/toolchain.dev.openshift.com_usersignups.yaml
deploy/olm-catalog/toolchain-host-operator/manifests/toolchain.dev.openshift.com_toolchainstatuses.yaml
deploy/olm-catalog/toolchain-host-operator/manifests/toolchain.dev.openshift.com_usersignups.yaml
go.mod
go.sum
hack/deploy_csv.yaml

Related API PR: https://github.com/codeready-toolchain/api/pull/240
Fixes https://issues.redhat.com/browse/CRT-1114

Regenerated due to api changes

---

cmd/manager/main.go

modify scheme api initialization so it's closer to what is generated by operator-sdk

chore: modify scheme api initialization

---

controllers/usersignup/usersignup_controller_test.go
controllers/usersignupcleanup/usersignup_cleanup_controller.go
controllers/usersignupcleanup/usersignup_cleanup_controller_test.go
test/usersignup.go

paired with: https://github.com/codeready-toolchain/toolchain-e2e/pull/319

fix: don't delete reactivated UserSignups

---

deploy/crds/toolchain.dev.openshift.com_toolchainconfigs.yaml
deploy/olm-catalog/toolchain-host-operator/manifests/toolchain.dev.openshift.com_toolchainconfigs.yaml
hack/deploy_csv.yaml

Related PR: https://github.com/codeready-toolchain/api/pull/243

Generated files for toolchainconfig api changes

---

controllers/deactivation/deactivation_controller_test.go
controllers/toolchainconfig/cache_test.go
controllers/toolchainconfig/configuration_test.go
controllers/toolchainconfig/toolchainconfig_controller_test.go
controllers/usersignup/approval_test.go
controllers/usersignup/predicate_test.go
controllers/usersignup/usersignup_controller_test.go
go.mod
go.sum
test/config.go

chore: update to latest toolchain-common

---

deploy/templates/notificationtemplates/userdeactivated/notification.html
deploy/templates/notificationtemplates/userdeactivated/subject.txt
deploy/templates/notificationtemplates/userdeactivating/notification.html
deploy/templates/notificationtemplates/userprovisioned/notification.html
deploy/templates/notificationtemplates/userprovisioned/subject.txt
pkg/templates/notificationtemplates/notification_generator_test.go

See https://issues.redhat.com/browse/CRT-1156

Remove Beta from emails

---

deploy/crds/toolchain.dev.openshift.com_toolchainconfigs.yaml
deploy/olm-catalog/toolchain-host-operator/manifests/toolchain.dev.openshift.com_toolchainconfigs.yaml
go.mod
go.sum
hack/deploy_csv.yaml

Generated files from codeready-toolchain/api#246

Updated toolchainconfig

---

deploy/crds/toolchain.dev.openshift.com_hostoperatorconfigs.yaml
deploy/crds/toolchain.dev.openshift.com_toolchainconfigs.yaml
deploy/olm-catalog/toolchain-host-operator/manifests/toolchain.dev.openshift.com_hostoperatorconfigs.yaml
deploy/olm-catalog/toolchain-host-operator/manifests/toolchain.dev.openshift.com_toolchainconfigs.yaml
hack/deploy_csv.yaml

Generated API files related to PR: https://github.com/codeready-toolchain/api/pull/248

Generated API files

---

go.mod
go.sum

https://github.com/codeready-toolchain/toolchain-common/pull/195

fix: reuse cached client

---

config/crd/bases/toolchain.dev.openshift.com_hostoperatorconfigs.yaml
config/crd/bases/toolchain.dev.openshift.com_toolchainconfigs.yaml

Generated files after adding registration service configuration APIs.
Related PR: https://github.com/codeready-toolchain/api/pull/252

Add reg service config to toolchainconfig

---

deploy/templates/nstemplatetiers/baseextendedidling/cluster.yaml
deploy/templates/nstemplatetiers/baseextendedidling/ns_dev.yaml
deploy/templates/nstemplatetiers/baseextendedidling/ns_stage.yaml
deploy/templates/nstemplatetiers/baseextendedidling/tier.yaml
pkg/templates/nstemplatetiers/nstemplatetier_generator_whitebox_test.go

Creates a new tier that's the same as the base tier but extends the idling period to 24 hours.

Create tier for idling extended to 24 hours

---

controllers/masteruserrecord/masteruserrecord_controller.go
controllers/masteruserrecord/masteruserrecord_controller_test.go

paired with https://github.com/codeready-toolchain/toolchain-e2e/pull/358

don't decrement when UserAccount is accidentally deleted

---

config/crd/bases/toolchain.dev.openshift.com_hostoperatorconfigs.yaml
config/crd/bases/toolchain.dev.openshift.com_toolchainconfigs.yaml

Generated files for updated API.
Related PR: https://github.com/codeready-toolchain/api/pull/253

Add replicas to reg service config

---

.github/workflows/publish-operators-for-e2e-tests.yml

The same change as: https://github.com/codeready-toolchain/member-operator/pull/289

feat: trigger GH Actions workflow for retest comment

---

controllers/usersignup/usersignup_controller.go

Fixes https://issues.redhat.com/projects/CRT/issues/CRT-1218

Use UserSignup.Annotations instead of .Labels to get user's email address

---

controllers/notification/notification_controller.go

to revert https://github.com/codeready-toolchain/host-operator/commit/485d122dfd04cae158f8d0d9f49633777b1c3f71

chore: remove the temporal fix for broken Notifications

---

controllers/masteruserrecord/sync.go
controllers/masteruserrecord/sync_test.go
controllers/toolchainconfig/configuration.go
controllers/toolchainconfig/configuration_test.go
controllers/usersignup/usersignup_controller.go
controllers/usersignup/usersignup_controller_test.go
test/notification/assertion.go

Fixes an issue where the registration service URL is not being set in the notification context.

Add reg service URL to notification context

---

controllers/usersignup/usersignup_controller.go
controllers/usersignup/usersignup_controller_test.go

This PR prevents duplicate deactivating and deactivated notifications from being created if they have already been previously created in cases where the UserSignup status failed to update.
Fixes https://issues.redhat.com/browse/CRT-1243

Don't create duplicate notifications when UserSignup status update fails.

---

deploy/templates/nstemplatetiers/advanced/based_on_tier.yaml
deploy/templates/nstemplatetiers/basedeactivationdisabled/based_on_tier.yaml
deploy/templates/nstemplatetiers/baseextended/based_on_tier.yaml
deploy/templates/nstemplatetiers/baseextendedidling/based_on_tier.yaml
deploy/templates/nstemplatetiers/baselarge/based_on_tier.yaml
pkg/templates/nstemplatetiers/nstemplatetier_generator.go
pkg/templates/nstemplatetiers/nstemplatetier_generator_whitebox_test.go
test/templates/nstemplatetiers/advanced/based_on_tier.yaml

now using something like:
```
from: base
parameters:
- name: ...
value: ...
```
fixes https://issues.redhat.com/browse/CRT-1264

refactor: simplify the tier templates

---

config/crd/bases/toolchain.dev.openshift.com_masteruserrecords.yaml
config/crd/bases/toolchain.dev.openshift.com_usersignups.yaml

Related API PR: https://github.com/codeready-toolchain/api/pull/258
Fixes https://issues.redhat.com/browse/CRT-1254

API Regeneration

---

deploy/templates/nstemplatetiers/hackathon/based_on_tier.yaml
pkg/templates/nstemplatetiers/nstemplatetier_generator_whitebox_test.go

Related issue: https://issues.redhat.com/browse/CRT-1258
Related PR: https://github.com/codeready-toolchain/toolchain-e2e/pull/390

Add hackathon tier

---

deploy/templates/nstemplatetiers/baselarge/based_on_tier.yaml
pkg/templates/nstemplatetiers/nstemplatetier_generator_whitebox_test.go

Related PR: https://github.com/codeready-toolchain/toolchain-e2e/pull/391

Extend baselarge tier to 90 days deactivation period

---

pkg/apis/apis.go

Update to k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1

---

config/crd/bases/toolchain.dev.openshift.com_toolchainevents.yaml

Regenerated due to api changes.
https://issues.redhat.com/browse/CRT-1299

Added ToolchainEvent CRD to API

---

controllers/usersignup/masteruserrecord.go
controllers/usersignup/masteruserrecord_test.go
controllers/usersignup/usersignup_controller_test.go

Related to https://issues.redhat.com/browse/CRT-1075

chore: remove outdated code

---

config/crd/bases/toolchain.dev.openshift.com_toolchainconfigs.yaml

Related PR: https://github.com/codeready-toolchain/api/pull/268

Generated files for DefaultSpaceTier configuration

---

PROJECT
config/crd/bases/toolchain.dev.openshift.com_changetierrequests.yaml
config/crd/bases/toolchain.dev.openshift.com_spaces.yaml
config/crd/kustomization.yaml
config/manifests/bases/host-operator.clusterserviceversion.yaml
go.mod
go.sum

see also https://github.com/codeready-toolchain/api/pull/267
Fixes https://issues.redhat.com/browse/CRT-1309

feat: Space CRD

---

config/crd/bases/toolchain.dev.openshift.com_spaces.yaml
go.mod
go.sum

Updates to include the new `Space.Status.TargetCluster` field while the SpaceController is still under review (#548)

feat: Space.Status.TargetCluster field

---

controllers/changetierrequest/changetierrequest_controller.go
controllers/changetierrequest/changetierrequest_controller_test.go
controllers/templateupdaterequest/templateupdaterequest_controller_test.go
go.mod
go.sum

Fixes https://issues.redhat.com/browse/CRT-1322
See also https://github.com/codeready-toolchain/toolchain-common/pull/218

feat: ChangeTierRequest updates MasterUserRecord.Spec.TierName

---

config/crd/bases/toolchain.dev.openshift.com_toolchainstatuses.yaml

generated from https://github.com/codeready-toolchain/api/pull/274

feat: add HostRoutes into ToolchainStatus CRD

---

.github/workflows/ci-build.yml
make/lint.mk

chore: update GolangCI action and makefile goal

---

config/crd/bases/toolchain.dev.openshift.com_templateupdaterequests.yaml

generated from https://github.com/codeready-toolchain/api/pull/276

Update TUR crd

---

deploy/templates/nstemplatetiers/advanced/based_on_tier.yaml

e2e test: https://github.com/codeready-toolchain/toolchain-e2e/pull/423

Increase memory limit for advanced tier to 16Gi

---

controllers/toolchainconfig/configuration.go
controllers/toolchainconfig/configuration_test.go
go.mod
go.sum

Related issue: https://issues.redhat.com/browse/CRT-1319
Related PR: https://github.com/codeready-toolchain/toolchain-common/pull/222

Default space tier config

---

controllers/changetierrequest/changetierrequest_controller.go
controllers/changetierrequest/changetierrequest_controller_test.go
go.mod
go.sum

see https://github.com/codeready-toolchain/api/pull/282

chore: fix typo in const name

---

config/crd/bases/toolchain.dev.openshift.com_masteruserrecords.yaml
go.mod
go.sum

see https://github.com/codeready-toolchain/api/pull/285
Fixes https://issues.redhat.com/browse/CRT-1336

feat: SpaceRoles in NSTemplateSet

---

controllers/changetierrequest/changetierrequest_controller.go
controllers/changetierrequest/changetierrequest_controller_test.go

When promoting a user to a new tier I saw that there was a race-condition:
1. `ChangeTierRequest` was created
2. The `ChangeTierRequest` controller removed `Deactivating` state from `UserSignup`
3. The `Deactivation` controller was triggered based on the change in the spec
4. The `Deactivation` controller checked the tier of the MUR - which was still the old one - and added the `deactivating` state back to `UserSignup`
5. The `ChangeTierRequest` controller updated the `TierName` in MUR but it was too late
So this PR moves the logic that updates `UserSignup` resources after changing TierName in MUR 
There won't be any e2e test since it's impossible to write a reliable one - it's race-condition issue. But I added unit-test for it.

fix: remove deactivating state after promoting to a new tier

---

PROJECT
config/crd/bases/toolchain.dev.openshift.com_spacebindings.yaml
config/crd/kustomization.yaml

Adds SpaceBinding CRD generated from https://github.com/codeready-toolchain/api/pull/287

feat: introduce SpaceBinding CRD

---

deploy/templates/nstemplatetiers/appstudio/cluster.yaml
deploy/templates/nstemplatetiers/base/cluster.yaml
deploy/templates/nstemplatetiers/test/cluster.yaml

Related PR: https://github.com/codeready-toolchain/toolchain-e2e/pull/451

Update services quota to 30

---

main.go

https://github.com/codeready-toolchain/host-operator/pull/575#discussion_r789663062

fix: add missing os.Exit(1)

---

.github/workflows/ci-build.yml
.golangci.yml
controllers/deactivation/deactivation_controller_test.go
controllers/notification/notification_controller_test.go
controllers/nstemplatetier/nstemplatetier_controller.go
controllers/nstemplatetier/util/hash.go
controllers/templateupdaterequest/templateupdaterequest_controller.go
controllers/toolchainstatus/toolchainstatus_controller.go
controllers/usersignup/predicate.go
controllers/usersignup/usersignup_controller.go
controllers/usersignup/usersignup_controller_test.go
controllers/usersignupcleanup/usersignup_cleanup_controller_test.go
pkg/counter/cache.go
test/usersignup.go
version/version.go

disable 'golint', use 'revive' instead

chore: update linter config

---

deploy/templates/nstemplatetiers/appstudio/ns_appstudio.yaml

e2e tests: https://github.com/codeready-toolchain/toolchain-e2e/pull/463

Add ComponentDetectionQuery to appstudio user SA role

---

config/crd/bases/toolchain.dev.openshift.com_toolchainstatuses.yaml
controllers/toolchainstatus/toolchainstatus_controller.go
controllers/toolchainstatus/toolchainstatus_controller_test.go
go.mod
go.sum
test/toolchainstatus.go

refactor: rename Member.APIEndpoint field

---

deploy/templates/nstemplatetiers/appstudio/ns_appstudio.yaml

needed by HAC to manage SPI resources
paired with: https://github.com/codeready-toolchain/toolchain-e2e/pull/468

feat: add SPI resources to appstudio-user-actions role

---

pkg/capacity/manager.go
pkg/capacity/manager_test.go

https://github.com/codeready-toolchain/host-operator/pull/592#pullrequestreview-875208283

feat: privision in batches of 50

---

config/crd/bases/toolchain.dev.openshift.com_nstemplatetiers.yaml

Fixes https://issues.redhat.com/browse/CRT-1345
See also: https://github.com/codeready-toolchain/api/pull/292

feat: SpaceRoles in NSTemplateTier

---

deploy/templates/nstemplatetiers/appstudio/ns_appstudio.yaml

e2e tests: https://github.com/codeready-toolchain/toolchain-e2e/pull/482

Add delete for spiaccesstokenbindings in appstudio tier

---

controllers/spacecleanup/space_cleanup_controller.go
controllers/spacecleanup/space_cleanup_controller_test.go
main.go
test/space/space.go
test/space/space_assertions.go

add SpaceCleanup controller that deletes every space that:
* doesn't have any SpaceBinding
* it was created more than 30 seconds ago
paired with https://github.com/codeready-toolchain/toolchain-e2e/pull/479

feat: add SpaceCleanup controller

---

controllers/spacecleanup/space_cleanup_controller.go
controllers/spacecleanup/space_cleanup_controller_test.go

Reverts codeready-toolchain/host-operator#608

Revert "fix: prolong cleanup timeout"

---

PROJECT
config/crd/bases/toolchain.dev.openshift.com_socialevents.yaml
config/crd/kustomization.yaml
config/manifests/bases/host-operator.clusterserviceversion.yaml
go.mod
go.sum

see https://github.com/codeready-toolchain/api/pull/298

refactor: rename 'ToolchainEvent' type to 'SocialEvent'

---

deploy/templates/nstemplatetiers/appstudio/ns_appstudio.yaml

Duplicates https://github.com/codeready-toolchain/host-operator/pull/626
Paired with https://github.com/codeready-toolchain/toolchain-e2e/pull/542

Update the appstudio user actions role with the new requirements

---

config/crd/bases/toolchain.dev.openshift.com_usertiers.yaml

Generated files for the new UserTier CRD.
See https://github.com/codeready-toolchain/api/pull/302

UserTier CRD

---

config/crd/bases/toolchain.dev.openshift.com_toolchainconfigs.yaml

Related PR: https://github.com/codeready-toolchain/api/pull/308

Generated files that include default user tier

---

deploy/registration-service/registration-service.yaml

feat: grant permission to Registration Service to get SocialEvents

---

deploy/templates/nstemplatetiers/appstudio/cluster.yaml

e2e tests: https://github.com/codeready-toolchain/toolchain-e2e/pull/562

Disable Idler for appstudio tier

---

config/crd/bases/toolchain.dev.openshift.com_toolchainconfigs.yaml

Generated files for https://github.com/codeready-toolchain/api/pull/314

Generated files for MemberOperatorConfig update

---

deploy/templates/nstemplatetiers/appstudio/spacerole_admin.yaml

This PR is paired with https://github.com/codeready-toolchain/toolchain-e2e/pull/578

Allow appstudio users to create Environment APIs

---

config/crd/bases/toolchain.dev.openshift.com_socialevents.yaml
config/crd/bases/toolchain.dev.openshift.com_toolchainconfigs.yaml
go.mod
go.sum

for `spec.MaxAttendees` and `status.activationCount`
gives:
```
$ oc get socialevents
NAME    STARTTIME              ENDTIME                DESCRIPTION       MAXATTENDEES   CURRENTATTENDEES
8gwgc   2022-07-05T22:00:00Z   2022-07-06T21:59:59Z   Summer Workshop   10             1
gwnxb   2022-07-05T22:00:00Z   2022-07-06T21:59:59Z   Summer Workshop   10             0
```
see https://github.com/codeready-toolchain/api/pull/317

add print columns on SocialEvent

---

config/crd/bases/toolchain.dev.openshift.com_nstemplatetiers.yaml
config/crd/bases/toolchain.dev.openshift.com_toolchainconfigs.yaml
go.mod
go.sum
test/nstemplatetier/nstemplatetier.go

Related PR: https://github.com/codeready-toolchain/api/pull/318

Remove deactivation timeout days

---

deploy/templates/nstemplatetiers/appstudio/ns_appstudio.yaml

Paired with https://github.com/codeready-toolchain/toolchain-e2e/pull/582

Increase ephemeral storage for HACBS

---

deploy/templates/nstemplatetiers/base/cluster.yaml

This reverts commit 127897eff1ff1a3a2937e040d67d3caaaef6d752.

Revert "feat: add optional DBaaSTenant resource (#607)"

---

deploy/templates/nstemplatetiers/base1ns/cluster.yaml

Related to https://github.com/codeready-toolchain/host-operator/pull/673

Stop creating DBaaSTenant resources

---

deploy/templates/nstemplatetiers/appstudio/spacerole_admin.yaml

Context https://issues.redhat.com/browse/SVPI-187

feat: SPI Grant an ability for the users to revoke/adjust granted authorization

---

controllers/toolchainconfig/toolchainconfig_controller.go
controllers/toolchainstatus/creation.go
controllers/toolchainstatus/creation_test.go
deploy/resources.go
go.mod
go.sum
main.go
pkg/templates/nstemplatetiers/nstemplatetier_generator.go
pkg/templates/usertiers/usertier_generator.go

refactor: no need for runtime.Scheme in ApplyClient

---

config/crd/bases/toolchain.dev.openshift.com_toolchainconfigs.yaml

API changes in relation to https://issues.redhat.com/browse/CRT-1588
API PR: https://github.com/codeready-toolchain/api/pull/321

Regenerated from API changes

---

config/crd/bases/toolchain.dev.openshift.com_toolchainconfigs.yaml

Regenerated from API changes
API PR: https://github.com/codeready-toolchain/api/pull/322

Regenerated from API

---

deploy/templates/nstemplatetiers/base1ns/cluster.yaml
deploy/templates/nstemplatetiers/base1ns/ns_dev.yaml
deploy/templates/nstemplatetiers/base1ns/spacerole_admin.yaml

Paired with https://github.com/codeready-toolchain/toolchain-e2e/pull/612

Update base1ns with new resource quotas from test tier.

---

deploy/templates/nstemplatetiers/appstudio/spacerole_admin.yaml

https://coreos.slack.com/archives/C02CTEB3MMF/p1669107802317799
paired with https://github.com/codeready-toolchain/toolchain-e2e/pull/624

drop application prefix from AppStudio CRDs

---

deploy/templates/nstemplatetiers/appstudio/spacerole_admin.yaml
deploy/templates/nstemplatetiers/appstudio/spacerole_viewer.yaml

See https://issues.redhat.com/browse/CRT-1461
Paired with https://github.com/codeready-toolchain/toolchain-e2e/pull/625

Add user rolebindings for proxy updates

---

.github/workflows/ci-build.yml

run CycloneDX action to generate SBOM

---

.gitignore

chore: remove 'database'

---

go.mod
go.sum

This PR is for testing new toolchaincluster controller changes that adds home label on toolchaincluster of type member.
See Jira: https://issues.redhat.com/browse/ASC-245
Related PRs:
- toolchain-common: https://github.com/codeready-toolchain/toolchain-common/pull/284
Paired with:
- toolchain-e2e: https://github.com/codeready-toolchain/toolchain-e2e/pull/645

Roles as labels at ToolchainCluster CRD

---

config/crd/bases/toolchain.dev.openshift.com_spaces.yaml
go.mod
go.sum

This PR adds `parentSpace` field to the `Space` CRD, covers the first acceptance criteria from https://issues.redhat.com/browse/ASC-247.
Related PR's:
- host-operator: https://github.com/codeready-toolchain/api/pull/335

add parentSpace field in Space CRD, minor comment fix

---

deploy/templates/nstemplatetiers/appstudio/spacerole_admin.yaml

- SPI Grant an ability for the users to operate with spifilecontentrequest CR

feat: SPI Grant an ability for the users to operate with spifilecontentrequest CR

---

deploy/templates/nstemplatetiers/appstudio/ns_appstudio.yaml

requires https://github.com/codeready-toolchain/member-operator/pull/404 
e2e tests: https://github.com/codeready-toolchain/toolchain-e2e/pull/653

Add Dev Environment CR to appstudio tier template

---

deploy/templates/nstemplatetiers/appstudio/cluster.yaml
deploy/templates/nstemplatetiers/appstudio/ns_appstudio.yaml

Signed-off-by: Romain Arnaud <rarnaud@redhat.com>
C.f. https://github.com/codeready-toolchain/toolchain-e2e/pull/658

Increase pod quota for AppStudio to 150

---

deploy/templates/nstemplatetiers/appstudio/ns_tenant.yaml
deploy/templates/nstemplatetiers/appstudio/tier.yaml
pkg/templates/nstemplatetiers/nstemplatetier_generator_test.go
pkg/templates/nstemplatetiers/nstemplatetier_generator_whitebox_test.go
test/templates/nstemplatetiers/appstudio/ns_tenant.yaml
test/templates/nstemplatetiers/appstudio/tier.yaml
test/templates/nstemplatetiers/metadata.yaml

paired PR: https://github.com/codeready-toolchain/toolchain-e2e/pull/659

stonesoup: add -tenant suffix to appstudio tier

---

deploy/registration-service/registration-service.yaml

For https://github.com/codeready-toolchain/registration-service/pull/301

Add spacebindings to reg service permissions

---

controllers/usersignup/usersignup_controller.go

minor refactoring to improve readability of the code

refactor logic to check space creation

---

config/crd/bases/toolchain.dev.openshift.com_proxyplugins.yaml
config/crd/bases/toolchain.dev.openshift.com_toolchainconfigs.yaml
config/crd/kustomization.yaml

reverts accidentally revert removed changes in https://github.com/codeready-toolchain/host-operator/commit/acd39aa79678397d80e0d1006475b4206f50b07d and adds ProxyPlugins to the list in kustomize

fix: revert removed CRD updates & add ProxyPlugins to the list

---

deploy/templates/nstemplatetiers/appstudio/cluster.yaml
deploy/templates/nstemplatetiers/base/cluster.yaml
deploy/templates/nstemplatetiers/base1ns/cluster.yaml
deploy/templates/nstemplatetiers/test/cluster.yaml

Related issue - https://issues.redhat.com/browse/CRW-4124
Related e2e tests PR - https://github.com/codeready-toolchain/toolchain-e2e/pull/683

chore: increase quota for ingresses / routes to 30

---

deploy/templates/nstemplatetiers/appstudio/spacerole_admin.yaml

* remove deploymenttargetclasses since it is cluster-scope
* update write permission to deploymenttarget and deploymenttargetclaims
Corresponding test repo PR: https://github.com/codeready-toolchain/toolchain-e2e/pull/686

update rbac for DT/DTC/DTCLS

---

.github/workflows/ci-build.yml

chore: upgrade GolangCI Lint to v1.52.0

---

controllers/usersignup/usersignup_controller.go
pkg/segment/segment.go
test/segment/assertions.go

As requested by Jake Lucky and Brad.

Add userID and accountID to signup event in segment

---

pkg/segment/segment.go
test/segment/assertions.go

Rename account_id to groupID for segment

---

deploy/templates/nstemplatetiers/appstudio/ns_tenant.yaml

* Resource quota to prevent unlimited number of CRs in namespace
* Initial change with high limits, will be adjusted in future
Made as a follow-on to #783

feat(STONEINTG-343): set ResourceQuota for Appstudio CRDs

---

deploy/templates/notificationtemplates/appstudio/userdeactivated/notification.html
deploy/templates/notificationtemplates/appstudio/userdeactivated/subject.txt
deploy/templates/notificationtemplates/appstudio/userdeactivating/notification.html
deploy/templates/notificationtemplates/appstudio/userdeactivating/subject.txt
deploy/templates/notificationtemplates/appstudio/userprovisioned/notification.html
pkg/templates/notificationtemplates/notification_generator_test.go

https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1684319994963529?
thread_ts=1684252874.848339&cid=C04PZ7H0VA8
https://issues.redhat.com/browse/RHTAPBUGS-295
https://issues.redhat.com/browse/RHTAPBUGS-299

appstudio: add RHTAP to emails

---

deploy/templates/nstemplatetiers/base1ns/ns_dev.yaml

e2e tests: https://github.com/codeready-toolchain/toolchain-e2e/pull/736

Change memory limit for build workloads

---

deploy/templates/nstemplatetiers/appstudio/spacerole_admin.yaml

The old service account has been phased out.
Impacts 
https://issues.redhat.com/browse/RHTAPBUGS-338
e2e tests: https://github.com/codeready-toolchain/toolchain-e2e/pull/741

Move to the new name of the tekton sa

---

deploy/templates/nstemplatetiers/appstudio/spacerole_admin.yaml
deploy/templates/nstemplatetiers/appstudio/spacerole_contributor.yaml
deploy/templates/nstemplatetiers/appstudio/spacerole_maintainer.yaml

We're planning to enable the remote secrets in rhtap staging in the near future so we want the admin users to be able to play with them. I hope this is enough to do so.
e2e-tests: https://github.com/codeready-toolchain/toolchain-e2e/pull/746

Enable admins to work with the remote secrets.

---

deploy/templates/nstemplatetiers/appstudio/spacerole_admin.yaml
deploy/templates/nstemplatetiers/appstudio/spacerole_contributor.yaml
deploy/templates/nstemplatetiers/appstudio/spacerole_maintainer.yaml

BuildPipelineSelector allows modify selection of pipelineRun for build.
E2E test -> https://github.com/codeready-toolchain/toolchain-e2e/pull/751

Appstudio: add access to buildpipelineselectors

---

go.mod
go.sum
test/spacerequest/spacerequest.go

keeping uuid library consistent

use gofrs/uuid instead of google/uuid

---

deploy/templates/nstemplatetiers/appstudio-env/ns_env.yaml

E2E test -> https://github.com/codeready-toolchain/toolchain-e2e/pull/754

feat(SANDBOX-249): add a new role and rolebinding to appstudio-env tier

---

config/crd/bases/toolchain.dev.openshift.com_toolchainconfigs.yaml

Related API changes: https://github.com/codeready-toolchain/api/pull/374

generated from API

---

deploy/templates/nstemplatetiers/appstudio/ns_tenant.yaml

to avoid creation of a high number of SpaceRequests
paired PR https://github.com/codeready-toolchain/toolchain-e2e/pull/786

appstudio: limit SpaceRequest and DT(C/S) count to 32

---

config/crd/bases/toolchain.dev.openshift.com_masteruserrecords.yaml

Regenerated from API
PR: https://github.com/codeready-toolchain/api/pull/376

Added email to propagated claims

---

controllers/masteruserrecord/masteruserrecord_controller.go
controllers/masteruserrecord/masteruserrecord_controller_test.go
go.mod
go.sum

Fixes https://issues.redhat.com/browse/SANDBOX-396

Propagate PropagatedClaims from MasterUserRecord to UserAccount

---

deploy/templates/nstemplatetiers/base/ns_dev.yaml
deploy/templates/nstemplatetiers/base/ns_stage.yaml
deploy/templates/nstemplatetiers/base1ns/ns_dev.yaml

Add network policy required for CNV operator to work with Dev Sandbox user namespaces.
e2e tests: https://github.com/codeready-toolchain/toolchain-e2e/pull/804

Network policy for cnv

---

controllers/toolchainconfig/toolchainconfig_controller.go
controllers/toolchainconfig/toolchainconfig_controller_test.go

fix: forward context in ToolchainConfig controller

---

controllers/spacerequest/spacerequest_controller.go

fix: forward context in SpaceRequest controller

---

controllers/space/space_controller.go
go.mod
go.sum

Refactor space controller to use common space binding lister functionality from toolchain-common: https://github.com/codeready-toolchain/toolchain-common/tree/master/pkg/spacebinding
Jira: https://issues.redhat.com/browse/ASC-436

fix: replace listpacebindings function with common util 

---

controllers/space/space_controller.go

fix: forward context in Space reconciler

---

controllers/spacecleanup/space_cleanup_controller.go

fix: forward context in SpaceCleanup controller

---

controllers/spacecompletion/space_completion_controller.go

fix: forward context in SpaceCompletion reconciler

---

controllers/spacebindingrequest/spacebindingrequest_controller.go

fix: forward context in SpaceBindingRequest reconciler

---

controllers/spacebindingcleanup/spacebinding_cleanup_controller.go

fix: forward context in SpaceBindingCleanup reconciler

---

deploy/templates/nstemplatetiers/appstudio/cluster.yaml
deploy/templates/nstemplatetiers/appstudio/ns_tenant.yaml

Just for builds.
Requested by Brain.
Paired with https://github.com/codeready-toolchain/toolchain-e2e/pull/825

Increase resource quota for appstudilo tier

---

deploy/templates/nstemplatetiers/base/ns_dev.yaml
deploy/templates/nstemplatetiers/base/ns_stage.yaml
deploy/templates/nstemplatetiers/base1ns/ns_dev.yaml

Adds a selector to enable ingress from openshift-cnv.

Update CNV network policy

---

deploy/templates/nstemplatetiers/advanced/based_on_tier.yaml
deploy/templates/nstemplatetiers/base/cluster.yaml
deploy/templates/nstemplatetiers/base/ns_dev.yaml
deploy/templates/nstemplatetiers/base/ns_stage.yaml
deploy/templates/nstemplatetiers/baselarge/based_on_tier.yaml

Paired with https://github.com/codeready-toolchain/toolchain-e2e/pull/828

Align resource quota in base tier with base1ns

---

deploy/templates/nstemplatetiers/appstudio/cluster.yaml
deploy/templates/nstemplatetiers/appstudiolarge/based_on_tier.yaml
pkg/templates/nstemplatetiers/nstemplatetier_generator_whitebox_test.go

See https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1698769593328539
Paired with https://github.com/codeready-toolchain/toolchain-e2e/pull/832

Introduce appstudio large tier

---

controllers/nstemplatetier/nstemplatetier_controller.go

fix: forward context in NSTemplateTier reconciler

---

controllers/deactivation/deactivation_controller.go

fix: forward context in Deactivation reconciler

---

controllers/masteruserrecord/masteruserrecord_controller.go
controllers/masteruserrecord/masteruserrecord_controller_test.go
controllers/masteruserrecord/sync.go
controllers/masteruserrecord/sync_test.go

fix: forward context in MasterUserRecord reconciler

---

controllers/toolchainconfig/sync.go
controllers/toolchainconfig/sync_test.go
controllers/toolchainconfig/toolchainconfig_controller.go

fix: forward context in ToolchainConfig reconciler

---

controllers/notification/notification_controller.go

fix: forward context in Notification reconciler

---

main.go
pkg/templates/nstemplatetiers/nstemplatetier_generator.go
pkg/templates/nstemplatetiers/nstemplatetier_generator_test.go

fix: forward context in nstemplatetier generator

---

controllers/toolchainstatus/toolchainstatus_controller.go
pkg/counter/cache.go
pkg/counter/cache_test.go
test/counter.go

fix: forward context in pkg/counter

---

controllers/spacecompletion/space_completion_controller.go
controllers/usersignup/approval.go
controllers/usersignup/approval_test.go
controllers/usersignup/usersignup_controller.go
pkg/capacity/manager.go
pkg/capacity/manager_test.go

fix: forward context in pkg/capacity

---

config/crd/bases/toolchain.dev.openshift.com_toolchainconfigs.yaml

Generated api update for https://github.com/codeready-toolchain/api/pull/385

Generated files

---

go.mod
go.sum

Related to https://github.com/codeready-toolchain/api/pull/385

Update api dependency

---

controllers/spacebindingcleanup/spacebinding_cleanup_controller.go
controllers/spacebindingrequest/spacebindingrequest_controller.go
controllers/spacerequest/spacerequest_controller.go
pkg/cluster/cluster.go

fix: forward context in pkg/cluster

---

controllers/masteruserrecord/masteruserrecord_controller_test.go
controllers/masteruserrecord/sync_test.go
controllers/space/space_controller.go
controllers/toolchainconfig/toolchainconfig_controller_test.go

fix incorrect usage of log.IntoContext

---

controllers/usersignup/usersignup_controller.go
controllers/usersignup/usersignup_controller_test.go

Fixes https://issues.redhat.com/browse/SANDBOX-468
e2e test PR: https://github.com/codeready-toolchain/toolchain-e2e/pull/839

Removed migration code

---

controllers/spacerequest/spacerequest_controller.go
controllers/spacerequest/spacerequest_controller_test.go
pkg/space/space.go
pkg/space/space_test.go

This should prevent subspace names from growing longer from the level of subspace nesting.

impl new subspace naming strategy

---

controllers/toolchainconfig/toolchainconfig_controller.go
controllers/toolchainstatus/creation.go
controllers/toolchainstatus/creation_test.go
go.mod
go.sum
main.go
pkg/templates/nstemplatetiers/nstemplatetier_generator.go
pkg/templates/usertiers/usertier_generator.go
pkg/templates/usertiers/usertier_generator_test.go

Requiring [toolchain-common#340](https://github.com/codeready-toolchain/toolchain-common/pull/340)

fix: forward context in toolchain-common pkg/client

---

deploy/templates/nstemplatetiers/appstudio/ns_tenant.yaml

See https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1700239362389419
Paired with: https://github.com/codeready-toolchain/toolchain-e2e/pull/853

Increase storage request limit for appstudo

---

config/crd/bases/toolchain.dev.openshift.com_masteruserrecords.yaml
config/crd/bases/toolchain.dev.openshift.com_toolchainconfigs.yaml
controllers/masteruserrecord/sync.go
controllers/masteruserrecord/sync_test.go
go.mod
go.sum

This is to Drop unused parameters from the embedded MUR.Status.UserAccounts.Clusters type
Related PRs
API - https://github.com/codeready-toolchain/api/pull/387
Toolchain e2e - https://github.com/codeready-toolchain/toolchain-e2e/pull/855

Dropping the unused parameters

---

deploy/templates/notificationtemplates/sandbox/userdeactivated/notification.html
deploy/templates/notificationtemplates/sandbox/userdeactivating/notification.html
deploy/templates/notificationtemplates/sandbox/userprovisioned/notification.html

since the current invite link was expired

update slack invite link

---

config/crd/bases/toolchain.dev.openshift.com_masteruserrecords.yaml

https://github.com/codeready-toolchain/api/pull/394

print target cluster from status

---

config/crd/bases/toolchain.dev.openshift.com_toolchainconfigs.yaml

Generated for https://github.com/codeready-toolchain/api/pull/392

SSO Configuration for web login

---

config/manager/manager.yaml

upgrade ose-kube-rbac-proxy to v4.14

---

.github/workflows/publish-operators-for-e2e-tests.yml

https://github.com/codeready-toolchain/registration-service/pull/394

 check substrings of GH comments to run PR CD workflow

---

controllers/toolchainstatus/toolchainstatus_controller.go
go.mod
go.sum

related to [#352](https://github.com/codeready-toolchain/toolchain-common/pull/352)

fix: forward context in common's status pkg

---

config/crd/bases/toolchain.dev.openshift.com_usersignups.yaml

See https://github.com/codeready-toolchain/api/pull/399

Fix usersignup email printcolumn

---

controllers/spaceprovisionerconfig/spaceprovisionerconfig_controller.go

add some logs to SPC controller

---

controllers/usersignupcleanup/usersignup_cleanup_controller.go
controllers/usersignupcleanup/usersignup_cleanup_controller_test.go

In order to keep our total UserSignups under control, this PR updates the UserCleanupController so that it will delete users that haven't been activated in the last 2 years, that only have one total activation and that aren't banned.
Fixes: https://issues.redhat.com/browse/SANDBOX-547
Note: the 2 years must be configured in the host operator configuration.

Update User Cleanup controller to be useful

---

.golangci.yml
controllers/deactivation/deactivation_controller_test.go
controllers/deactivation/mapper_test.go
controllers/masteruserrecord/mapper_test.go
controllers/masteruserrecord/masteruserrecord_controller_test.go
controllers/masteruserrecord/sync_test.go
controllers/notification/notification_controller_test.go
controllers/nstemplatetier/nstemplatetier_controller_test.go
controllers/socialevent/socialevent_controller_test.go
controllers/spacebindingcleanup/spacebinding_cleanup_controller_test.go
controllers/spacerequest/spacerequest_controller_test.go
controllers/toolchainconfig/sync_test.go
controllers/toolchainconfig/toolchainconfig_controller_test.go
controllers/toolchainstatus/toolchainstatus_controller_test.go
controllers/usersignup/status_updater_test.go
controllers/usersignup/usersignup_controller_test.go
controllers/usersignupcleanup/usersignup_cleanup_controller_test.go
pkg/counter/cache_test.go
pkg/pending/cache_test.go
test/metric.go
test/notification/assertion.go

address linter issues

---

pkg/templates/nstemplatetiers/nstemplatetier_generator_test.go

https://github.com/codeready-toolchain/host-operator/actions/runs/8799872789/job/24149818181?pr=1000#step:5:438

fix flakiness in tier generator test

---

deploy/templates/nstemplatetiers/base/ns_dev.yaml
deploy/templates/nstemplatetiers/base/ns_stage.yaml
deploy/templates/nstemplatetiers/base1ns/ns_dev.yaml

e2e tests: https://github.com/codeready-toolchain/toolchain-e2e/pull/960

Add network policies for rhoai

---

deploy/templates/nstemplatetiers/base1ns/ns_dev.yaml

tests: https://github.com/codeready-toolchain/toolchain-e2e/pull/963

Increase memory quota for rhoai

---

controllers/spacerequest/spacerequest_controller.go
controllers/spacerequest/spacerequest_controller_test.go
go.mod
go.sum

[KUBESAW-121](https://issues.redhat.com/browse/KUBESAW-121)
depends on https://github.com/codeready-toolchain/toolchain-common/pull/403

fix: don't rely on certificates in ToolchainClusters

---

make/go.mk

This is related to the  discussion 
https://github.com/codeready-toolchain/api/pull/437#discussion_r1691463409

KS129 change the sequence of make file target

---

config/crd/bases/toolchain.dev.openshift.com_toolchainconfigs.yaml

remove webConsolePlugin from ToolchainClusterConfig (phase 1)

---

config/crd/bases/toolchain.dev.openshift.com_toolchainconfigs.yaml

Generated for https://github.com/codeready-toolchain/api/pull/439

CRD: Add CPU to Autoscaler buffer

---

go.mod
go.sum

Part of https://issues.redhat.com/browse/SANDBOX-724

Update api and common

---

config/crd/bases/toolchain.dev.openshift.com_bannedusers.yaml

Reason field was added to BannedUserSpec
https://github.com/codeready-toolchain/api/pull/442
[SANDBOX-681](https://issues.redhat.com/browse/SANDBOX-681)

SANDBOX-681: update toolchain.dev.openshift.com_bannedusers.yaml

---

deploy/templates/nstemplatetiers/intelxlarge/based_on_tier.yaml
pkg/templates/nstemplatetiers/nstemplatetier_generator_test.go

Paired with https://github.com/codeready-toolchain/toolchain-e2e/pull/1058

Create intel-x-large tier

---

deploy/templates/nstemplatetiers/base/cluster.yaml
deploy/templates/nstemplatetiers/base1ns/ns_dev.yaml

Requested by Kathryn
Paired with https://github.com/codeready-toolchain/toolchain-e2e/pull/1067

Increase storage quota to 60Gi

---

controllers/deactivation/deactivation_controller.go
controllers/deactivation/deactivation_controller_test.go

https://redhat-internal.slack.com/archives/CHK0J6HT6/p1736864013718759?thread_ts=1733416826.163349&cid=CHK0J6HT6
https://issues.redhat.com/browse/SANDBOX-837

skip deactivating state if deactivatingNotificationDays is zero

---

CODEOWNERS

project: add Rafaela, Feny and Lukas to CODEOWNERS

---

.golangci.yml

remove unsupported service:
`$ golangci-lint config verify --config=./.golangci.yml jsonschema: "" does not validate with "/additionalProperties": additional properties 'service' not allowed
`
Similar Prs
- Member-operator - https://github.com/codeready-toolchain/member-operator/pull/626
- Host Operator - https://github.com/codeready-toolchain/host-operator/pull/1143
- Toolchain-e2e - https://github.com/codeready-toolchain/toolchain-e2e/pull/1120
- Toolchain - common - https://github.com/codeready-toolchain/toolchain-common/pull/458
- Api - https://github.com/codeready-toolchain/api/pull/461 
- Registration Service - https://github.com/codeready-toolchain/registration-service/pull/511

Updating .golangci.yml config removing unsupported service

---

go.mod
go.sum

https://github.com/codeready-toolchain/toolchain-common/pull/462

fix: panic when GH api returns an error

---

config/crd/bases/toolchain.dev.openshift.com_bannedusers.yaml
config/crd/bases/toolchain.dev.openshift.com_masteruserrecords.yaml
config/crd/bases/toolchain.dev.openshift.com_notifications.yaml
config/crd/bases/toolchain.dev.openshift.com_nstemplatetiers.yaml
config/crd/bases/toolchain.dev.openshift.com_proxyplugins.yaml
config/crd/bases/toolchain.dev.openshift.com_socialevents.yaml
config/crd/bases/toolchain.dev.openshift.com_spacebindingrequests.yaml
config/crd/bases/toolchain.dev.openshift.com_spacebindings.yaml
config/crd/bases/toolchain.dev.openshift.com_spaceprovisionerconfigs.yaml
config/crd/bases/toolchain.dev.openshift.com_spacerequests.yaml
config/crd/bases/toolchain.dev.openshift.com_spaces.yaml
config/crd/bases/toolchain.dev.openshift.com_tiertemplaterevisions.yaml
config/crd/bases/toolchain.dev.openshift.com_tiertemplates.yaml
config/crd/bases/toolchain.dev.openshift.com_toolchainclusters.yaml
config/crd/bases/toolchain.dev.openshift.com_toolchainconfigs.yaml
config/crd/bases/toolchain.dev.openshift.com_toolchainstatuses.yaml
config/crd/bases/toolchain.dev.openshift.com_usersignups.yaml
config/crd/bases/toolchain.dev.openshift.com_usertiers.yaml

Generated by https://github.com/codeready-toolchain/api/pull/462
[SANDBOX-808](https://issues.redhat.com/browse/SANDBOX-808)

SANDBOX-808: update controller-gen.kubebuilder.io/version to v0.15.0

---

controllers/nstemplatetier/nstemplatetier_controller.go

Trigger reconciles on annotation change of NSTemplateTiers to actually speed up the deletion triggered by the e2e tests cleanup.
Related PRs:
- toolchain-e2e: https://github.com/codeready-toolchain/toolchain-e2e/pull/1171
https://issues.redhat.com/browse/SANDBOX-1346

Trigger reconciles on annotation change of NSTemplateTiers

---

cmd/main.go

Segment quota reset
reverting https://github.com/codeready-toolchain/host-operator/pull/1192

console: re-enable the DEVSANDBOX_SEGMENT_API_KEY annotation
