codeready-toolchain/host-operator

examples/toolchain_v1alpha1_masteruserrecord_cr.yaml, examples/toolchain_v1alpha1_nstemplatetier_cr.yaml, pkg/apis/addtoscheme_toolchain_v1alpha1.go
To run `host-operator` locally.  I have deployed relevant CRD, SA, Role and RoleBinding from host-operator project.
After that I tried to run host-operator locally with following command but got error.
Command: `operator-sdk up local --namespace myproject`
Error:
```
INFO[0000] Running the operator locally.                
INFO[0000] Using namespace myproject.                   
{"level":"info","ts":1560844031.4633334,"logger":"cmd","msg":"Go Version: go1.12.6"}
{"level":"info","ts":1560844031.4633586,"logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":1560844031.4633708,"logger":"cmd","msg":"Version of operator-sdk: v0.8.1"}
{"level":"info","ts":1560844031.4706278,"logger":"leader","msg":"Trying to become the leader."} …
```
=> fix - no kind is registered error while starting host operator locally

deploy/crds/toolchain_v1alpha1_masteruserrecord.yaml, deploy/crds/toolchain_v1alpha1_nstemplatetier.yaml
The CRDs are regenerated with the new `make generate` target from `api` repo. There are a few differences:
- `_crd` prefix is removed.
- the generator uses a different version of **k8s controller-tools** (the last stable one, which is 0.1.10) comparing to operator-sdk. Some changes look suspicious but let's fix them later if they cause any problems. We should fix them by using the proper version of the generator tools rather than manually changing the CRDs.
=> Rename CRD files to align with api generator

deploy/role.yaml
add toolchain.dev.openshift.com group to host-operator role so the ServiceAccount can watch these CRs
=> fix: add toolchain.dev.openshift.com group to host-operator role

go.mod, go.sum, pkg/controller/add_userprovisionrequest.go, pkg/controller/userprovisionrequest/userprovisionrequest_controller.go
This PR adds a freshly generator controller for reconciling `UserProvisionRequest` resources.
Fixes [CRT-173](https://jira.coreos.com/browse/CRT-173)
=> Create empty UserProvisionRequestController

make/test.mk
Use the `CLONEREFS_OPTIONS` env var to extract the PR/commit metadata and upload the coverage reports on codecov.io with the appropriate arguments
=> upload codecov results

.codecov.yaml
Disabling the codecov report expiry as documented in https://docs.codecov.io/docs/codecov-yaml#section-expired-reports to attempt to fix the missing reports after merging a PR on `master` branch.
=> disable codecov report expiry

deploy/operator_dev_cluster.yaml, examples/toolchain_v1alpha1_userprovisionrequest_cr.yaml, make/deploy.mk, make/dev.mk
*Changes Proposed in this PR*
- Adds ImageStream which points to image from openshift CI cluster.
- Add DeploymentConfig which uses above ImageStream
- Fix minor make targets
To Do
=> Add operator deploymentconfig and imagestream for continuous deployment

deploy/role.yaml
With the original configuration, it was failing for e2e tests with `no RBAC policy matched` error
=> fix: change role to have full permissions for toolchain.dev.openshift.com group

README.adoc, make/test.mk
This PR introduces changes to the test Makefile:
* prints logs when the e2e tests fail (useful in CI, otherwise there is no way to figure out what happened)
* renames variable `TEST_NAMESPACE` to `HOST_NS` to make it consistent with `MEMBER_NS`
* load names of the namespaces from variable
I also changed the README to reflect the changes
When and if we agree on these changes, then I'll push the same to member-operator repo
=> chore: print logs when e2e tests fail & change variable names

deploy/crds/toolchain_v1alpha1_masteruserrecord.yaml, examples/toolchain_v1alpha1_masteruserrecord_cr.yaml
1. Add `mur` as a short name for `MasterUserRecord`
2. Fix MUR example CR. We will need to refactor our MUR API (see https://github.com/codeready-toolchain/host-operator/pull/27#pullrequestreview-276884345) but for now let's fix the example since it's not valid atm.
=> Add short name for MasterUserRecord

README.adoc, make/dev.mk
Since operator-sdk 0.10.x has go module support, we don't need it when running the operator locally
=> chore: remove vendor support when running operator locally

go.mod, go.sum, pkg/controller/masteruserrecord/masteruserrecord_controller.go, pkg/controller/masteruserrecord/masteruserrecord_controller_test.go, test/e2e/masteruserrecord_test.go, test/e2e/wait_util.go, test/masteruserrecord/assertion.go, test/masteruserrecord/doubles.go
This PR:
* adds a finalizer to `MasterUserRecord` for the first reconcile (after the creation of `MUR` and before creating `UserAccouts`)
* deletes `UserAccounts` when the `MasterUserRecord` is going to be deleted
* removes the finalizer from `MasterUserRecord` after successful deletion of all `UserAccounts`
* adds unit tests as well as e2e test
=>  feat(CRT-176): add garbage collection for MasterUserRecord that deletes UserAccounts

deploy/cluster_role.yaml, deploy/cluster_role_binding.yaml, deploy/operator.yaml, deploy/operator_dev_cluster.yaml, deploy/role.yaml, go.mod, go.sum, make/dev.mk, make/test.mk, pkg/config/constants.go, pkg/controller/kubefedcluster.go, test/e2e/usersignup_test.go
* separates Role and ClusterRole permissions
* modifies KubeFedCluster e2e test to meet changes in https://github.com/codeready-toolchain/toolchain-common/pull/33
* cleanup fixes in UserSignup e2e test 
* removed unnecessary `OPERATOR_NAMESPACE` var
NOTE: depends on changes made in https://github.com/codeready-toolchain/toolchain-common/pull/33 as well as https://github.com/codeready-toolchain/member-operator/pull/56
=> fix(CRT-223): separate Role and ClusterRole permissions + test fixes/adjustments

go.mod
the git.apache.org seems to be still down https://status.apache.org/incidents/63030p4241xj
so I'm adding permanent workaround/solution
=> chore: replace git.apache.org/thrift.git by github.com/apache/thrift

make/test.mk
When the e2e tests are being executed in openshift-ci, then the repo will provide to e2e test logic the image that was already built for the host-operator PR
see codeready-toolchain/toolchain-e2e#6
=> chore: when running in CI use built image in e2e tests

.codecov.yaml, make/test.mk
We can't really test cmd/manager properly in unit tests (it's coverd in e2e tests) so excluding it from the codecov report. See https://github.com/codeready-toolchain/host-operator/pull/80
=> Exclude cmd/manager (main) from coverage report

.golangci.yml, make/lint.mk
configure in .golangci.yml instead of in the CLI,
using the new `timeout` name in replacement of
`deadline` which is now deprecated.
fixes CRT-295
=> configure golangci-lint timeout

go.mod, go.sum, pkg/controller/usersignup/usersignup_controller.go, pkg/controller/usersignup/usersignup_controller_test.go
This PR updates the host operator to remove usage of the `UserSignup.Spec.UserID` field.  Instead of using the `UserID` field to populate the MasterUserRecord name, the UserSignup.Name value is now used instead.
Fixes https://jira.coreos.com/browse/CRT-315
=> Updated host operator to remove UserSignup.Spec.UserID

.travis.yml, make/docker.mk
brings travis config file that will for every commit to master branch:
* build the project
* build the image of the project and push it to quay
* using the olm scripts from `api` repo generate a new version of the host-operator and (using operator courier) pushes it to quay
Already working build can be seen here: https://travis-ci.org/MatousJobanek/host-operator
and the pushed bundles here: https://quay.io/application/matousjobanek/toolchain-host-operator?tab=releases
This PR depends on logic introduced in this PR https://github.com/codeready-toolchain/api/pull/58
IMPORTANT: This PR is ready to review, but please, don't merge it yet as I need to do some additional setup (in quay and in travis) just before merging it ;-)
=> (DO NOT MERGE) chore: deploy csv for every commit in master via travis-ci

deploy/crds/toolchain_v1alpha1_registrationservice_crd.yaml, deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain-host-operator.v0.0.1.clusterserviceversion.yaml, deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain_v1alpha1_registrationservice_crd.yaml, examples/toolchain_v1alpha1_registrationservice_cr.yaml, hack/deploy_csv.yaml
It will be used as a holder of reg-service configuration as well as a triggerrer of the actual deployment.
The params that are in the CRD have been taken from the ConfigMap used by the registration service
result of https://github.com/codeready-toolchain/api/pull/61
=> feat(CRT-352): create RegistrationService CRD

.gitignore, deploy/registration-service/deployment.yaml, deploy/registration-service/registration-service.yaml, make/go.mk
As the registration service needs to be created programmatically we need the deployment template inside of host-operator repo - this PR:
* copies the deployment template
* embed it as an asset (will be used later)
See these PRs for better context:
https://github.com/codeready-toolchain/registration-service/pull/75
https://github.com/codeready-toolchain/api/pull/65
=> chore(CRT-361): copy registration-service deployment and embed it as an asset

deploy/crds/toolchain_v1alpha1_masteruserrecord_crd.yaml, deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain_v1alpha1_masteruserrecord_crd.yaml, go.mod, go.sum, hack/deploy_csv.yaml
See
https://github.com/codeready-toolchain/api/pull/66
and
https://github.com/codeready-toolchain/toolchain-common/pull/65
=> Remove deprecated TargetCluster from MUR status

deploy/templates/nstemplatetiers/advanced-code.yaml, deploy/templates/nstemplatetiers/advanced-dev.yaml, deploy/templates/nstemplatetiers/advanced-stage.yaml, deploy/templates/nstemplatetiers/basic-code.yaml, deploy/templates/nstemplatetiers/basic-dev.yaml, deploy/templates/nstemplatetiers/basic-stage.yaml, pkg/templates/nstemplatetiers/nstemplatetier_generator_whitebox_test.go
Edit role is not enough for Che. It requires access to some resources like roles which is not allowed by edit.
We can probably create a specific role and define the minimum permissions but I think it's OK if we just add admin role for the user for now. Deleting a namespace by user should not be a problem because our NSTemplateSet Controller will recreate namespaces.
Later we will improve it.
e2e tests: https://github.com/codeready-toolchain/toolchain-e2e/pull/62
=> Grant users admin role

go.mod, go.sum, pkg/controller/masteruserrecord/sync.go, pkg/controller/masteruserrecord/sync_test.go
Add Che Dashboard URL to MUR status if Che is available in the cluster.
There is no e2e tests for this change because we do not install Che Operator on our tests clusters.
This is something to address later.
=> Add Che Dashboard URL to MUR status

deploy/templates/nstemplatetiers/advanced-code.yaml, deploy/templates/nstemplatetiers/advanced-dev.yaml, deploy/templates/nstemplatetiers/advanced-stage.yaml, deploy/templates/nstemplatetiers/basic-code.yaml, deploy/templates/nstemplatetiers/basic-dev.yaml, deploy/templates/nstemplatetiers/basic-stage.yaml, pkg/templates/nstemplatetiers/nstemplatetier_generator_whitebox_test.go
Requires https://github.com/codeready-toolchain/member-operator/pull/109 to be merged first to pass e2e tests.
After some investigation it looks like che requires edit permissions for roles and rolebindings in the namespace to create workspaces. This is on top of the edit role (to create other resources like deployments, routes, services, etc).
This PR reduces permissions to edit role for all namespaces and adds the missing edit permissions for roles and rolebindings for -code namespace.
E2E tests: https://github.com/codeready-toolchain/toolchain-e2e/pull/63
=> Reduce user permissions

cmd/manager/main.go
When creating metrics of our CRs we should use our toolchain apis
This will get rid of the annoying errors `reflector.go:95: Failed to list` in the logs
=> fix: use toolchain apis for listing CRs to be monitored

go.mod, go.sum, pkg/apis/apis.go
The scheme should contain only CRs apis - this will get rid of the last `reflector.go:95: Failed to list` errors from our logs - we should create metrics for the extensions
see: https://github.com/codeready-toolchain/api/pull/83
=> fix: common api sheme contain only CRs

deploy/cluster_role.yaml, deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain-host-operator.v0.0.1.clusterserviceversion.yaml, deploy/role.yaml, hack/deploy_csv.yaml
Since the RBAC issue with `reflector.go:95: Failed to list` errors should be fixed I decided to remove unneeded permissions from our roles. I didn't spend much time investigating which particular permissions are used and which are not, I just removed those that were apparently added just as a workaround for making our logs clean and happy.
=> chore: remove unneeded permissons

.travis.yml, openshift-ci/Dockerfile.tools
`yq` binary is needed in the script introduced here https://github.com/codeready-toolchain/api/pull/88. The script will be then used for e2e tests as well as for CD
=> chore: install github.com/kislyuk/yq binary

pkg/controller/masteruserrecord/masteruserrecord_controller_test.go, pkg/controller/masteruserrecord/sync.go
Currently ff MUR reconcile failed with some error (target member cluster is temporally not available for example) then the error is stuck in MUR.Status.Ready condition if there is no changes in the MUR.Status.UserAccount[] conditions.
Steps to reproduce:
- Create a MUR and get it provisioned. UserAccount is provisioned and MUR is Ready.
- Break the member kubefedcluster, so member is not available from host.
- Trigger MUR reconcile
- MUR.Status.Ready condition is false now with the error about unavailable member
- Fix member cluster
- MUR reconcile is called but there is nothing to update in MUR.Status.UserAccount[] since the corresponding UserAccount statuses didn't change in member. So, MUR do not update Ready condition either and we stuck with the error.
This PR fixes the problem and …
=> Fix MUR status synchronization in case of target availability error

deploy/crds/toolchain_v1alpha1_masteruserrecord_crd.yaml, deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain-host-operator.v0.0.1.clusterserviceversion.yaml, deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain_v1alpha1_masteruserrecord_crd.yaml, hack/deploy_csv.yaml
Relates to PR: https://github.com/codeready-toolchain/api/pull/100 
Relates to Jira task: https://issues.redhat.com/browse/CRT-455
Relates to Jira story: https://issues.redhat.com/browse/CRT-444
Copying UserAccountSpec to masteruserrecord_types and rename to UserAccountEmbedded in order to decouple UserAccountSpec type from UserAccount.
This will be done in three stages:
1. Deprecate Embedded UA ID/Disabled
2. Change the implementation and start using the new API. Roll out to prod.
3. Delete deprecated API.
This PR is a part of stage 1.
=> generated from make generate in api

.travis.yml, make/manifests.mk, openshift-ci/Dockerfile.tools
this is another preparation for running builds via Tekton pipelines
* adds `push-to-quay-nightly` makefile target so we can trigger the push process by calling the target that already uses all necessary params
* add installation of operator-courier to the `Dockerfile.tools` so we can use the image for pushing the CSV to quay
=> chore: add push-to-quay-nightly makefile target & add courier to dockerfile

deploy/templates/nstemplatetiers/advanced/ns_code.yaml, deploy/templates/nstemplatetiers/advanced/ns_dev.yaml, deploy/templates/nstemplatetiers/advanced/ns_stage.yaml, deploy/templates/nstemplatetiers/basic/ns_code.yaml, deploy/templates/nstemplatetiers/basic/ns_dev.yaml, deploy/templates/nstemplatetiers/basic/ns_stage.yaml, deploy/templates/nstemplatetiers/team/ns_dev.yaml, deploy/templates/nstemplatetiers/team/ns_stage.yaml, pkg/templates/nstemplatetiers/nstemplatetier_generator_whitebox_test.go
This PR adds NetworkPolicies to all namespace templates to block traffic from pods from other namespaces.
Requires https://github.com/codeready-toolchain/member-operator/pull/133 to be merged first.
See https://issues.redhat.com/browse/CRT-492
e2e tests - https://github.com/codeready-toolchain/toolchain-e2e/pull/83
=> Isolate pods in user namespaces

deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain-host-operator.v0.0.1.clusterserviceversion.yaml, examples/toolchain_v1alpha1_usersignup_cr.yaml, go.mod, go.sum, hack/deploy_csv.yaml, pkg/controller/masteruserrecord/masteruserrecord_controller.go, pkg/controller/masteruserrecord/masteruserrecord_controller_test.go, pkg/controller/masteruserrecord/sync.go, pkg/controller/masteruserrecord/sync_test.go, pkg/controller/usersignup/usersignup_controller.go, pkg/controller/usersignup/usersignup_controller_test.go
add missing label and annotation on example user signup
refactored the code to pass the logger to the status updaters
using the same var name everywhere for consistency
refactoring the `IsSynchronized` logic and testing.
Updates https://issues.redhat.com/browse/CRT-459
=> Code cleanup 

deploy/templates/nstemplatetiers/advanced/ns_code.yaml, deploy/templates/nstemplatetiers/advanced/ns_dev.yaml, deploy/templates/nstemplatetiers/advanced/ns_stage.yaml, deploy/templates/nstemplatetiers/basic/ns_code.yaml, deploy/templates/nstemplatetiers/basic/ns_dev.yaml, deploy/templates/nstemplatetiers/basic/ns_stage.yaml, deploy/templates/nstemplatetiers/team/cluster.yaml, deploy/templates/nstemplatetiers/team/ns_dev.yaml, deploy/templates/nstemplatetiers/team/ns_stage.yaml, pkg/templates/nstemplatetiers/nstemplatetier_generator_whitebox_test.go
change/optimize limits across tiers. We agreed on these numbers:
* **code/stage** (the original values)
* cpu: 150m
* memory: 512Mi
* **dev** (enough for running pipeline tutorials)
* cpu: 250m
* memory: 1Gi
* **dev/stage**
* cpu: 500m
* memory: 2Gi
* **cluster**
* cpu: 2000m
* memory: 10Gi
paired PR: https://github.com/codeready-toolchain/toolchain-e2e/pull/97
=> chore: optimize limits across tiers

deploy/templates/nstemplatetiers/advanced/ns_code.yaml, deploy/templates/nstemplatetiers/basic/ns_code.yaml, deploy/templates/nstemplatetiers/team/ns_dev.yaml, deploy/templates/nstemplatetiers/team/ns_stage.yaml, pkg/templates/nstemplatetiers/nstemplatetier_generator_whitebox_test.go
Instead of allowing `"*"` verbs for `role/rolebinding` resources in user namespaces we should explicitly allow all verbs but `"escalate" `.
Since `"*"` also includes `"escalate"` it allows users to escalate privileges and create roles/rolebindings  with permissions the user doesn't already have. User would be able to modify limitranges for example.
With this change users won't be able to escalate permissions.
e2e tests: https://github.com/codeready-toolchain/toolchain-e2e/pull/98
=> Prevent privilege escalation in user namespaces

go.mod, go.sum
see https://github.com/codeready-toolchain/toolchain-common/pull/99
=> chore: update common that refreshes cache when no cluster is found

go.mod, go.sum
Remove replacement of the toolchain-common - introduced by me when I accidentally merged the PR https://github.com/codeready-toolchain/host-operator/pull/185 without removing the replacement
I'm idiot :facepalm:
=> fix: remove replacement of common and update it

deploy/templates/nstemplatetiers/advanced/ns_dev.yaml, deploy/templates/nstemplatetiers/basic/ns_dev.yaml, deploy/templates/nstemplatetiers/team/cluster.yaml, deploy/templates/nstemplatetiers/team/ns_dev.yaml, deploy/templates/nstemplatetiers/team/ns_stage.yaml, pkg/templates/nstemplatetiers/nstemplatetier_generator_whitebox_test.go
My explanation for the values:
We need to take into account that if we aggregate all values taken from the running pods/containers, then the resulting values cannot exceed the values set in `ClusterResourceQuotas`:
* basic/advanced:
* cpu: 1750m
* memory: 7Gi
* team:
* cpu: 2000m
* memory: 15Gi (increased from 10Gi to have some cushion - we will be able to run tasks that eat more memory in parallel) 
In addition, when there is an `EventListener` running in the namespace, it immediately takes the default values (we run 2 EventListeners in our codeready-toolchain-dev namespace). That lowers the memory/millicpu that has left for the actual Pipelines/Tasks. 
Then, the actual `TaskRun` contains (apart from the steps) also some additional init/internal containers (eg. for cloning repo, creating …
=> chore: balance values in LimitRanges/Quotas to fit in memory/cpu limits

deploy/templates/nstemplatetiers/advanced/ns_code.yaml, deploy/templates/nstemplatetiers/basic/ns_code.yaml, pkg/templates/nstemplatetiers/nstemplatetier_generator_whitebox_test.go
https://github.com/codeready-toolchain/host-operator/pull/197 helped to speed up Che workspace/IDE. But it turned out that there are two pods managed by Che:
- first pod is created by Che which starts a workspace.
- as the result of the first pod another pod (workspace pod) is created.
The starting pod doesn't specify limits so our default limits from the limit range is used. I took the new numbers from che.openshift.io. It's 1 core of CPU and 512Mi of RAM. That seems to help to speed up the che ws start.
The second pod (the workspace itself) is already fast enough after applying https://github.com/codeready-toolchain/host-operator/pull/197 and https://github.com/codeready-toolchain/toolchain-infra/pull/15
e2e tests: https://github.com/codeready-toolchain/toolchain-e2e/pull/107
=> Set the default Che limits to 1 core to speed up workspace creation

go.mod, go.sum, pkg/controller/masteruserrecord/masteruserrecord_controller.go
In order to track the status of the user provisioned notification, we need to add a new Status condition to MasterUserRecord.
This PR adds the conditions for both provisioned notification created and provisioned notification failed. 
Jira: https://issues.redhat.com/browse/CRT-521
=> add notification condition to mur

pkg/controller/changetierrequest/changetierrequest_controller.go, pkg/controller/usersignup/masteruserrecord.go, pkg/controller/usersignup/masteruserrecord_test.go, pkg/controller/usersignup/usersignup_controller.go, pkg/controller/usersignup/usersignup_controller_test.go
Jira issue: https://issues.redhat.com/browse/CRT-659
In the current running clusters, there are already some users provisioned but their MUR instances still contain only `Revision` and `Type` fields filled and not `TemplateRef` - this is still empty.
We need to migrate all existing users to use the `TemplateRef` field otherwise we are not able to start deployment of member operator (that is caused by another issue in member-operator)
There is no way to create e2e tests for it - we cannot create MUR without TeplateRef field filled since the field is mandatory. But I tested it locally and everything worked fine - the MUR (and all related resources) was updated so it contains `TemplateRef` field set
=> fix: migrate existing MURs from deprecated fields to TemplateRef field

go.mod, go.sum, pkg/controller/changetierrequest/changetierrequest_controller_test.go, pkg/controller/usersignup/masteruserrecord.go, pkg/templates/nstemplatetiers/nstemplatetier_generator.go, pkg/templates/nstemplatetiers/nstemplatetier_generator_whitebox_test.go
Move constant containing type name of a template that contains cluster-scoped resources into the api repo. In addition, I made the string lower case since the name of the resource shouldn't contain any capital letter anyway.
depends on https://github.com/codeready-toolchain/api/pull/140
=> chore: move constant containing clusterresources type name to api

pkg/configuration/configuration.go
Fixes https://issues.redhat.com/browse/CRT-677
Adds configuration parameter to allow the setting of a specific notification delivery service to use.
=> Add configuration parameter for notification delivery service

deploy/olm-catalog/toolchain-host-operator/bundle.Dockerfile, deploy/olm-catalog/toolchain-host-operator/metadata/annotations.yaml
Adds two files needed by opm and by operator registry.
* `bundle.Dockerfile` used for the operator bundle image
* `metadata/annotations.yaml` containing metadata info about the operator bundle
=> chore: add bundle metadata and Dockerfile

make/manifests.mk
Add new targets to manifests makefile - these targets will be used by CD to release a new nightly/staging releases.
* generate-cd-release-manifests - generates a new version of operator manifests
* push-manifests-as-app - pushes manifests as an application to quay
* push-bundle-and-index-image - pushes manifests as a bundle image to quay and adds it to the index image
* recover-operator-dir - recovers the operator bundle directory from backup folder
=> chore: add manifests targets that will be used by CD

cmd/manager/main.go
When getting the metrics, we have to use the schema builder taken from the api repo. The reason is that the schema builder adds only our toolchain CRDs + KubeFed api. The schema builder in host operator adds api also for additional groups and our ServiceAccount doesn't have enough permissions to list all of them. That's why we have a lot of `Failed to list *unstructured.Unstructured:` errors in our logs nowadays.
=> fix: get metrics only for Toolchain CRDs

pkg/configuration/configuration.go, pkg/configuration/configuration_test.go
Currently secret env vars are not properly created. The code replaces "-" instead of "." causing env var names such as `HOST_OPERATOR_MAILGUN.DOMAIN." Instead this should be `HOST_OPERATOR_MAILGUN_DOMAIN`
This PR is to handle replacing both "." and "-" with "_"
=> fixing string replace to handle . and -

deploy/env/e2e-tests.yaml, pkg/configuration/configuration.go, pkg/configuration/configuration_test.go
Adding environment variable for host-operator in order to help write end-to-end tests for the notification service.
This env var will be used to determine whether or not we should even attempt sending a notification depending on the environment. In the e2e-environment it is not easily possible to test the notification service. Since we cannot expose the secret for end-to-end tests and setting up a mock server is not as easily do-able, we can instead set up an environment variable. If the environment variable is set to `e2e` then we will bypass sending the notification via mailgun and proceed onwards to set the notification status to `sent` and verify that the notification is deleted after the deletion timestamp has elapsed.
=> adding environment variable

go.sum, pkg/configuration/configuration.go, pkg/controller/notification/mailgun_notification_delivery_service.go, pkg/controller/notification/mailgun_notification_delivery_service_test.go, pkg/controller/notification/notification_context.go, pkg/controller/notification/notification_context_test.go, pkg/controller/notification/notification_controller.go, pkg/controller/notification/notification_controller_test.go, pkg/controller/notification/notification_delivery_service_test.go, test/notification/assertion.go
This PR implements notification delivery within the notification controller.  The `newReconciler()` function now creates a new notification delivery service factory which uses the configuration to determine which type of delivery service to create.  Currently we support **mailgun** (for production use) and **mock** (for testing).  Depending on which is configured, the delivery service will be created as part of the NotificationReconciler.
Fixes https://issues.redhat.com/browse/CRT-678
=> Implement notification delivery in notification controller

deploy/cluster_role.yaml, deploy/olm-catalog/toolchain-host-operator/manifests/toolchain-host-operator.clusterserviceversion.yaml, deploy/role.yaml, hack/deploy_csv.yaml
Since Idler is cluster scoped we need to move toolchain from role.yaml to cluster-role.yaml.
It should fix errors like this in hosted toolchain log: 
```
Failed to list *unstructured.Unstructured: idlers.toolchain.dev.openshift.com is forbidden: User "system:serviceaccount:xcoulon-host-17145616:host-operator" cannot list resource "idlers" in API group "toolchain.dev.openshift.com" at the cluster scope
```
=> Allow access to cluster scoped toolchain resources

go.mod, go.sum, pkg/controller/toolchainstatus/toolchainstatus_controller.go, pkg/controller/toolchainstatus/toolchainstatus_controller_test.go, test/toolchainstatus_assertions.go
If there is a problem with a member cluster it may not be listed in the the cluster cache. In the toolchainstatus code it falls under the no member clusters found case. In this case the status object is being created but it is not being added to the toolchainstatus. The fix is simply to add it to the toolchainstatus. Also, the unit tests were only checking the overall status only, they should be updated to check the individual component statuses as well.
Related issue: https://issues.redhat.com/browse/CRT-731
=> Fix no members case in toolchainstatus

deploy/crds/toolchain_v1alpha1_toolchainstatus_crd.yaml, deploy/olm-catalog/toolchain-host-operator/manifests/toolchain_v1alpha1_toolchainstatus_crd.yaml, hack/deploy_csv.yaml
This PR contains generated files for the new Host field of the MemberStatus API that will be used to report the host connection status with toolchain Condition type instead of Kubefed types.
=> Generated files for memberstatus Host field

cmd/manager/main.go, go.mod, go.sum, pkg/configuration/configuration.go, pkg/configuration/configuration_test.go, pkg/controller/masteruserrecord/masteruserrecord_controller.go, pkg/controller/masteruserrecord/masteruserrecord_controller_test.go, pkg/controller/masteruserrecord/sync.go, pkg/controller/masteruserrecord/sync_test.go
We have to move
https://github.com/codeready-toolchain/host-operator/blob/master/pkg/controller/masteruserrecord/sync.go#L29-L30
and
https://github.com/codeready-toolchain/host-operator/blob/master/pkg/controller/masteruserrecord/sync.go#L178
to configuration so we can customize them via ConfigMap.
It's needed for OSD integration.
Jira: https://issues.redhat.com/browse/CRT-745
Related PR: https://github.com/codeready-toolchain/toolchain-infra/pull/28/files
=> using configuration for console and che routes and namespaces

deploy/olm-catalog/toolchain-host-operator/manifests/toolchain-host-operator.clusterserviceversion.yaml, deploy/role.yaml, hack/deploy_csv.yaml
Since we migrated to ToolchainCluster CRD then the operator doesn't need the permissions to access/modify the KubeFed resources
=> chore: remove KubeFed from role

deploy/crds/toolchain_v1alpha1_masteruserrecord_crd.yaml, deploy/olm-catalog/toolchain-host-operator/manifests/toolchain_v1alpha1_masteruserrecord_crd.yaml, go.mod, go.sum, hack/deploy_csv.yaml, pkg/controller/masteruserrecord/sync.go, pkg/controller/masteruserrecord/sync_test.go
This PR adds the following
- generated files for the new MUR.Status.ProvisionedTime field
- logic to set the ProvisionedTime field on the first time the MUR goes to Provisioned status
- unit tests
Related PRs:
- https://github.com/codeready-toolchain/api/pull/176
- https://github.com/codeready-toolchain/toolchain-common/pull/122
=> Provisioned time for MUR

deploy/olm-catalog/toolchain-host-operator/manifests/toolchain-host-operator.clusterserviceversion.yaml, deploy/role.yaml, hack/deploy_csv.yaml
A couple of permissions were missing, which resulted
in the following errors:
```
{"level":"info","msg":"Could not create metrics Service","error":"failed to initialize service object for metrics: replicasets.apps \"host-operator-849b9cccc4\" is forbidden: User \"system:serviceaccount:xcoulon-host-12182550:host-operator\" cannot get resource \"replicasets\" in API group \"apps\" in the namespace \"xcoulon-host-12182550\""}
```
and then
```
{"level":"info","msg":"Could not create ServiceMonitor object","error":"servicemonitors.monitoring.coreos.com \"host-operator-metrics\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>"}
```
E2E tests: https://github.com/codeready-toolchain/toolchain-e2e/pull/142
Signed-off-by: …
=> fix: start metrics server at operator startup

go.mod, go.sum, pkg/controller/nstemplatetier/nstemplatetier_controller_test.go
replaced the use of `github.com/alecthomas/assert`
with `github.com/strechr/testify/assert`
=> test: replace 'assert' pkg

go.mod, go.sum, pkg/controller/masteruserrecord/masteruserrecord_controller.go, pkg/controller/masteruserrecord/masteruserrecord_controller_test.go, pkg/controller/nstemplatetier/nstemplatetier_controller.go, pkg/controller/nstemplatetier/nstemplatetier_controller_test.go, test/templateupdaterequest/templateupdaterequest.go
When ensuring the UserAccounts for the MasterUserRecord exist, if one
is being deleted, then the controller will requeue (with a delay),
which should give time to the member cluster to finish deleting
the resources. Then, during the new reconcile loop, the
MasterUserRecord controller will recreate the UserAccount.
Also, small refactorings (func name and using `metav1.Now()`
as a shorthand)
E2E Tests: https://github.com/codeready-toolchain/toolchain-e2e/pull/146
Fixes https://issues.redhat.com/browse/CRT-778
=> fix: recreate UserAccount when deleted (on purpose or by accident)

deploy/registration-service/registration-service.yaml
we forgot to add this to the host-operator. it was only added to the registration-service:  https://github.com/codeready-toolchain/registration-service/blob/master/deploy/registration-service.yaml#L28
=> adding update permissions to registration-service.yaml

go.mod, go.sum, pkg/controller/toolchainstatus/toolchainstatus_controller.go, pkg/controller/toolchainstatus/toolchainstatus_controller_test.go, test/toolchainstatus_assertions.go
This PR refactors the ToolchainStatus controller:
* the handlers doesn't return error but boolean saying if the components are ready or not
* as a side effect, we will log all errors, not only the latest one (as it was done before)
* it checks if any ToolchainCluster that was previously present was removed - if so, then it sets the `ready = false` with reason `MemberToolchainClusterRemoved`
* in the next PR, it will be combined with the conter - it will verify if the removed member cluster contains any provisioned UserAccounts or not to check if the removal was safe.
* removed the check if the member client is nill or not - this was unreal use-case - all member clusters that are in cache has the client initialized
All these changes are required to make it working with the counter that …
=> chore: refactor ToolchainStatus controller

go.mod, go.sum, pkg/configuration/configuration.go, pkg/configuration/configuration_test.go, pkg/controller/controller.go, pkg/controller/deactivation/deactivation_controller.go, pkg/controller/deactivation/deactivation_controller_test.go, test/nstemplatetier/nstemplatetier.go
Adds a new deactivation controller that watches MUR resources and triggers deactivation of users after the deactivation period expires. The deactivation period is determined by their associated tier.
Adds a configurable domain exclusion list that allows user accounts that match any of the domains in the list to be excluded from automatic deactivation
- The deactivation controller checks the NSTemplateTier associated with the MUR to discover the deactivation timeout value
- If the time since the MUR was provisioned exceeds the Deactivation Period then deactivate the user
- Otherwise, it will requeue the reconcile to a time when the user should be deactivated
- Added unit tests
Note: We cannot activate auto deactivation until we have an API to delete users from Che so this PR introduces the …
=> Deactivation controller

pkg/controller/usersignup/mapper.go, pkg/controller/usersignup/mapper_test.go, pkg/controller/usersignup/predicate.go, pkg/controller/usersignup/predicate_test.go, pkg/controller/usersignup/status.go, pkg/controller/usersignup/status_test.go, pkg/controller/usersignup/usersignup_controller.go, pkg/controller/usersignup/usersignup_controller_test.go
This PR slightly refactors the UserSignup controller - the code was long with long methods and hard to maintain and read.
I moved:
* predicate related code into `predicate.go` (the related tests were moved into `predicate_test.go`)
* mapper related code into `mapper.go` (the related tests were moved into `mapper_test.go`)
* functions taking care of status update into `status.go`. There was no test that would verify the status update functionality, but I added a new one that verifies the method `wrapErrorWithStatusUpdate` into `status_test.go`
All above is just copy-paste operations
Then I split the `Reconcile` method into separated methods. Newly, none one of the new methods returns the `reconcile.Result{}` - they return only values related to their functionality.
Newly, when the …
=> Refactor user signup

go.mod, go.sum, pkg/controller/masteruserrecord/masteruserrecord_controller_test.go, pkg/controller/toolchainstatus/toolchainstatus_controller_test.go, pkg/controller/usersignup/mapper_test.go, pkg/controller/usersignup/masteruserrecord_test.go, pkg/controller/usersignup/predicate_test.go, pkg/controller/usersignup/usersignup_controller.go, pkg/controller/usersignup/usersignup_controller_test.go, test/cluster.go, test/toolchainstatus.go, test/usersignup.go
Rename:
`newGetMemberCluster` -> `NewGetMemberCluster` and moved to  `test/cluster.go`
`clusterClient` -> `ClusterClient` and moved to `test/cluster.go`
`newToolchainStatus` -> `NewToolchainStatus` and moved to  `test/toolchainstatus.go`
`newObjectMeta` -> `NewUserSignupObjectMeta` and moved to  `test/usersignup.go`
`operatorNamespace` -> `test.HostOperatorNs`
`defaultToolchainStatusName` -> `configuration.DefaultToolchainStatusName`
Introduced `getMemberClusters cluster.GetMemberClustersFunc` param in UserSignup controller for easy mocking.
replaced all initialization of `UserSignup` with `NewUserSignup()` function
=> chore: refactor test helper functions to make them reusable&extendable

deploy/env/dev.yaml, deploy/env/e2e-tests.yaml, deploy/env/prod.yaml, deploy/templates/nstemplatetiers/advanced/tier.yaml, deploy/templates/nstemplatetiers/basic/tier.yaml, pkg/templates/nstemplatetiers/nstemplatetier_generator_test.go, pkg/templates/nstemplatetiers/nstemplatetier_generator_whitebox_test.go
This PR changes the following:
- automatic user deactivation for the basic and advanced tiers. The team tier will remain the same (no `deactivationTimeoutDays` configured) so users in that tier will not be automatically deactivated
- adds `@redhat.com` to the auto deactivation exclusion list for both prod and dev environments
- adds `@excluded.com` to the auto deactivation exclusion list for the test environments
e2e PR: https://github.com/codeready-toolchain/toolchain-e2e/pull/169
- tests the auto exclusion list configured with `@excluded.com`
Related issue:
https://issues.redhat.com/browse/CRT-815
=> Enable auto deactivation on basic and advanced tiers and exclusion

deploy/env/e2e-tests.yaml
This PR simply enables the phone verification feature for e2e tests.
This is part of the changes required for https://issues.redhat.com/browse/CRT-792.
=> Enable phone verification in e2e tests

deploy/templates/notificationtemplates/userdeactivated/notification.html, deploy/templates/notificationtemplates/userdeactivated/subject.txt, deploy/templates/notificationtemplates/userprovisioned/notification.html, deploy/templates/notificationtemplates/userprovisioned/subject.txt, pkg/templates/notificationtemplates/notification_generator_test.go
Updates the email text for both the provisioned and deactivated emails that are sent to users.
Changes:
- new deactivation email
- updated provisioned email to specify active period of 14 days
- updated naming to "Red Hat OpenShift Dev Sandbox Beta"
=> chore: Update email text for provision and deactivation

deploy/templates/notificationtemplates/userdeactivated/notification.html, deploy/templates/notificationtemplates/userprovisioned/notification.html
adding devsandbox@redhat.com to provisioned and deactivated notification templates.
Jira: https://issues.redhat.com/browse/CRT-625
copying contents regarding the email for the templates from this document: https://docs.google.com/document/d/1KaN9BrsYpTvWnZZ_svWeTPIJY4UUJcnudM3gryRYi9k/edit
=> adding devsandbox email to templates

pkg/controller/usersignup/approval.go, pkg/controller/usersignup/approval_test.go, pkg/controller/usersignup/predicate.go, pkg/controller/usersignup/predicate_test.go, pkg/controller/usersignup/unapproved/cache.go, pkg/controller/usersignup/unapproved/cache_test.go, pkg/controller/usersignup/unapproved/mapper.go, pkg/controller/usersignup/unapproved/mapper_test.go, pkg/controller/usersignup/usersignup_controller.go, pkg/controller/usersignup/usersignup_controller_test.go, test/usersignup.go
This PR adds some kind of waiting list for unapproved UserSignups. The waiting list is just an abstraction - it represents all UserSignups with the label `state=pending`.
On this waiting list are user signups that:
* are not approved manually 
* cannot be approved automatically because either automatic approval is disabled or there is no member cluster with available capacity
* are approved manually but there is no member cluster with available capacity
How this "waiting list abstraction" works?
We have a new watcher that:
* watches `ToolchainStatus` CRD - this means that the watcher will be triggered every 5s
* has a predicate to trigger a reconcile loop only when the automatic approval is enabled
* maps the ToolchainStatus update event to the oldest unapproved UserSignup
So as you can …
=> feat: add waiting list for unapproved UserSignups 

cmd/manager/main.go, go.mod, pkg/controller/deactivation/deactivation_controller.go, pkg/controller/deactivation/deactivation_controller_test.go, pkg/controller/usersignup/usersignup_controller.go, pkg/controller/usersignup/usersignup_controller_test.go, pkg/counter/cache.go, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go, test/counter.go, test/metric.go
This PR adds to https://github.com/codeready-toolchain/host-operator/pull/286 which exposes the metrics endpoint.
Metric | Type | Description 
--- | --- | ---
user_signups_total | Counter | Total number of unique User Signups
user_signups_provisioned_total | Counter | Total number of Provisioned User Signups
user_signups_banned_total | Counter | Total number of Banned User Signups
user_signups_deactivated_total | Counter | Total number of Deactivated User Signups
user_signups_auto_deactivated_total | Counter | Total number of Automatically Deactivated User Signups
master_user_record_current | Gauge | Current number of Master User Records (mirrors the MUR counter from the cache)
1. single usersignup created
1. deactivate
1. reactivated
1. deactivated again
1. reactivated again
``` …
```
=> Gather and expose custom metrics

go.mod, pkg/apis/apis.go, pkg/configuration/configuration.go, pkg/configuration/configuration_test.go, pkg/controller/masteruserrecord/masteruserrecord_controller_test.go, pkg/controller/masteruserrecord/sync.go, pkg/controller/masteruserrecord/sync_test.go, pkg/controller/toolchainstatus/toolchainstatus_controller.go, pkg/controller/toolchainstatus/toolchainstatus_controller_test.go, test/toolchainstatus.go
This PR drops the direct retrieval of console & che routes from member clusters and takes the URL from the ToolchainStatus. 
It also drops unnecessary configuration parameters that were moved to member operator.
This PR depends on https://github.com/codeready-toolchain/member-operator/pull/213
In the future, we will change the registration-service logic so the URLs are not taken from `MUR.status` but from `ToolchainStatus`. Then we will be able to drop this logic from host-operator completely.
=> chore: take the console & che url from ToolchainStatus

pkg/controller/usersignup/usersignup_controller.go, pkg/controller/usersignup/usersignup_controller_test.go, pkg/metrics/metrics.go
Rename user_signups_provisioned_total to user_signups_approved_total since approved doesn't necessarily mean provisioned.
=> chore: Rename user_signups_provisioned_total to user_signups_approved_total

pkg/configuration/configuration.go, pkg/configuration/configuration_test.go, pkg/controller/usersignup/usersignup_controller.go, pkg/controller/usersignup/usersignup_controller_test.go
This PR introduces a change to `UserSignupController` in order to check that usernames don't begin with a forbidden prefix, such as "openshift" or "kubernetes".  If the username does start with one of these strings, it will be prefixed with "crt-".
Fixes https://issues.redhat.com/browse/CRT-783
=> Add handling for forbidden username prefixes

pkg/templates/nstemplatetiers/nstemplatetier_generator.go, pkg/templates/nstemplatetiers/nstemplatetier_generator_test.go
adds more logs to the logic that creates or updates `NSTemplateTier` resources based on the changes from the bundled templates.
This should help us with monitoring any possible changes in the Tier resources
Paired with: https://github.com/codeready-toolchain/toolchain-e2e/pull/206
=> chore: add more logs when updating NSTemplateTier resources

deploy/templates/notificationtemplates/userdeactivated/notification.html, deploy/templates/notificationtemplates/userprovisioned/notification.html, pkg/templates/notificationtemplates/notification_generator_test.go
Fixes the notification template href issue where the href fails to appear on emails sent by the staging environment. 
Jira: https://issues.redhat.com/browse/CRT-836
=> updating templates to remove href

deploy/templates/nstemplatetiers/advanced/cluster.yaml, deploy/templates/nstemplatetiers/advanced/ns_dev.yaml, deploy/templates/nstemplatetiers/advanced/ns_stage.yaml, deploy/templates/nstemplatetiers/basic/cluster.yaml, deploy/templates/nstemplatetiers/basic/ns_dev.yaml, deploy/templates/nstemplatetiers/basic/ns_stage.yaml, deploy/templates/nstemplatetiers/basicdeactivationdisabled/cluster.yaml, deploy/templates/nstemplatetiers/basicdeactivationdisabled/ns_dev.yaml, deploy/templates/nstemplatetiers/basicdeactivationdisabled/ns_stage.yaml, deploy/templates/nstemplatetiers/team/cluster.yaml, deploy/templates/nstemplatetiers/team/ns_dev.yaml, deploy/templates/nstemplatetiers/team/ns_stage.yaml, pkg/templates/nstemplatetiers/nstemplatetier_generator_whitebox_test.go
After long discussion with Ilya and OpenShift folks we decided to increase user's CPU limit to 10 cores.
I'm also increasing the default CPU limit for -dev and -stage namespaces accordingly.
We can adjust the limits later.
e2e tests: https://github.com/codeready-toolchain/toolchain-e2e/pull/210
=> Increase CPU limit to 10 cores

deploy/olm-catalog/toolchain-host-operator/manifests/toolchain-host-operator.clusterserviceversion.yaml, deploy/operator.yaml, deploy/registration-service/registration-service.yaml, hack/deploy_csv.yaml
Same as here: https://github.com/codeready-toolchain/member-operator/pull/225
This PR also adds cpu/memory requests to the reg-service which we can adjust later.
=> Drop cpu/memory limits for host operator & add requests for reg-service

pkg/controller/toolchainstatus/toolchainstatus_controller.go, pkg/controller/toolchainstatus/toolchainstatus_controller_test.go
Fixes https://issues.redhat.com/browse/CRT-881
=> Use unique names for ToolchainStatus notifications

pkg/controller/deactivation/deactivation_controller.go, pkg/controller/deactivation/predicate.go
A problem was discovered where the deactivation controller was not being reconciled on a pod restart in some situations eg. Pod killed or scaling the deployment down and then back up. However, when using `make dev-deploy-e2e-local` the logs show that the deactivation controller was being reconciled.
In the cases where the reconcile was not happening, the deactivation controller receives a Create event which was being filtered out by the `OnlyUpdateWhenGenerationNotChanged` predicate but in the cases where the reconcile was happening Update events were received.
We want the deactivation controller to reconcile when the host-operator is restarted for any reason so we're introducing a new predicate that will reconcile on any Create or Update event.
=> Change deactivation controller predicate

deploy/env/e2e-tests.yaml, deploy/env/prod.yaml, deploy/registration-service/registration-service.yaml
We can't keep it in env/prod.yaml because we need to use different numbers in prod and stage. So, let's keep it in the host operator secret as we do for the rest of twilio configuration.
The secret is already setup correctly: https://github.com/codeready-toolchain/sandbox-sre/blob/7e5a36466d2b5be02b6067834d5f9eb31e5e11a1/config/sandbox.x8i5.p1.openshiftapps.com/host/operator_secret.yaml#L18
We just need to drop the reg-service env var from the deployment and start loading it from the secret.
Also see https://github.com/codeready-toolchain/registration-service/pull/152
Will fail until https://github.com/codeready-toolchain/registration-service/pull/152 and https://github.com/codeready-toolchain/toolchain-e2e/pull/213 are merged.
=> Move twilio phone number to secret

go.mod, go.sum, pkg/controller/registrationservice/registrationservice_controller.go, pkg/controller/registrationservice/registrationservice_controller_test.go
currently, there are issues with setting the correct status of `RegistrationService` CR - maybe, our check, if the resource was updated or not, doesn't work in the very same way as the k8s check (for the generation number). As a result, we can wait for a reconciliation that will not come.
As a solution, the controller will create/update all resources at once - if it seems that any resource was updated/created, then it adds the information into the message and sets to re-queue after 1 second (just as a safety in case it wouldn't be reconciled by the change)
=> fix: deploy all reg-service resources at once

cmd/manager/main.go, go.mod, go.sum, pkg/controller/deactivation/deactivation_controller.go, pkg/controller/hostoperatorconfig/cache_test.go, pkg/controller/masteruserrecord/sync.go, pkg/controller/registrationservice/registrationservice_controller_test.go, pkg/controller/toolchainstatus/toolchainstatus_controller.go, pkg/controller/toolchainstatus/toolchainstatus_controller_test.go, pkg/controller/usersignup/predicate.go, pkg/controller/usersignup/unapproved/cache.go, pkg/templates/nstemplatetiers/nstemplatetier_generator_whitebox_test.go
by default, this function wants to use all out CRDs, but when we have a "host-only"
cluster, this metrics server fails to load the CRDs from etcd, which causes CrashLoops.
If we really need this metrics server, then we should taylor the list of CRDs to expose.
Keeping the `serveCRMetrics` for now, but with a comment to avoid linter issue,
since it's not used.
Also, address pending lint issues with fixes or comments
=> disable CR metrics

go.mod, go.sum, pkg/controller/toolchainstatus/toolchainstatus_controller.go, pkg/controller/toolchainstatus/toolchainstatus_controller_test.go
fix: https://issues.redhat.com/browse/CRT-886
keep member status list empty when no member ToolchainCluster CR is present in the host cluster
=> fix: keep member status list empty when no ToolchainCluster CR is present

pkg/controller/toolchainstatus/toolchainstatus_controller.go, pkg/controller/toolchainstatus/toolchainstatus_controller_test.go
I see in the logs that the toolchainstatus controller calls `//api/v1/health` instead of `/api/v1/health`. This PR fixes it.
=> Remove double // in reg-service health enpdoint URL

pkg/controller/masteruserrecord/masteruserrecord_controller.go, pkg/controller/masteruserrecord/masteruserrecord_controller_test.go
Fix for https://issues.redhat.com/browse/CRT-892
The MasterUserRecord was being deleted even if there was a failure deleting the related UserAccount(s). This change updates the logic related to deleting user accounts to verify the deletion is completed before continuing with the MasterUserRecord deletion.
With the change the MasterUserRecord would not be deleted and would propagate the error correctly.
eg.
```
status:
conditions:
- lastTransitionTime: "2020-12-11T01:36:17Z"
message: waiting for UserAccount deletion
reason: UnableToDeleteUserAccounts
status: "False"
type: Ready
```
Related e2e PR to make tests pass:
https://github.com/codeready-toolchain/toolchain-e2e/pull/218
=> Wait for UserAccount to be deleted before deleting MUR

deploy/templates/nstemplatetiers/advanced/ns_code.yaml, deploy/templates/nstemplatetiers/advanced/ns_dev.yaml, deploy/templates/nstemplatetiers/advanced/ns_stage.yaml, deploy/templates/nstemplatetiers/basic/ns_code.yaml, deploy/templates/nstemplatetiers/basic/ns_dev.yaml, deploy/templates/nstemplatetiers/basic/ns_stage.yaml, deploy/templates/nstemplatetiers/basicdeactivationdisabled/ns_code.yaml, deploy/templates/nstemplatetiers/basicdeactivationdisabled/ns_dev.yaml, deploy/templates/nstemplatetiers/basicdeactivationdisabled/ns_stage.yaml, deploy/templates/nstemplatetiers/team/ns_dev.yaml, deploy/templates/nstemplatetiers/team/ns_stage.yaml, pkg/templates/nstemplatetiers/nstemplatetier_generator_whitebox_test.go, test/templates/nstemplatetiers/advanced/ns_code.yaml, test/templates/nstemplatetiers/advanced/ns_dev.yaml, test/templates/nstemplatetiers/advanced/ns_stage.yaml, test/templates/nstemplatetiers/basic/ns_code.yaml, test/templates/nstemplatetiers/basic/ns_dev.yaml, test/templates/nstemplatetiers/basic/ns_stage.yaml, test/templates/nstemplatetiers/nocluster/ns_code.yaml, test/templates/nstemplatetiers/nocluster/ns_dev.yaml, test/templates/nstemplatetiers/nocluster/ns_stage.yaml, test/templates/nstemplatetiers/team/ns_dev.yaml, test/templates/nstemplatetiers/team/ns_stage.yaml
Adds network policies that allow connections between all namespaces belonging to a user but not from other user's namespaces.
- Adds a new `name` label for each user namespace that will be used for the network selector in the NetworkPolicy
- Adds a NetworkPolicy for each of the user namespaces to allow connections from each of the other namespaces belonging to the same user
Note: I manually verified connectivity between each of the namespace types and also verified other namespaces cannot access the user's namespace.
e2e tests: https://github.com/codeready-toolchain/toolchain-e2e/pull/222
Related issue: https://issues.redhat.com/browse/CRT-819
=> User namespace networking

pkg/configuration/configuration.go, pkg/configuration/configuration_test.go, pkg/controller/usersignup/usersignup_controller_test.go
prevent from creating `redhat` & `default` prefixes
```
Customer workloads should be placed in customer namespaces, and should not match this regular expression: (^kube.*|^openshift.*|^default$|^redhat.*)
```
I know that the `default` is not a prefix, but it's easier to implement and doesn't hurt us :-) 
paired with: https://github.com/codeready-toolchain/toolchain-e2e/pull/223
=> fix: prevent redhat and default prefixes

pkg/controller/usersignup/masteruserrecord.go, pkg/controller/usersignup/masteruserrecord_test.go, pkg/controller/usersignup/usersignup_controller.go, pkg/controller/usersignup/usersignup_controller_test.go, test/usersignup.go
This PR is step 3 of the changes required for CRT-915.  It populates the UserSignup.Spec.UserID property from the UserSignup.Name, and uses this new property value when creating new MasterUserRecord instances
Fixes https://issues.redhat.com/browse/CRT-915
=> Populate UserSignup.Spec.UserID, and use to create MUR

pkg/configuration/configuration.go, pkg/configuration/configuration_test.go, pkg/controller/masteruserrecord/sync.go, pkg/controller/usersignup/usersignup_controller_test.go
Since we have dedicated admin users with `sandbox-` prefix, we need to prevent from creating such users via provisioning flow.
paired with https://github.com/codeready-toolchain/toolchain-e2e/pull/230
=> chore: prevent from creating sandbox* users

pkg/controller/deactivation/deactivation_controller_test.go, pkg/controller/masteruserrecord/sync.go
fix formatting in `sync.go`
increase the time cushion in the deactivation test - it happened to me that it failed when running the test from that repo but without changing the logic. My PC is maybe just too slow :grimacing:
=> chore: formatting & flaky deactivation test

make/manifests.mk
remove slash at the end of reg-service repo URL so we can use it for ssh clone
=> fix: remove slash at the end of reg-service repo URL

go.mod, go.sum, pkg/controller/deactivation/deactivation_controller.go, pkg/controller/deactivation/deactivation_controller_test.go, pkg/controller/masteruserrecord/masteruserrecord_controller_test.go, pkg/controller/masteruserrecord/sync.go, pkg/controller/usersignup/usersignup_controller.go
This PR removes the temporary code that was required as part of https://issues.redhat.com/browse/CRT-915.  This is a work in progress, and is first waiting upon https://github.com/codeready-toolchain/api/pull/213.
=> Cleanup temporary code

deploy/templates/nstemplatetiers/advanced/ns_stage.yaml, deploy/templates/nstemplatetiers/basic/ns_stage.yaml, deploy/templates/nstemplatetiers/basicdeactivationdisabled/ns_stage.yaml, deploy/templates/nstemplatetiers/test/cluster.yaml, deploy/templates/nstemplatetiers/test/ns_code.yaml, deploy/templates/nstemplatetiers/test/ns_dev.yaml, deploy/templates/nstemplatetiers/test/ns_stage.yaml, deploy/templates/nstemplatetiers/test/tier.yaml, pkg/templates/nstemplatetiers/nstemplatetier_generator_whitebox_test.go
There is a need for the CRW team to test some different namespace settings for user namespaces. See https://issues.redhat.com/browse/CRT-940?focusedCommentId=15762779&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15762779 for details.
But I think it would be useful to have some `test` tier which we could use for such research/tests. Ideally we would want to have some ability to create temporal tiers directly in the cluster but it's not that easy right now.
So, for now let's have a permanent special tier we can use for that. If we need to test something else we just modify this test tier.
We do not care much about detailed unit tests for this tier content besides testing the the tier is present and parseible. Also I don't think we have to include it into our …
=> Introducing Test tier

pkg/controller/toolchainstatus/toolchainstatus_controller.go, pkg/controller/toolchainstatus/toolchainstatus_controller_test.go
- remove the unnecessary `metadata.managedFields` portion
- wrap the unmarshalled YAML into `<div><pre><code>` tags in order
to keep the formatting in the received mails
=> improve ToolchainStatus notifications

pkg/controller/deactivation/deactivation_controller.go, pkg/controller/deactivation/deactivation_controller_test.go, pkg/controller/toolchainstatus/toolchainstatus_controller.go, pkg/controller/usersignup/masteruserrecord.go, pkg/controller/usersignup/usersignup_controller.go, pkg/controller/usersignup/usersignup_controller_test.go, pkg/counter/cache.go, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go, test/counter.go, test/metric.go
remove the wrappers, refactor the init/reset
and update the tests accordingly: ince the `Reset()` func
now resets all metrics including the gauge(s), it's important
to set the initial values after preparing the reconciler and
resetting the metrics
=> refactor metrics

pkg/controller/usersignup/approval.go, pkg/controller/usersignup/approval_test.go
Related Issue: https://issues.redhat.com/browse/CRT-949
While updating the e2e tests for automatic approval to test multiple members, I discovered that the automatic approval was actually allowing 1 more user than the specified limit. For example, if you configure the HostOperatorConfig for a member to have a user limit of 1 then 2 users would be approved to be provisioned on the cluster. This is because in the `hasNotReachedMaxNumberOfUsersThreshold` func `numberOfUserAccounts <= threshold` will cause it to return true if the number of user accounts has reached the specified limit when it should really be returning false.
Also found that the unit test for the case 'two clusters where the first one reaches max number of UserAccounts' was misleading because it was actually hitting the …
=> Member user limit

pkg/controller/toolchainstatus/toolchainstatus_controller_test.go
also, refactor the func to initialize the `cluster.GetMemberClustersFunc`
func by passing the name(s) of the expected member clusters.
=> add tests on toolchain status with multiple members

pkg/configuration/configuration.go, pkg/controller/notification/mailgun_notification_delivery_service.go, pkg/controller/notification/mailgun_notification_delivery_service_test.go, pkg/controller/notification/notification_controller_test.go, pkg/controller/notification/notification_delivery_service_test.go
Repeat PR that adds support for ReplyTo email address, this time without our private Mailgun API key :)
Fixes https://issues.redhat.com/browse/CRT-910
Signed-off-by: sbryzak <sbryzak@gmail.com>
=> Add support for ReplyTo email address when sending notifications

.github/workflows/workflow.yml, make/docker.mk
adds GH Actions workflow that releases a new version of host-operator on every commit to master
depends on codeready-toolchain/toolchain-cicd#22
=> chore: add GH Actions workflow for releasing new operator versions

pkg/configuration/configuration.go, pkg/configuration/configuration_test.go, pkg/controller/usersignup/usersignup_controller.go, pkg/controller/usersignup/usersignup_controller_test.go
In the production cluster, there has been created a new user with cluster-admin privileges - that user has a suffix "admin" and some dedicated admin users have the same suffix as well. So I added a logic & configuration that prevents from creating users with the `admin` suffix.
paired with https://github.com/codeready-toolchain/toolchain-e2e/pull/272
=> feat: prevent from creating users with specific suffixes

pkg/controller/usersignup/usersignup_controller.go, pkg/controller/usersignup/usersignup_controller_test.go
Related issue: https://issues.redhat.com/browse/CRT-985
Updates the automatic approval to use the base tier by default
e2e-tests: https://github.com/codeready-toolchain/toolchain-e2e/pull/277
=> Use the base tier as the default for new approvals

pkg/configuration/configuration.go, pkg/controller/usersignupcleanup/usersignup_cleanup_controller_test.go
deactivated usersignup resources will be retained for a longer
period, so we can keep track of returning users even later
fixes https://issues.redhat.com/browse/CRT-1021
=> update usersignup retention to 180 days

go.mod, go.sum, pkg/controller/deactivation/deactivation_controller.go, pkg/controller/deactivation/deactivation_controller_test.go, pkg/controller/usersignup/usersignup_controller.go, pkg/controller/usersignup/usersignup_controller_test.go, pkg/controller/usersignupcleanup/usersignup_cleanup_controller.go, test/usersignup.go
This PR refactored the host operator to use the `UserSignup.Spec.States` property to record the deactivated state, instead of `UserSignup.Spec.Deactivated`.
Fixes https://issues.redhat.com/browse/CRT-1006
Related toolchain-common PR: https://github.com/codeready-toolchain/toolchain-common/pull/162
Related sandbox-sre PR: https://github.com/codeready-toolchain/sandbox-sre/pull/213
=> Refactored UserSignup to use states for deactivated flag

.github/workflows/ci-build.yml
upgrade underlying GolangCI action to 1.39
Do not use cache and avoid tons of errors such as:
```
Error: /usr/bin/tar: ... : Cannot open: File exists
```
Fixes https://issues.redhat.com/browse/CRT-1109
=> lint: configure GitHub Action

pkg/controller/notification/notification_context.go, pkg/controller/notification/notification_controller.go, pkg/controller/notification/user_notification_context.go
Initial diagnostic code for https://issues.redhat.com/browse/CRT-1104.  This PR will capture additional notification context state in our logs in order to determine cause of delivery errors.
=> Enhance logging for failed notification delivery

pkg/configuration/configuration.go, pkg/controller/usersignupcleanup/usersignup_cleanup_controller_test.go
So we delete deactivated usersignups in 365 days not in 180 days as for now.
=> Increase the default deactivated usersignup retention to 365 days

go.mod, go.sum, pkg/controller/usersignup/status.go, pkg/controller/usersignup/usersignup_controller.go, pkg/controller/usersignup/usersignup_controller_test.go
This PR changes the "Deactivating" reason to "DeactivationInProgress" in order to remove ambiguity between the state where the user is currently in the process of being deactivated, as opposed to the user being within the pre-deactivation period before their account is deactivated.
=> Rename Deactivating reason to DeactivationInProgress

.github/workflows/publish-operator-for-e2e-tests.yml
This is a workflow that will publish bundle of host operator for every PR
This is needed for the migration to operator-sdk 1.8.0
Since it uses `pull_request_target` to be able to access secrets, I need to have it in master branch so it is executed by GH actions
=> chore: add publish-operator-for-e2e-tests worflow

.github/workflows/publish-operator-for-e2e-tests.yml
by default when `pull_request_target` is used, then it uses code from master, but we need to checkout the PR head from forked repo
=> fix: use PR head from fork repo

controllers/usersignupcleanup/usersignup_cleanup_controller.go, controllers/usersignupcleanup/usersignup_cleanup_controller_test.go, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go
when a UserSignup resource is deleted because
the external user failed to pass the phone verification,
the cleanup controller checks if the user initiated an
attempt (and maybe some technical issue occurred)
or not (maybe the user did not want to input her phone number,
for privacy reasons).
This info is found by checking if the `toolchain.dev.openshift.com/verification-code`
annotation has been set or not.
Fixes https://issues.redhat.com/browse/CRT-1064
=> feat: metric to track phone verification failures

.github/workflows/publish-operators-for-e2e-tests.yml
rename & update the publish-operators-for-e2e-tests.yml worflow to the latest working & verified version
=> chore: rename & update publish-operators-for-e2e-tests.yml to the latest

controllers/usersignup/usersignup_controller.go, controllers/usersignup/usersignup_controller_test.go
When UserSignup is being deleted, then (in my opinion) we should not do anything in the reconcile. 
My guess is that the flakiness is caused by reconciliation that creates MUR just after their deletion - this is at least what it looks like from the logs. 
I can be wrong, but still - when the UserSignup is being deleted, we should just exit the reconcile.
I'm open to discussion ;-)
=> fix: skip reconcile when UserSignup is being deleted

controllers/notification/mailgun_notification_delivery_service.go, controllers/notification/notification_controller_test.go, controllers/notification/user_notification_context.go, controllers/notification/user_notification_context_test.go
After much digging through the RFC2822 spec, it seems the simplest fix for countering invalid characters that users insert into their names is to just surround their name with double quotes, making it a `quoted-string` (see https://datatracker.ietf.org/doc/html/rfc2822#section-3.2.5)
Fixes https://issues.redhat.com/browse/CRT-1166
=> Formatted email address to be more RFC2822 compliant

make/manifests.mk
delete obsolete install-current-operator target as the installation was move to the scripts
=> chore: delete obsolete install-current-operator target

controllers/notification/notification_builder.go, controllers/notification/notification_builder_test.go, controllers/notification/notification_controller_test.go
This PR adds validation that enforces the notification recipient to be a valid email address.
e2e tests: https://github.com/codeready-toolchain/toolchain-e2e/pull/375
Fixes https://issues.redhat.com/browse/CRT-1219
=> Add validation for recipient when creating a new NotificationBuilder

deploy/templates/nstemplatetiers/base/ns_dev.yaml, deploy/templates/nstemplatetiers/base/ns_stage.yaml, pkg/templates/nstemplatetiers/nstemplatetier_generator_whitebox_test.go
adds Role & RoleBindings which will grant crtadmins (that in `crtadmin-users-view` group) a view & exec permissions in all users namespaces.
This will still require some additional changes in sandbox-sre repo to create the Group and add specific crtadmin users there.
paired with: https://github.com/codeready-toolchain/toolchain-e2e/pull/381
=> feat: add Role & RoleBindings to grant crtadmins view & exec perms

deploy/templates/nstemplatetiers/baseextendedidling/based_on_tier.yaml, pkg/templates/nstemplatetiers/nstemplatetier_generator_whitebox_test.go
Updates the idler timeout to 144 hrs (518400 seconds)
Related PR: https://github.com/codeready-toolchain/toolchain-e2e/pull/383
=> Change baseextendedidling tier to 144 hrs

controllers/usersignup/masteruserrecord.go, controllers/usersignup/usersignup_controller_test.go, go.mod, go.sum, test/usersignup.go
This PR modifies the UserSignup controller to copy the UserSignup's OriginalSub property value to MasterUserRecord.
Fixes https://issues.redhat.com/browse/CRT-1271
=> Propagate OriginalSub from UserSignup to MasterUserRecord

controllers/changetierrequest/changetierrequest_controller.go, controllers/changetierrequest/changetierrequest_controller_test.go, go.mod, go.sum
Related Issue: https://issues.redhat.com/browse/CRT-1222
Related PRs:
https://github.com/codeready-toolchain/toolchain-common/pull/214
https://github.com/codeready-toolchain/toolchain-e2e/pull/393
Updates the ChangeTierRequest controller to look up the related UserSignup and reset its deactivating state
=> Reset deactivating state when promoting users

config/crd/bases/toolchain.dev.openshift.com_masteruserrecords.yaml, controllers/changetierrequest/changetierrequest_controller.go, controllers/changetierrequest/changetierrequest_controller_test.go, controllers/masteruserrecord/masteruserrecord_controller_test.go, controllers/masteruserrecord/sync_test.go, controllers/templateupdaterequest/templateupdaterequest_controller.go, controllers/templateupdaterequest/templateupdaterequest_controller_test.go, controllers/usersignup/masteruserrecord.go, controllers/usersignup/masteruserrecord_test.go, controllers/usersignup/usersignup_controller_test.go, go.mod, go.sum, test/templateupdaterequest/assertion.go
Apply changes after switching to a pointer for `UserAccount.Spec.NSTemplateSet` 
See also:
- https://github.com/codeready-toolchain/api/pull/263
- https://github.com/codeready-toolchain/toolchain-common/pull/216
Fixes Fixes https://issues.redhat.com/browse/CRT-1305
=> refactor: decouple UserAccounts from NSTemplateSets

config/crd/bases/toolchain.dev.openshift.com_masteruserrecords.yaml, config/manifests/bases/host-operator.clusterserviceversion.yaml, go.mod, go.sum
Just a module update with the new field in `MasterUserRecord.Spec`,
but no change in the business logic.
Applying the same module update on both host-operator and member-operator
so that when the business logic is applied, both operators can use the
new field.
This is a workaround the limitations of e2e test pairing.
See [discussion](https://github.com/codeready-toolchain/host-operator/pull/539#issuecomment-975630203)
=> refactor: add MasterUserRecord.Spec.TierName field (only)

controllers/masteruserrecord/sync_test.go, controllers/toolchainstatus/toolchainstatus_controller_test.go, go.mod, go.sum, main.go, test/cluster.go
This PR brings a code that will be used in the following tasks:
* https://issues.redhat.com/browse/CRT-1310
* https://issues.redhat.com/browse/CRT-1306
It let us watch the member clusters directly. It uses this https://github.com/kubernetes-sigs/controller-runtime/blob/master/designs/move-cluster-specific-code-out-of-manager.md)
related PR: https://github.com/codeready-toolchain/toolchain-common/pull/217
=> feat: watch member clusters directly

config/crd/bases/toolchain.dev.openshift.com_toolchainstatuses.yaml, controllers/toolchainstatus/toolchainstatus_controller.go, controllers/toolchainstatus/toolchainstatus_controller_test.go, go.mod, go.sum, main.go, pkg/apis/apis.go, pkg/templates/registrationservice/template.go, pkg/templates/registrationservice/template_test.go, test/toolchainstatus_assertions.go
This PR:
1. gets Proxy URL from the Proxy route
2. adds the Proxy URL to the ToolchainStatus CR
3. if the proxy route is not found, then it sets the condition as "unavailable"
The URL will be then used by reg-service to show the Proxy URL to AppStudio developers.
Paired with: https://github.com/codeready-toolchain/toolchain-e2e/pull/418
=> feat: add Proxy URL to ToolchainStatus CR

controllers/changetierrequest/changetierrequest_controller_test.go, controllers/space/space_controller.go, controllers/space/space_controller_test.go, go.mod, go.sum, test/space/space.go, test/space/space_assertions.go
also, refactor logic to set status.targetCluster when
updating status conditions, and appy changes in existing tests
(mostly, ensure initial status is correctly set)
See also:
- https://github.com/codeready-toolchain/api/pull/283
- https://github.com/codeready-toolchain/toolchain-e2e/pull/431
Fixes https://issues.redhat.com/browse/CRT-1392
=> feat: retarget space to another member cluster

controllers/templateupdaterequest/templateupdaterequest_controller.go, controllers/templateupdaterequest/templateupdaterequest_controller_test.go, test/templateupdaterequest/templateupdaterequest.go
Related Issue: https://issues.redhat.com/browse/CRT-1315
When TemplateUpdateRequest with Spec.CurrentHash is created, then it will only monitor the associated Space until the “toolchain.dev.openshift.com/<tiername>-tier-hash” label at Space CR is different from the one stored in TemplateUpdateRequest.Spec.CurrentHash. In other words, it will wait until the “toolchain.dev.openshift.com/<tiername>-tier-hash” label has changed. When the label is changed, then the TemplateUpdateRequest controller will wait until the Ready condition in Space CR is true.
=> Template update requests for Spaces

deploy/templates/nstemplatetiers/appstudio/ns_appstudio.yaml
included in the `appstudio` template.
E2E test: https://github.com/codeready-toolchain/toolchain-e2e/pull/433
Fixes https://issues.redhat.com/browse/CRT-1383
=> feat: set space label on appstudio namespace

controllers/spacebindingcleanup/mapper.go, controllers/spacebindingcleanup/mapper_test.go, controllers/spacebindingcleanup/predicate.go, controllers/spacebindingcleanup/predicate_test.go, controllers/spacebindingcleanup/spacebinding_cleanup_controller.go, controllers/spacebindingcleanup/spacebinding_cleanup_controller_test.go, go.mod, go.sum, main.go, test/space/space_assertions.go, test/spacebinding/spacebinding.go, test/spacebinding/spacebinding_assertions.go
Adds SpaceBindingCleanup controller that deletes the SpaceBinding if either the bound MUR or the bound Space was deleted.
There is also:
1. Mapper that maps:
* MUR to SpaceBinding(s) using the label: `toolchain.dev.openshift.com/masteruserrecord == mur.Name`
* Space to SpaceBinding(s) using the label: `toolchain.dev.openshift.com/space == space.Name`
2. Predicate which ignores creation & updates of the Space & MasterUserRecord resources - allowes only deletion and the generic event
paired with: https://github.com/codeready-toolchain/toolchain-e2e/pull/453
=> feat: introduce SpaceBindingCleanup controller

controllers/usersignup/approval.go, controllers/usersignup/approval_test.go, pkg/capacity/manager.go, pkg/capacity/manager_test.go
move capacity management logic to separate package so it can be reused in SpaceCompletion controller
https://issues.redhat.com/browse/CRT-1333
=> refactoring: move capacity management logic to separate package

controllers/nstemplatetier/nstemplatetier_controller.go, controllers/usersignup/usersignup_controller_test.go, pkg/counter/cache.go
revert unneeded changes after gosec linter complains
use `// nolint:gosec` comment instead.
=> chore: revert linter changes

controllers/space/space_controller.go, controllers/space/space_controller_test.go, controllers/spacecompletion/space_completion_controller.go, controllers/spacecompletion/space_completion_controller_test.go, main.go, test/space/space.go
Adds SpaceCompletion controller which will set TierName and TargetCluster if they are not set already.
To choose the correct TargetCluter it uses the same capacity manager as is used for UserSignup
paired with: https://github.com/codeready-toolchain/toolchain-e2e/pull/469
=> feat: introduce SpaceCompletion controller

pkg/capacity/manager.go, pkg/capacity/manager_test.go
By default, choose the target cluster based on capacity in a balanced way, because I got bored by trying to achieve the same thing via modifying the thresholds over and over again.
The capacity manager returns the cluster with the most capacity available there.
=> feat: choose the target cluster based on capacity in a balanced way

deploy/templates/nstemplatetiers/appstudio/cluster.yaml, deploy/templates/nstemplatetiers/base/cluster.yaml
SBO supports 2 API but the quota was only set for one of them.
This PR:
* Adds quotas for the second (SPEC) API
* distributes the overall quota between the two
=> chore: include quota for SBO spec API

controllers/space/mapper.go, controllers/space/mapper_test.go, controllers/space/space_controller.go
currently while watching NSTemplateSet in all member clusters from Space Controller, the event handler used was 'EnqueueRequestForObject' which would set the Namespace as the member-operator's namespace in the reconcile request. This PR updates the watch handler to use a mapper to map the host-operator's namespace in the reconcile request for the watcher.
This was also causing a delay in cleanup - space would take longer than timeout at times to delete and fail. Made minor changes in e2e test to identify the failing object in logs here - https://github.com/codeready-toolchain/toolchain-e2e/pull/489
=> update watch handler to map host namespace in reconcile request 

controllers/spacebindingcleanup/mapper.go
no need to dump a stacktrace in the logs when there is no spacebinding
=> reduce log level when no spacebinding exists

deploy/templates/nstemplatetiers/base/cluster.yaml
Adds two DBaaSTenant cluster-scoped resources for RHODA operator. Both of them contain the `toolchain.dev.openshift.com/optional-resource` annotation to mark them as optional. The content of the annotation doesn't matter as we check only the presence of the annotation.
There won't be any e2e tests because the resources won't be created in e2e environment - RHODA operator is not installed there so it's missing the needed API group.
Depends on: https://github.com/codeready-toolchain/member-operator/pull/345
=> feat: add optional DBaaSTenant resource

deploy/templates/nstemplatetiers/appstudio/ns_appstudio.yaml
Allow users to access results and records stored in tekton-results.
Tekton results: https://github.com/tektoncd/results
Deployed to stage cluster by https://github.com/redhat-appstudio/infra-deployments/pull/136
e2e tests: https://github.com/codeready-toolchain/toolchain-e2e/pull/500
=> Allow to access tekton-results

deploy/templates/nstemplatetiers/appstudio/cluster.yaml, deploy/templates/nstemplatetiers/base/cluster.yaml
It looks like the CR object counts are not supported in 4.10. It was undocumented in 4.9 (see table 7.3 in https://access.redhat.com/documentation/en-us/openshift_container_platform/4.10/html/building_applications/quotas#quotas-resources-managed_quotas-setting-per-project) but worked. It doesn't work in 4.10 anymore.
See https://issues.redhat.com/browse/OHSS-10763 for more details.
E2e tests: https://github.com/codeready-toolchain/toolchain-e2e/pull/506
=> Drop counts for objects defined by CRDs from user quotas

deploy/templates/nstemplatetiers/base/ns_stage.yaml
Since WTO and CRW share the same NetworkPolicy group we have to allow traffic from that group to both -dev and -stage. Otherwise WTO can't connect to the terminal pod in -stage.
e2e tests: https://github.com/codeready-toolchain/toolchain-e2e/pull/509
=> Add WTO NetworkPolicy to -stage

config/crd/bases/toolchain.dev.openshift.com_masteruserrecords.yaml, config/crd/bases/toolchain.dev.openshift.com_socialevents.yaml, controllers/usersignup/masteruserrecord_test.go, deploy/registration-service/registration-service.yaml, go.mod, go.sum
Related issue: https://issues.redhat.com/browse/CRT-1326
Related PR: https://github.com/codeready-toolchain/api/pull/299
Removes the `Banned` and `Deprovisioned` fields from the MUR spec. They were not used.
=> Removed banned & deprovision from MUR spec

config/crd/bases/toolchain.dev.openshift.com_masteruserrecords.yaml, controllers/changetierrequest/changetierrequest_controller_test.go, controllers/masteruserrecord/masteruserrecord_controller_test.go, controllers/masteruserrecord/sync.go, controllers/masteruserrecord/sync_test.go, controllers/usersignup/masteruserrecord.go, controllers/usersignup/masteruserrecord_test.go, controllers/usersignup/usersignup_controller_test.go, go.mod, go.sum
Related PRs:
- https://github.com/codeready-toolchain/api/pull/300
- https://github.com/codeready-toolchain/toolchain-common/pull/249
- https://github.com/codeready-toolchain/toolchain-e2e/pull/533
Summary of changes:
- generated files from api change
- code changes related to removal of `UserAccountSpecEmbedded` from MUR
- removal of migration and test functions related to MUR migration to Spaces (since some of it was dealing with the `UserAccountSpecEmbedded`)
=> Remove UserAccountSpecEmbedded from MUR

deploy/templates/nstemplatetiers/appstudio/ns_appstudio.yaml
Add roles for AppStudio users to create, delete, get, list, watch RegisteredClusters
Paired with https://github.com/codeready-toolchain/toolchain-e2e/pull/544
Signed-off-by: Robin Y Bobbitt <rbobbitt@redhat.com>
=> allow appstudio users to work with registeredclusters

controllers/deactivation/deactivation_controller_test.go, go.mod, go.sum
Related PR: https://github.com/codeready-toolchain/toolchain-common/pull/254
MUR does not need tier hash labels since NSTemplateSet is already handled by Spaces since https://github.com/codeready-toolchain/host-operator/pull/595
=> No need for tier when calling mur Account modifier

deploy/templates/nstemplatetiers/appstudio/spacerole_admin.yaml
Configmaps can be used for switching used tekton bundles.
Paired with https://github.com/codeready-toolchain/toolchain-e2e/pull/564
=> Allow appstudio users create configmaps

controllers/usersignup/usersignup_controller.go, controllers/usersignup/usersignup_controller_test.go
This PR modifies the `EncodeUserIdentifier` function used by the migration process to check if the username ends with any invalid characters, and removes them if so.
Fixes https://issues.redhat.com/browse/CRT-1514
=> Fix encoding of usernames with invalid end chars

controllers/space/space_controller.go, controllers/space/space_controller_test.go, controllers/usersignup/spacebinding.go, controllers/usersignup/usersignup_controller.go
Create SpaceBindings with a name based on the Space name and the MasterUserRecord name, so that if the UserSignupController is called just after a SpaceBinding was created but before it was indexed by Etcd (hence, `client.List` with a label matcher would return no result), then creating another SpaceBinding will fail because it would have the same name as the existing one.
see also https://github.com/codeready-toolchain/toolchain-e2e/pull/561
=> refactor UserSignupController: do not watch SpaceBindings

controllers/usersignup/predicate.go, controllers/usersignup/predicate_test.go, controllers/usersignup/usersignup_controller.go
also, reduce cyclomatic complexity of the 'Reconciler.migrateUserIfNecessary' method
=> refactor: avoid flaky cases during usersignup migration

deploy/templates/notificationtemplates/idlertriggered/notification.html, deploy/templates/notificationtemplates/idlertriggered/subject.txt, pkg/templates/notificationtemplates/notification_generator_test.go
adding namespace name to title of the body does not show up in the email, moving the namespace name to subject.
=> move the namespace name to subject of idler notification

deploy/templates/nstemplatetiers/appstudio/spacerole_admin.yaml
This PR is paired with https://github.com/codeready-toolchain/toolchain-e2e/pull/580
=> Allow appstudio users to  create hacbs APIs

controllers/usersignup/usersignup_controller.go, controllers/usersignup/usersignup_controller_test.go
increment deactivated counter only when a user is really deactivated (originally was approved). Not when a user is in `verificationRequired` state for an extended period of time.
=> fix: increment deactivated only when user is deactivated

controllers/usersignup/usersignup_controller_test.go, go.mod, go.sum
This PR updates the unit tests to create UserSignups with the name equal to the username, instead of the user ID.
Fixes https://issues.redhat.com/browse/CRT-1503
=> Update unit tests to create UserSignup with name equal to username

deploy/templates/nstemplatetiers/appstudio/spacerole_admin.yaml
- Rename of releaselinks to release plans and release plan admissions
Tests are here: codeready-toolchain/toolchain-e2e#591
=> Refactor rbac for release links

deploy/templates/nstemplatetiers/appstudio/ns_appstudio.yaml
needed by AppStudio Proxy to obtain a token for a ServiceAccount
e2e tests: https://github.com/codeready-toolchain/toolchain-e2e/pull/592
=> proxy: grant permissions to create TokenRequest API

config/default/manager_auth_proxy_patch.yaml
no need to be so verbose, which will also make fluentd less verbose
(less non-json messages to drop)
=> reduce log level on kube-rbac-proxy sidecar container

deploy/templates/nstemplatetiers/appstudio/spacerole_admin.yaml
This allows users of the staging cluster to configure their workspace, and interact with rebuilt artifacts.
fixes PLNSRVCE-893
Users of the appstudio staging cluster that want to use the JVM Build Service (https://github.com/redhat-appstudio/jvm-build-service) need permission to modify these objects to be able to do anything meaningful. 
I am not 100% sure how all this works, so let me know if this is not the right place for this.
=> Allow access to some JVM Build Service Objects

deploy/registration-service/registration-service.yaml, deploy/templates/nstemplatetiers/appstudio/spacerole_admin.yaml, deploy/templates/nstemplatetiers/appstudio/spacerole_viewer.yaml
The proxy now uses impersonation so the user SA and its RoleBindings are no longer needed. See https://github.com/codeready-toolchain/registration-service/pull/289
e2e tests: https://github.com/codeready-toolchain/toolchain-e2e/pull/642
=> Remove appstudio user SA

make/manifests.mk
save kustomize build output to temporary file, in order to intercept failures and avoid publishing empty bundles.
See "green job" with failed build example:
https://github.com/codeready-toolchain/member-operator/actions/runs/3749944798/jobs/6369029675#step:9:1296
=> handle kustomize build failure

controllers/spacecompletion/space_completion_controller.go, controllers/spacecompletion/space_completion_controller_test.go, controllers/usersignup/approval.go, controllers/usersignup/approval_test.go, controllers/usersignup/usersignup_controller.go, controllers/usersignup/usersignup_controller_test.go, main.go, pkg/capacity/manager.go, pkg/capacity/manager_test.go
The original implementation didn't work fine because it blindly divided by 50 without reminder, but the result was in most cases the same for both clusters. 
The new approach stores the last member cluster that was used.
* If the reminder is not 0 (there is still some capacity until a multiply of 50 is reached), then it uses the last used member cluster
* otherwise, it compares the clusters and chooses the freest one for the next batch of 50 Spaces
=> fix: provision Spaces in batches by 50

deploy/registration-service/registration-service.yaml
Related Issue: https://issues.redhat.com/browse/CRT-1619
This is in preparation for changes to the registration service that will use [shared informers](https://github.com/kubernetes/client-go/blob/master/tools/cache/shared_informer.go).
Get, List and Watch permissions are required to get the Shared Informers working.
https://github.com/codeready-toolchain/registration-service/blob/master/deploy/registration-service.yaml will be updated to match in an upcoming PR.
=> Additional registration service permissions required for informers

deploy/registration-service/registration-service.yaml
Make initialDelaySeconds 30 seconds for the reg service since startup takes a longer time while waiting for the shared informers cache to sync. Related to https://github.com/codeready-toolchain/registration-service/pull/297
=> Make initialDelaySeconds 30 seconds for reg service

deploy/templates/nstemplatetiers/appstudio/spacerole_admin.yaml
Fixes issue: not able to create spifilecontentrequest on stonesoup stagin
=> fix: resource name should be in plural form

deploy/templates/nstemplatetiers/appstudio/spacerole_admin.yaml
Pipeline serviceAccount is used for running tekton pipelines and users should be able to attach secrets for container and git repositories.
=> appstudio: Allow manage pipeline serviceaccount

deploy/templates/nstemplatetiers/appstudio/ns_appstudio.yaml
Pipeline Service keeps the latest 10 PipelineRuns, so the quota is increased to 12 to allow for 2 PipelineRuns to be created before the pruner makes more space for additional PipelineRuns.
e2e-tests: https://github.com/codeready-toolchain/toolchain-e2e/pull/657
Signed-off-by: Romain Arnaud <rarnaud@redhat.com>
=> Increase PVC quota for AppStudio to 12

deploy/registration-service/registration-service.yaml
Related to https://issues.redhat.com/browse/CRT-1637
Reg service PR with matching deployment yaml: https://github.com/codeready-toolchain/registration-service/pull/300
*Update*
Since populating the informers cache only happens on startup I reverted the changes to the liveness and readiness probes and introduced a startup probe with a higher failureThreshold.
=> Add reg service permissions to watch spaces and add startup probe

deploy/templates/nstemplatetiers/base/ns_dev.yaml, deploy/templates/nstemplatetiers/base/ns_stage.yaml, deploy/templates/nstemplatetiers/base1ns/ns_dev.yaml, deploy/templates/nstemplatetiers/test/ns_dev.yaml
Adding the `modelmesh-enabled: "true"` and `opendatahub.io/dashboard: "true"` labels to all user namespaces across all tiers so that user's namespace is treated as a Data Science Project from a RHODS perspective. This allows users to use the Model Serving feature within RHODS
=> Add RHODS DSP labels to all user namespaces

deploy/templates/nstemplatetiers/appstudio/spacerole_admin.yaml
This PR removes write access to GitOpsDeployment from users of Stonesoup, as the ability to create/modify a GitOpsDeployment would allow the user to bypass per-user security boundaries.
Corresponding test repo PR: https://github.com/codeready-toolchain/toolchain-e2e/pull/669
JIRA: [GITOPSRVCE-427](https://issues.redhat.com/browse/GITOPSRVCE-427)
=> Allow only read access to GitOpsDeployments

controllers/space/space_controller.go
there may be a delay between the creation on the member cluster and the client update on the host cluster, so failing at the second attempt should not raise an error
Fixes https://issues.redhat.com/browse/CRT-1729 
=> refactor: ignore NSTemplateSet creation failure if already exists

deploy/registration-service/registration-service.yaml
replaces https://github.com/codeready-toolchain/host-operator/pull/762
/assign @alexeykazakov
=> PLNSRVCE-1166: add proxyplugins crd to registration-service role

deploy/templates/nstemplatetiers/appstudio/spacerole_admin.yaml
This PR add read RBAC of DT, DTC and DeploymentTargetClass to nstemplatetiers.
Corresponding test repo PR: https://github.com/codeready-toolchain/toolchain-e2e/pull/680
=> feat(HACBS-1969): add read rbac of DT, DTC and DeploymentTargetClass to nstemplatetiers

deploy/templates/nstemplatetiers/appstudio/spacerole_admin.yaml
Add create permission for `SelfSubjectAccessReview` to allow for RBAC checks in UI.
Test repo PR: https://github.com/codeready-toolchain/toolchain-e2e/pull/681
=> Allow create access for SelfSubjectAccessReview

deploy/templates/nstemplatetiers/appstudio/spacerole_admin.yaml
This reverts commit 646e31935cfd485936c6f864b3fd3ecbb5500544.
Access for the resource was not needed.
=> Revert PR #766

deploy/templates/nstemplatetiers/base/cluster.yaml, deploy/templates/nstemplatetiers/base1ns/ns_dev.yaml, deploy/templates/nstemplatetiers/test/ns_dev.yaml
Increasing storage limits to 40Gi for RHODS operator updates.
e2e tests: https://github.com/codeready-toolchain/toolchain-e2e/pull/691
=> Increase storage limit to 40Gi

controllers/spacerequest/spacerequest_controller.go, controllers/spacerequest/spacerequest_controller_test.go, pkg/space/space.go
Provision sub-space to the same member clusters as parent space
Jira: https://issues.redhat.com/browse/ASC-349
Paired with:
- e2e: https://github.com/codeready-toolchain/toolchain-e2e/pull/700
=> Provision sub-space to the same member clusters as parent space

controllers/usersignup/usersignup_controller.go, controllers/usersignup/usersignup_controller_test.go, test/segment/assertions.go
Currently there is mismatch between `userID` field in events sent to segment from web-console and Sandbox backend (host operator).
In our activation event we use the sso username while web-console uses the `User.metadata.name` which is the complaint username.
As a temporal solution we would like to start using the compliant username in the host operator too but unfortunately we don't have it available in the UserSignup when it's approved.
This PR does two things:
- Move the activation event report to the place where we create a MUR CR for the approved UserSignup instead of reporting it when it's approved.
- Start using the compliant username instead of the sso username.
See more details in slack: https://redhat-internal.slack.com/archives/CHK0J6HT6/p1680830236435579
We still need to get …
=> Use compliant username in segment event

deploy/templates/nstemplatetiers/appstudio/spacerole_admin.yaml, deploy/templates/nstemplatetiers/appstudio/spacerole_contributor.yaml, deploy/templates/nstemplatetiers/appstudio/spacerole_maintainer.yaml, test/templates/nstemplatetiers/appstudio/spacerole_admin.yaml, test/templates/nstemplatetiers/appstudio/spacerole_contributor.yaml, test/templates/nstemplatetiers/appstudio/spacerole_maintainer.yaml
Adds readonly access for appstudio users to gitopsdeploymentmanagedenvironments, gitopsdeploymentrepositorycredentials, gitopsdeploymentsyncrun APIs.
Corresponding test PR: https://github.com/codeready-toolchain/toolchain-e2e/pull/693
Corresponding book PR: https://github.com/redhat-appstudio/book/pull/90
=> Add read access to additional Core GitOps APIs

controllers/space/space_controller.go, controllers/space/space_controller_test.go, pkg/counter/cache.go, test/toolchainstatus.go
decrement counter when NSTemplateSet is deleted and not when finalizer is removed, otherwise, we can have wrong values in the counter when space is moved from one member cluster to another
paired PR and also the case when I faced the issue with wrong numbers: https://github.com/codeready-toolchain/toolchain-e2e/pull/707
=> fix: decrement counter when NSTemplateSet is deleted

deploy/templates/nstemplatetiers/appstudio/spacerole_admin.yaml, test/templates/nstemplatetiers/appstudio/spacerole_admin.yaml
For security purposes, only the GitOps Service controllers should be able to create/modify/delete the `GitOpsDeployment*` resources, at this time.
* Note this does not effect the Environment API (Snapshots, Environments, SnapshotEnvironmentBindings, etc).
- *Book*: https://github.com/redhat-appstudio/book/pull/97
- *Toolchain-e2e*: https://github.com/codeready-toolchain/toolchain-e2e/pull/712
=> Remove write access to all GitOpsDeployment* resources, from all roles

deploy/templates/nstemplatetiers/appstudio/spacerole_admin.yaml, deploy/templates/nstemplatetiers/appstudio/spacerole_contributor.yaml, deploy/templates/nstemplatetiers/appstudio/spacerole_maintainer.yaml
since this role was created, the results REST API has been updated such that `logs` is a separate resource
(and yes, it is known that the README in the upstream repo needs to be updated :-) ) 
with this change, the following now works running the latest codeready alongside the latest appstudio pipeline-service (not yet bumped in infra-deployments):
```
gmontero ~ $ curl -k -X GET -H "Authorization: Bearer $BEARER_TOKEN" -H "Accept: application/json"   https://api-toolchain-host-operator.apps.gmontero412.devcluster.openshift.com/plugins/tekton-results/apis/results.tekton.dev/v1alpha2/parents/crt-sandboxtest-1-tenant/results/9244af2e-35eb-4c02-a681-211a38a84413/logs/35f62ea5-49f6-3fae-8c2a-d8bc9000537a | jq -r '.result.data' | base64 -d -
% Total    % Received % Xferd  Average Speed   Time …
```
=> PLNSRVCE-1167: add logs resource to tekton results RBAC

deploy/templates/notificationtemplates/appstudio/userprovisioned/notification.html
On line 56, I replaced the old URL for the docs with the new URL
=> Update docs link in app studio welcome email

deploy/templates/notificationtemplates/appstudio/userprovisioned/notification.html
Our users might be confused, because our documentation has to use "App Studio" right now, not the actual product name. This PR is meant to help with that.
=> Add "community" on line 56

deploy/templates/nstemplatetiers/appstudio-env/ns_env.yaml, deploy/templates/nstemplatetiers/appstudio/ns_tenant.yaml, test/templates/nstemplatetiers/appstudio/ns_tenant.yaml
This PR adds all workspace_name label to all the appstudio namespaces.
Paired with https://github.com/codeready-toolchain/toolchain-e2e/pull/721
=> Added workspace_name label in namespace template

controllers/usersignup/usersignup_controller.go, controllers/usersignup/usersignup_controller_test.go, pkg/metrics/metrics.go
Related Issue: https://issues.redhat.com/browse/CRT-1790
```
sandbox_user_signups_verification_required_total 14
```
e2e tests: https://github.com/codeready-toolchain/toolchain-e2e/pull/734
=> Add UserSignupVerificationRequiredTotal metric

make/go.mk
When building the operator in Github jobs the module path was not correctly populated see: https://github.com/codeready-toolchain/host-operator/actions/runs/5027765267/jobs/9017655116#step:7:61 causing the version and build time to be empty.
Also it's fine to have the org name "hard coded" since the module name is the same when building the operator locally and in Github.
This is prerequisite for monitoring the deployed versions of the sandbox operators.
Jira story: https://issues.redhat.com/browse/SANDBOX-53
=> fix: ldflags commit id and build time in github

controllers/usersignup/usersignup_controller.go, test/segment/assertions.go
Use Annotations[SSOUserIDAnnotationKey] instead of usersignup.Spec.userId to reflect Red Hat SSO ID being sent to segment.
=> use annotations user ID for using SSO User_Id

pkg/segment/segment.go, test/segment/assertions.go
fix wrt: https://issues.redhat.com/browse/SANDBOX-55
Instead of sending the activation to pendo directly from code, add accountId in properties to the data being sent to segment. Since data in context could not be used to send to pendo, moving it to properties is the alternate. This way segment can remain the single source of data, and the data can be relayed from amplitude to pendo via existing field mapping.
=> add accountID in properties as well

pkg/segment/segment.go, test/segment/assertions.go
sending data from Amplitude -> pendo is failing due to incompatible timestamp formats. Thus sending the epoch time as part of properties to segment to propagate the field forward to pendo.
fix wrt: https://issues.redhat.com/browse/SANDBOX-55
=> Send epoch time in segment properties

controllers/spacerequest/spacerequest_controller.go, controllers/spacerequest/spacerequest_controller_test.go
We have added the new `SpaceLabelKey` on the resources provisioned by the nstemplaset controller in https://github.com/codeready-toolchain/member-operator/pull/438
The changes in this PR are for:
- replacing usage of the `OwnerLabelKey` with `SpaceLabelKey`.
Jira story: https://issues.redhat.com/browse/SANDBOX-51
=> fix: replace "owner" label with "space" label ( part 2 )

deploy/templates/nstemplatetiers/appstudio-env/ns_env.yaml, deploy/templates/nstemplatetiers/appstudio/ns_tenant.yaml, go.mod, go.sum, test/templates/nstemplatetiers/appstudio/ns_tenant.yaml
Drop unused `toolchain.dev.openshift.com/workspace` label
Part of Jira: https://issues.redhat.com/browse/SANDBOX-51
=> fix: drop label WorkspaceLabelKey

controllers/toolchainstatus/toolchainstatus_controller.go, controllers/toolchainstatus/toolchainstatus_controller_test.go
This PR's moves the unit test that covers the happy path of the revision check from it's own unit test to the existing one _"All components ready"_. 
Also copying the revisionCheck object so that it doesn't get lost in case an error occurs in the host operator status check prior to the execution of the `CheckDeployedVersionIsUpToDate` function.
=> fix: refactor toolchain status test for revision check and copy revision check object 

controllers/toolchainstatus/toolchainstatus_controller.go, controllers/toolchainstatus/toolchainstatus_controller_test.go, test/toolchainstatus.go
Adding revision check conditions handling to the `ExtractStatusMetadata` function, so that it can be reported in the unready notification email.
=> fix: add revision check component to status metadata for email notification

controllers/toolchainconfig/toolchainconfig_controller.go
see: https://redhat-internal.slack.com/archives/CHK0J6HT6/p1690446745059439
=> fix: remove generation predicate from secrets watcher

deploy/templates/nstemplatetiers/appstudio/spacerole_admin.yaml
See discussion in slack thread: https://redhat-internal.slack.com/archives/C02FANRBZQD/p1692011366722619
For issue https://issues.redhat.com/browse/RHTAPBUGS-595
ADR change: https://github.com/redhat-appstudio/book/pull/129
toolchain-e2e change: https://github.com/codeready-toolchain/toolchain-e2e/pull/780
=> adds deletecollection verb to components and applications

deploy/templates/nstemplatetiers/appstudio/ns_tenant.yaml
* Snapshots are high-traffic CRs that are created for each version of the application
* The limit of 512 has been too low in practice
See https://github.com/codeready-toolchain/toolchain-e2e/pull/781
=> fix(RHTAPBUGS-587): increase ResourceQuota for Snapshots

deploy/templates/nstemplatetiers/appstudio/spacerole_admin.yaml
When a cluster admin inspects a namespace, it would be helpful if the names of the roles and rolebindings consistently reflected their level.
Both the contributor and maintainer roles and rolebindings indicate their level in their names (contributor and maintainer respectively).
Here, do the same with admin for parity.
=> Update admin spacerole role and rolebinding to indicate level

deploy/templates/nstemplatetiers/appstudio/spacerole_admin.yaml
See https://github.com/redhat-appstudio/book/pull/124
Paired with https://github.com/codeready-toolchain/toolchain-e2e/pull/783
=> Let appstudio admins exec (rsh) to pods

controllers/spacebindingrequest/spacebindingrequest_controller.go, controllers/spacebindingrequest/spacebindingrequest_controller_test.go, controllers/spacerequest/spacerequest_controller.go, controllers/spacerequest/spacerequest_controller_test.go, pkg/cluster/cluster.go
- address comment from https://github.com/codeready-toolchain/host-operator/pull/848#discussion_r1294048180 
- extract the member lookup logic to function that is now reused in both spacerequest and sapacebindingrequest controllers.
=> refactor: introduce LookupMember cluster function

controllers/spacerequest/spacerequest_controller.go, controllers/spacerequest/spacerequest_controller_test.go
SpaceRequest improvement: right now when there is an issue in the Secret creation for the generated namespace the status of the SpaceRequest remains in `Provisioning` with no error message.
This PR sets the status of the SpaceRequest to `UnableToProvision` and adds the error message to the Message field of the condition.
=> bugfix: spacerequest set status unable to provision when there is an issue with secret creation

deploy/templates/nstemplatetiers/appstudio/spacerole_admin.yaml
grant CRUD permissions to Space admins in appstudio tier.
Jira: https://issues.redhat.com/browse/ASC-412
Paired with:  https://github.com/codeready-toolchain/toolchain-e2e/pull/789
=> feat: grant edit permissions over SBRs to RHTAP admis

deploy/templates/nstemplatetiers/appstudio/ns_tenant.yaml
During efforts to onboard product components to RHTAP, the PVC resource utilization limit has resulted in regular PipelineRun failures.
This is a brute-force attempt to address the problem in the near term to satisfy onboarding needs, while allowing time to consider alternative solutions.
Paired e2e tests PR: https://github.com/codeready-toolchain/toolchain-e2e/pull/794
=> resources: increase the PVC claim limit to 30

controllers/usersignup/usersignup_controller.go, controllers/usersignup/usersignup_controller_test.go
https://issues.redhat.com/browse/SANDBOX-369
This should help us to workaround the issue when users cannot reactivate because of having Space stuck in a terminating state https://redhat-internal.slack.com/archives/CHK0J6HT6/p1695253339361769
paired with: https://github.com/codeready-toolchain/toolchain-e2e/pull/798
=> fix: check conflicts with Space name for complaintUsername

controllers/usersignup/status_updater.go, controllers/usersignup/status_updater_test.go, controllers/usersignup/usersignup_controller.go
1. Forwards the Reconcile's context to called requiring functions
3. Retrieve the logger from context instead of passing it to each function
4. Removes a `//nolint: unparam` comment in `controllers/usersignup/status_updater.go`.
=> fix: forward context in UserSignup controller

controllers/toolchainstatus/toolchainstatus_controller.go, controllers/toolchainstatus/toolchainstatus_controller_test.go
Updating the notifications about toolchain status content to contain the source as well. 
Reference: https://issues.redhat.com/browse/SANDBOX-202
=> SANDBOX-202: Differentiation between notification emails from different environments

.github/workflows/ci-build.yml, .github/workflows/ci-check-gomod.yml, .github/workflows/operator-cd.yml, .github/workflows/publish-operators-for-e2e-tests.yml
As of [June 2023][1], GitHub no longer uses node v12 within its actions runner with the intention of removing support for this version in the future.  They have been encouraging action authors to switch to node v16 and [encouraging users][2] to use the new versions of the actions when they become available.
Bump the versions of the affected actions to bring this in line.
[1]: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
[2]: https://github.com/codeready-toolchain/host-operator/actions/runs/6421632076
=> ci: bump actions to silence node12 warnings

controllers/usersignup/usersignup_controller.go, controllers/usersignup/usersignup_controller_test.go
If we mark user signups as incomplete while a space is updating, then the registration controller will reject the login.  As a workaround, allow user signups to progress while the associated space is updating.
Resolves https://issues.redhat.com/browse/SANDBOX-72.
=> Allow user signups to complete when the associated space is updating

controllers/toolchainstatus/toolchainstatus_controller.go, controllers/toolchainstatus/toolchainstatus_controller_test.go
While preparing the toolchain notification,we should use  only the cluster domain not containing route prefix of the proxy.
For example current notification is `ToolchainStatus has been in an unready status for an extended period for api-toolchain-host-operator.apps.stone-stg-host.qc0p.p1.openshiftapps.com`.
Can be optimized to `ToolchainStatus has been in an unready status for an extended period for stone-stg-host.qc0p.p1.openshiftapps.com`
=> update notification just containing cluster domain name

controllers/usersignupcleanup/usersignup_cleanup_controller.go, controllers/usersignupcleanup/usersignup_cleanup_controller_test.go
It turned out that our UserSignup cleanup controller tries to delete the same UserSignup twice. As the result we increment our abandoned signup count twice per each deleted signup. I guess it's because we do not check if the resource is already being deleted and try to delete it again.
=> Do not try to delete UserSignups multiple times

controllers/masteruserrecord/mapper.go, controllers/masteruserrecord/mapper_test.go, controllers/masteruserrecord/masteruserrecord_controller.go, controllers/masteruserrecord/masteruserrecord_controller_test.go, controllers/masteruserrecord/sync.go, controllers/masteruserrecord/sync_test.go, controllers/usersignup/masteruserrecord.go, controllers/usersignup/masteruserrecord_test.go, go.mod, go.sum, test/spacebinding/spacebinding.go
The PR changes the way how MasterUserRecord decides where it should create UserAccount(s). It doesn't use the UserAccounts embedded in MasterUserRecord.Spec anymore (and thus the targetCluster neither).
Instead of it, it loads all Spaces it has access to (via SpaceBindings) and picks the first one that was created on the behalf of the MUR's UserSignup CR (that is given by the "creator" label). Such a Space corresponds to the default "home" Space that is provisioned automatically by the UserSignup controller when it's approved and being provisioned.
Although the code is ready to provision UserAccounts in multiple members, it still does that only for one single member cluster (account). The reason is that we need to make sure that all other components like registration-service and proxy are …
=> dynamically load targetCluster from Space

.codecov.yaml
Setting threshold to 1% for codecov.
Config can be validated before merging: curl -X POST --data-binary @.codecov.yaml https://codecov.io/validate
=> Add threshold in codecov settings

config/crd/bases/toolchain.dev.openshift.com_nstemplatetiers.yaml, deploy/registration-service/registration-service.yaml
This PR aims at modifying the NSTemplateTier CRD so as to support functionality of copy SA token or not.
See https://github.com/codeready-toolchain/api/pull/380
=> ASC-402: Modify NSTemplateTierSpec to support SA token copy

config/crd/bases/toolchain.dev.openshift.com_nstemplatetiers.yaml, deploy/registration-service/registration-service.yaml
having same labels for the 2 services may confuse Prometheus, thus renaming the label for metrics Service.
Also naming the port 8082 for metrics.
related PR: https://github.com/codeready-toolchain/registration-service/pull/363
=> rename metrics label

controllers/spacebindingrequest/spacebindingrequest_controller.go, controllers/spacebindingrequest/spacebindingrequest_controller_test.go
The `SpaceBindingRequest.Spec.MasterUserRecord` field cannot be updated once the SBR resoruce is created.
There is a validating webhook that prevents it: https://github.com/codeready-toolchain/member-operator/blob/a142fe458cc9e13ceaef136211c42a0ca5e4b975/deploy/webhook/member-operator-webhook.yaml#L231-L235
we can remove this code since it should never trigger this update. 
Jira: https://issues.redhat.com/browse/ASC-435
=> fix: remove unsupported MUR update from SBR controller 

config/crd/bases/toolchain.dev.openshift.com_usersignups.yaml
This field is going to be used by the proxy when no workspace context is provided.
API PR: https://github.com/codeready-toolchain/api/pull/384
Ref. https://issues.redhat.com/browse/SANDBOX-425
=> Add HomeSpace status field

controllers/spacecompletion/space_completion_controller.go, controllers/usersignup/usersignup_controller.go, main.go, pkg/pending/cache.go, pkg/pending/cache_test.go, pkg/pending/mapper.go, pkg/pending/mapper_test.go
Changes in `main.go` conflicts with changes applied by #916.
Some changes introduced here can be reverted after upgrading [controller-runtime](https://github.com/kubernetes-sigs/controller-runtime) to [v0.15.0](https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.15.0) or higher. More precisely it will be possible to apply the following actions: 
* `pkg/pending/mapper.go#BuildMapToOldestPending` can be removed
* context can be removed from `controllers/spacecompletion/space_completion_controller.go#SetupWithManager` 
* context can be removed from `controllers/usersignup/usersignup_controller.go#SetupWithManager`
=> fix: forward context in pkg/pending

config/crd/bases/toolchain.dev.openshift.com_spacerequests.yaml, config/crd/bases/toolchain.dev.openshift.com_spaces.yaml
For api change in  https://github.com/codeready-toolchain/api/pull/386
=> add disable inheritance api

controllers/usersignup/usersignup_controller.go, controllers/usersignup/usersignup_controller_test.go
Migrates remaining users using their existing property values to populate `UserSignup.Spec.IdentityClaims`.
Fixes https://issues.redhat.com/browse/SANDBOX-463
e2e test: https://github.com/codeready-toolchain/toolchain-e2e/pull/838
=> Added migration code to populate unmigrated identity claims

controllers/spacebindingrequest/spacebindingrequest_controller.go, controllers/spacebindingrequest/spacebindingrequest_controller_test.go
This fixes the issue with SpaceBindingRequest not being deleted when there is already an existing SpaceBinding object not owned by the SBR resource.
Jira: https://issues.redhat.com/browse/ASC-442
=> bugfix(spacebindingrequest): allow deletion of failed SpaceBindingRequest

controllers/usersignup/usersignup_controller.go, controllers/usersignup/usersignup_controller_test.go
This PR reintroduces the migration code that was removed in the following commit, in order to fix UserSignups that are currently in a broken state due to an older version of sandbox-cli erasing the IdentityClaim/PropagatedClaim property values.
https://github.com/codeready-toolchain/host-operator/commit/0c57eb06dbf48742ddf2278c5135311dafceff34
=> Reintroduce migration to fix broken UserSignups

config/manifests/bases/host-operator.clusterserviceversion.yaml, controllers/spaceprovisionerconfig/mapper.go, controllers/spaceprovisionerconfig/mapper_test.go, controllers/spaceprovisionerconfig/spaceprovisionerconfig_controller.go, controllers/spaceprovisionerconfig/spaceprovisionerconfig_controller_test.go, go.mod, go.sum, main.go
This only checks validity of the CR but doesn't integrate it into the space provisioning flow in any way.
Issue link: https://issues.redhat.com/browse/KSPACE-28
Associated toolchain-e2e PR: https://github.com/codeready-toolchain/toolchain-e2e/pull/883
Associated toolchain-common PR: https://github.com/codeready-toolchain/toolchain-common/pull/357
=> KSPACE-28: Implement the basic version of the SpaceProvisionerConfig controller.

deploy/templates/notificationtemplates/sandbox/idlertriggered/notification.html, deploy/templates/notificationtemplates/sandbox/idlertriggered/subject.txt, pkg/templates/notificationtemplates/notification_generator_test.go
This way the template can be reused when VMs are idled too.
https://issues.redhat.com/browse/SANDBOX-513
=> Make the idler template generic

deploy/templates/nstemplatetiers/appstudio/ns_tenant.yaml
Openshift will inject the CA bundle to the configmap. The configmap will be available in every tenant namespace, so tenant's pipelines would able to reach services that use private pki.
https://docs.openshift.com/container-platform/4.14/networking/configuring-a-custom-pki.html#nw-proxy-configure-object_configuring-a-custom-pki
=> RHTAPSRE-439: Deploy CA bundle configmap

controllers/masteruserrecord/masteruserrecord_controller_test.go, controllers/masteruserrecord/sync_test.go, controllers/space/space_controller_test.go, controllers/spacebindingcleanup/spacebinding_cleanup_controller_test.go, controllers/spacebindingrequest/spacebindingrequest_controller_test.go, controllers/spacerequest/spacerequest_controller_test.go, controllers/toolchainstatus/toolchainstatus_controller_test.go, go.mod, go.sum, main.go, test/cluster.go
This is related to Drop the distinction between host & member ToolchainClusters
Related PRs:
ToolchainCommon- https://github.com/codeready-toolchain/toolchain-common/pull/359
Member-Operator - https://github.com/codeready-toolchain/member-operator/pull/531
Registration-Service - https://github.com/codeready-toolchain/registration-service/pull/402
Toolchain-e2e - https://github.com/codeready-toolchain/toolchain-e2e/pull/893
Sandbox-sre - https://github.com/codeready-toolchain/sandbox-sre/pull/1524
=> KSPACE-20: Drop the distinction between host & member ToolchainClusters

deploy/templates/nstemplatetiers/appstudio/cluster.yaml
Even though this quota is named `for-<some-tenant>-deployments` implying that it only affects deployments, this is not the case and it does block the build. This quota cap the number of pods in a namespace, including the completed ones.
Not only the build tasks can no longer start, it looks like this does block some kind of pod cleanup because as soon as I increased the quota, not only builds started but overall number of pods started to go down after slightly increasing over 300.
PipelineRun usually have about 10 tasks or more so 300 pods, not counting deployments, allows maximum 30 PipelineRun which is too low. The pod counts includes the completed ones so since PipelineRun are not deleted right after completion, we need to increase that quota to not end up in this situation all the …
=> Increase appstudio pods quota

.github/workflows/ci-check-gomod.yml
Use `go list -m all` to get us the full machine-readable list of modules instead of manually parsing go.mod using grep to correctly check forbidden replacements in the go.mod.
=> Use `go list` in the go.mod replacements check to improve reliability

deploy/templates/nstemplatetiers/appstudio/ns_tenant.yaml
Most of on boarded teams did hit this quota which I change manually to 90 in all the cases and it has been working so far. Do the change in the default tier otherwise we would need to promote every team to appstudiolarge tier.
=> Increase appstudio tier pvc quota

controllers/masteruserrecord/masteruserrecord_controller_test.go, controllers/masteruserrecord/sync_test.go, controllers/notification/notification_controller_test.go, controllers/spacerequest/space_spacerequest_mapper_test.go, controllers/spacerequest/spacerequest_controller_test.go, controllers/toolchainconfig/toolchainconfig_controller_test.go, pkg/space/space_test.go, test/counter.go, test/spacebinding/spacebinding.go
This PR cleans up the packages being imported more than once.
=> cleanup packages being imported more than once

deploy/templates/nstemplatetiers/base/cluster.yaml, deploy/templates/nstemplatetiers/base1ns/cluster.yaml, deploy/templates/nstemplatetiers/test/cluster.yaml
https://issues.redhat.com/browse/SANDBOX-557
=> Add vms to quotas

go.mod, go.sum, main.go
This is to Rename the ToolchainCluster controller to ToolchainCluster_cache controller
PRs in other related repos:
Toolchain Common - https://github.com/codeready-toolchain/toolchain-common/pull/378
Member-Operator - https://github.com/codeready-toolchain/member-operator/pull/550
Other repo PRs where the only change is to update the go.mod dependency
Registration-Service - https://github.com/codeready-toolchain/registration-service/pull/418
Toolchain-e2e - https://github.com/codeready-toolchain/toolchain-e2e/pull/932
Sandbox-sre - https://github.com/codeready-toolchain/sandbox-sre/pull/1633
=> KUBESAW-10: Rename the ToolchainCluster controller to ToolchainCluster_cache controller

deploy/templates/nstemplatetiers/appstudio/cluster.yaml, deploy/templates/nstemplatetiers/appstudio/ns_tenant.yaml, deploy/templates/nstemplatetiers/appstudiolarge/based_on_tier.yaml
Change the default appstudio tier to parametrize all the compute-build values(cpu request/limit) and increase the large tier compute-build quotas. The numbers are quite high but one typical build-container task/pod have a limits of 20GiB and 18 cpus.
Also increase the secret quota for both tiers
[KFLUXINFRA-508](https://issues.redhat.com//browse/KFLUXINFRA-508)
=> Increase appstudiolarge tier quotas

deploy/templates/nstemplatetiers/appstudio/ns_tenant.yaml, deploy/templates/nstemplatetiers/appstudiolarge/based_on_tier.yaml
[KFLUXBUGS-1235](https://issues.redhat.com//browse/KFLUXBUGS-1235)
=> Increase Konflux large tier pvc to 180

config/crd/bases/toolchain.dev.openshift.com_toolchainconfigs.yaml
Implements: [ASC-444](https://issues.redhat.com//browse/ASC-444)
CRD change generated by api `make generate` call.
=> Adding domains field to auto-approval config

controllers/usersignup/usersignup_controller_test.go
JIRA: https://issues.redhat.com/browse/ASC-531
As 'kube' is already a forbidden prefix, there is no need of explicitly add 'kubesaw'.
Adding it in test to prevent future changes to break this behavior.
=> add test for 'kubesaw' prefix

config/crd/bases/toolchain.dev.openshift.com_toolchainclusters.yaml, config/crd/bases/toolchain.dev.openshift.com_toolchainstatuses.yaml
This is related to https://github.com/codeready-toolchain/host-operator/pull/1017#issuecomment-2082716929 . Making the `LastProbeTime` optional first
=> KUBESAW-43: Make LastProbeTime optional

deploy/templates/nstemplatetiers/appstudio/spacerole_admin.yaml
This change adds a Role and RoleBinding to the tenant use to CRUD on SecretStore and ExternalSecret CRs provided by external-secrets.io
This is meant for testing if this can enable tenants to create SecretStore and ExternalSecret from their own self-hosted or managed secrets backend 
Paired PR in `codeready-toolchain/toolchain-e2e` - https://github.com/codeready-toolchain/toolchain-e2e/pull/982
=> Role and RoleBinding for SecretStore and ExternalSecret CRs

deploy/templates/nstemplatetiers/appstudio/spacerole_admin.yaml, deploy/templates/nstemplatetiers/appstudio/spacerole_contributor.yaml, deploy/templates/nstemplatetiers/appstudio/spacerole_maintainer.yaml
Since we are switching to the new way of managing image repositories in Konflux via a separate `ImageRepositopry` resource instead of `Component` annotations, we need to grant users permissions to work with the new resource. `ImageRepositopry` should be created together with the `Component` (by UI) in case user wants to use default image repository option.
The permissions are set in sync with the `Component` permissions of each role.
[STONEBLD-2473](https://issues.redhat.com/browse/STONEBLD-2473)
=> Allow users to manage ImageRepository objects with the same access level as Components

config/crd/bases/toolchain.dev.openshift.com_toolchainclusters.yaml, config/crd/bases/toolchain.dev.openshift.com_toolchainstatuses.yaml, controllers/toolchainstatus/toolchainstatus_controller_test.go, go.mod, go.sum, test/cluster.go
This is to replace the special ToolchainClusterCondition with the standard toolchain Condition
This is Related to Change in
- API - https://github.com/codeready-toolchain/api/pull/416
- Toolchain-Common - https://github.com/codeready-toolchain/toolchain-common/pull/391
- Member-Operator - https://github.com/codeready-toolchain/member-operator/pull/560
- Toolchain-E2E - https://github.com/codeready-toolchain/toolchain-e2e/pull/955
- KSCTL - https://github.com/kubesaw/ksctl/pull/38
Only change is updating the dependency of API and toolchain-common
- Registration-Service - https://github.com/codeready-toolchain/registration-service/pull/424
- Sandbox-SRE - https://github.com/codeready-toolchain/sandbox-sre/pull/1706
=> KUBESAW-43: Replace the special ToolchainClusterCondition with the standard toolchain Condition

deploy/templates/nstemplatetiers/appstudio/spacerole_admin.yaml
Intended role was not applied properly due to including version in apiGroups.
Removing the same as part of this PR
Paired PR - https://github.com/codeready-toolchain/toolchain-e2e/pull/988
=> Remove version from apiGroups

go.mod, go.sum
Upgrade to toolchain-common with ToolchainController that no longer migrates the secrets to be labeled.  Ths is now assumed.
This brings in PR https://github.com/codeready-toolchain/toolchain-common/pull/400.
Related PRs:
- member-operator: https://github.com/codeready-toolchain/member-operator/pull/575
=> Upgrade to the latest toolchain-common

deploy/templates/nstemplatetiers/appstudio/ns_tenant.yaml, deploy/templates/nstemplatetiers/appstudiolarge/based_on_tier.yaml
appstudio:
* Parametrize request storage, keep same value of 200Gi
* Set build CPU request to half of limit, i.e. 60.
appstudiolarge:
* Set request storage to double of appstudio tier, i.e. 400Gi.
* Set build CPU request to half of limit, i.e. 240.
* Set build memory request to half of limit, i.e. 256Gi.
[KFLUXINFRA-632](https://issues.redhat.com//browse/KFLUXINFRA-632)
=> Increase quotas in appstudio and appstudiolarge

config/crd/bases/toolchain.dev.openshift.com_toolchainconfigs.yaml
Generated for https://github.com/codeready-toolchain/api/pull/429
=> CRDs for feature toggles API

deploy/templates/nstemplatetiers/base/cluster.yaml, deploy/templates/nstemplatetiers/base1ns/cluster.yaml
So users can't create services with type `LoadBalancer` which triggers creating a LB
Paired with https://github.com/codeready-toolchain/toolchain-e2e/pull/1004
=> Forbid creating loadbalancer services

controllers/usersignupcleanup/usersignup_cleanup_controller.go, controllers/usersignupcleanup/usersignup_cleanup_controller_test.go
The UserSignupDeletedWithInitiatingVerificationTotal and UserSignupDeletedWithoutInitiatingVerificationTotal metrics are meant for tracking signups that were deleted because the user signed up but was not approved because they did not complete the verification process within the retention period. It was found that the metrics were also being incremented when the UserSignup was deleted due to exceeding deactivated retention period too which was not intentional and makes the metric inaccurate.
This PR fixes the bug by ensuring the metrics are only incremented for the unverified deletion case.
https://issues.redhat.com/browse/SANDBOX-679
=> Fix unverified UserSignup deletion metrics bug

controllers/space/space_controller.go
To properly auto-update NSTemplateSets when we enable or disable a feature for Spaces we need to watch for Space and NSTemplateSet annotations. This PR adds `AnnotationChangedPredicate` to the Space and NSTemplateSet watchers in the Space controller.
This PR should unblock https://github.com/codeready-toolchain/toolchain-e2e/pull/1008 which is currently failing because of this. I can't pair https://github.com/codeready-toolchain/toolchain-e2e/pull/1008 to this PR though because it's already paired with https://github.com/codeready-toolchain/member-operator/pull/580
=> Add annotation changed predicate for Space and NSTemplateSet watch

controllers/space/space_controller.go
The annotation predicate for NSTemplateTier was added by mistake. See https://github.com/codeready-toolchain/host-operator/pull/1061#discussion_r1686637235 for details.
=> Revert annotation predicate for tiertemplate

deploy/templates/nstemplatetiers/base1ns/cluster.yaml
This ClusterRoleBinding is managed by the `openshift-lightspeed` feature. See:
```
annotations:
toolchain.dev.openshift.com/feature: openshift-lightspeed
```
This should not affect anything until we:
- add the feature to the specific toolchain configuration
- get the OSL operator installed
Related to (not paired with!): https://github.com/codeready-toolchain/toolchain-e2e/pull/1016
=> Add OpenShift Lightspeed CRB to base1ns

go.mod, go.sum
This updates to the latest toolchain-common version. It should have been part of https://github.com/codeready-toolchain/host-operator/pull/1058 that I mistakenly merged with toolchain-common reference that is a commit behind.
=> Update to the latest toolchain-common version

deploy/registration-service/registration-service.yaml
we need to grant watch permissions to secrets so we can use controller-runtime cache to watch cache them.
I also simplified the permissions related to the Toolchain API - just simply added "view" permissions to the whole Toolchain API group
[KUBESAW-188](https://issues.redhat.com/browse/KUBESAW-188)
=> add watch permissions to secrets & CMs, and view to whole Toolchain api

controllers/toolchainstatus/toolchainstatus_controller.go, controllers/toolchainstatus/toolchainstatus_controller_test.go
Modifying the members array while we're indexing through it with a range is an unsafe operation.  Instead, create a new array and assign it after processing all elements.
=> avoid index out-of-bounds in toolchainstatus controller

deploy/registration-service/registration-service.yaml
https://github.com/codeready-toolchain/registration-service/pull/461#discussion_r1768083781
I'm listing the toolchain resources explicitly to match list of resources that the client cache of the registration-service is pre-populated with. Related PR https://github.com/codeready-toolchain/registration-service/pull/463
=> make sure that registration-service role matches the cache

make/go.mk
Introduce a make command for pre-requisite of verify-replace script
Related PRs:
Toolchain-common - https://github.com/codeready-toolchain/toolchain-common/pull/429 
Member Operator - https://github.com/codeready-toolchain/member-operator/pull/599
Toolchain-e2e - https://github.com/codeready-toolchain/toolchain-e2e/pull/1049
Registration service - https://github.com/codeready-toolchain/registration-service/pull/465
Ksctl - https://github.com/kubesaw/ksctl/pull/81
=> KUBESAW-192: Introduce a make command for pre-requisite of verify-replace

config/crd/bases/toolchain.dev.openshift.com_toolchainclusters.yaml
This is a continuation of https://github.com/codeready-toolchain/host-operator/pull/1094
=> Remove the ToolchainCluster.spec.apiEndpoint field

deploy/registration-service/registration-service.yaml
The label in member operator and host operator are diffferent as registration service uses a shorter name. 
this is related to https://github.com/kubesaw/ksctl/pull/79#discussion_r1781172443 and making the label same across host and member deployments
this is related to https://github.com/kubesaw/ksctl/pull/79
=> KUBESAW-187: Have similar label names in member and host

controllers/nstemplatetier/nstemplatetier_controller.go, controllers/nstemplatetier/nstemplatetier_controller_test.go
don't process NSTemplateTier that is being deleted, otherwise, the controller can create TTR CRs in the reconcile that was triggered by the "delete" call.
https://redhat-internal.slack.com/archives/C06MJ2DVBU4/p1737375318490079
=> don't process NSTemplateTier that is being deleted

controllers/spaceprovisionerconfig/mapper.go, controllers/spaceprovisionerconfig/mapper_test.go, controllers/spaceprovisionerconfig/spaceprovisionerconfig_controller.go, pkg/predicate/toolchainconditionchanged.go, pkg/predicate/toolchainconditionchanged_test.go
This is done by introducing a filter for the watch that should ignore any changes to the TCs that are only caused by the changes in the timestamps of the conditions.
FYI, I didn't create any e2e test for this because frankly, I am not sure how that would look like. There should be no change in the behavior and I don't really see a way of testing "the reconciliation shouldn't happen if I do this".
JIRA: https://issues.redhat.com/browse/KUBESAW-256
=> Try to reduce the log verbosity of the SPC controller.

make/manifests.mk
exposes `--replace-version` flag via `REPLACE_OPERATOR_VERSION` variable
related PR: https://github.com/codeready-toolchain/toolchain-cicd/pull/133
=> expose --replace-version flag via REPLACE_OPERATOR_VERSION variable

controllers/usersignup/usersignup_controller.go, controllers/usersignup/usersignup_controller_test.go, go.mod, go.sum, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go, test/usersignup_assertions.go
Measures the provision time of the UserSignups. 
The start-time is taken from the annotation set in reg-service, as the end-time is taken the moment when UserSignup is marked as Complete.
The provision time is measured only when:
* the user didn't have to complete the whole verification
* the UserSignup wasn't approved manually
* when the annotation is present
The annotation is removed to ensure that we don't record the provision time twice for the same user
TODO:
depends on:
https://github.com/codeready-toolchain/api/pull/464
https://github.com/codeready-toolchain/toolchain-common/pull/461
https://github.com/codeready-toolchain/registration-service/pull/515 (this needs to be merged first to properly test it in e2e tests)
paired with …
=> measure UserSignup provision time

controllers/usersignup/usersignup_controller.go, controllers/usersignup/usersignup_controller_test.go
the label is more reliable (annotations are removed after successfully verifying the phone, which I didn't realize before)
paired with https://github.com/codeready-toolchain/toolchain-e2e/pull/1127
[SANDBOX-957](https://issues.redhat.com/browse/SANDBOX-957)
=> rely on the phone hash label skipping tracked provision time

controllers/usersignup/usersignup_controller_test.go, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go
based on the discussion from: https://redhat-internal.slack.com/archives/CHK0J6HT6/p1741187208229359
adjusted the buckets so they are more human readable and they also span across the longer provision times:
1s, 2s, 3s, 5s, 10s, 30s, 1m, 2m, 3m, 6m, 1h
=> adjust buckets in provision time histogram

deploy/templates/notificationtemplates/sandbox/userprovisioned/notification.html, deploy/templates/notificationtemplates/sandbox/userprovisioned/subject.txt, pkg/templates/notificationtemplates/notification_generator_test.go
Per [this conversation ](https://redhat-internal.slack.com/archives/C07UWTB1BPB/p1742932177195959), I want to move away from using the word provisioning in our initial email to users because it could create confusion with the AAP 'provision' button/flow.
=> updates language from provisioning to ready in emails

config/crd/bases/toolchain.dev.openshift.com_bannedusers.yaml, config/crd/bases/toolchain.dev.openshift.com_masteruserrecords.yaml, config/crd/bases/toolchain.dev.openshift.com_notifications.yaml, config/crd/bases/toolchain.dev.openshift.com_nstemplatetiers.yaml, config/crd/bases/toolchain.dev.openshift.com_proxyplugins.yaml, config/crd/bases/toolchain.dev.openshift.com_socialevents.yaml, config/crd/bases/toolchain.dev.openshift.com_spacebindingrequests.yaml, config/crd/bases/toolchain.dev.openshift.com_spacebindings.yaml, config/crd/bases/toolchain.dev.openshift.com_spaceprovisionerconfigs.yaml, config/crd/bases/toolchain.dev.openshift.com_spacerequests.yaml, config/crd/bases/toolchain.dev.openshift.com_spaces.yaml, config/crd/bases/toolchain.dev.openshift.com_tiertemplaterevisions.yaml, config/crd/bases/toolchain.dev.openshift.com_tiertemplates.yaml, config/crd/bases/toolchain.dev.openshift.com_toolchainclusters.yaml, config/crd/bases/toolchain.dev.openshift.com_toolchainconfigs.yaml, config/crd/bases/toolchain.dev.openshift.com_toolchainstatuses.yaml, config/crd/bases/toolchain.dev.openshift.com_usersignups.yaml, config/crd/bases/toolchain.dev.openshift.com_usertiers.yaml
Generated by https://github.com/codeready-toolchain/api/pull/474
[SANDBOX-955](https://issues.redhat.com/browse/SANDBOX-955)
=> SANDBOX-955: update controller-gen.kubebuilder.io/version to v0.16.5

controllers/toolchainstatus/creation.go, controllers/toolchainstatus/creation_test.go
=> use the SSA apply client for create/update of the ToolchainStatus

config/manager/health_service.yaml, config/manager/kustomization.yaml, config/manager/manager.yaml
for probing via Blackbox Exporter
=> monitoring: service to access '/healthz' endpoint

cmd/main.go, pkg/constants/constants.go, pkg/constants/field_manager.go, pkg/templates/nstemplatetiers/nstemplatetier_generator.go, pkg/templates/nstemplatetiers/nstemplatetier_generator_test.go, pkg/templates/usertiers/usertier_generator.go, pkg/templates/usertiers/usertier_generator_test.go, test/nstemplatetier/nstemplatetier.go
This compiles the list of the `NSTemplateTier`s that are bundled in the binary and makes sure that any `NSTemplateTier` that is annotated as bundled and is NOT in that list, is automatically deleted if no longer used by any space.
This will provide a nice cleanup mechanism of the bundled `NSTemplateTier` that we no longer use.
It does not affect any user-defined `NSTemplateTier`s.
Related PRs:
- api: https://github.com/codeready-toolchain/api/pull/480
- toolchain-e2e: https://github.com/codeready-toolchain/toolchain-e2e/pull/1154
=> remove the bundled NSTemplateTiers that are no longer used

controllers/usersignupcleanup/usersignup_cleanup_controller.go, controllers/usersignupcleanup/usersignup_cleanup_controller_test.go
Currently the `Abandonned Signups (last 24hours) `matrix is counting some users as without phone verification initiated even when they were actually sent to the phone verification flow, but had error while doing the phone verification.
Hence updated to check the `usersigupuserhashlabel` and update  the matrix accordingly
=> SANDBOX-1225: Fix Phone verification matrix

cmd/main.go
Segment quota overpassed
see https://github.com/codeready-toolchain/host-operator/blob/master/controllers/usersignup/usersignup_controller.go#L713 where the call to Segment is skipped when the client is not initialized
=> console: temporary remove the DEVSANDBOX_SEGMENT_API_KEY annotation
